### ISSUE TITLE
SAM traceback after PIP update

### ISSUE THREAD

**Issue by Marakai** [awslabs/aws-sam-cli#1131]
### Description

I updated all my various AWS packages (CLI, SAM, boto3), as well as Python 2.7 and 3.6 to their latest releases on my Centos 7.5 dev machine.

Now SAM "crashes":

```
$ sam --version

Traceback (most recent call last):
  File "/usr/bin/sam", line 6, in <module>
    from samcli.cli.main import cli
  File "/usr/lib/python2.7/site-packages/samcli/cli/main.py", line 10, in <module>
    from .options import debug_option, region_option, profile_option
  File "/usr/lib/python2.7/site-packages/samcli/cli/options.py", line 8, in <module>
    from .context import Context
  File "/usr/lib/python2.7/site-packages/samcli/cli/context.py", line 6, in <module>
    import boto3
  File "/usr/lib/python2.7/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/lib/python2.7/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/usr/lib/python2.7/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/usr/lib/python2.7/site-packages/botocore/compat.py", line 26, in <module>
    from urllib3 import exceptions
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python2.7/site-packages/urllib3/util/__init__.py", line 4, in <module>
    from .request import make_headers
  File "/usr/lib/python2.7/site-packages/urllib3/util/request.py", line 5, in <module>
    from ..exceptions import UnrewindableBodyError
ImportError: cannot import name UnrewindableBodyError
```

### Steps to reproduce

Updated to:

- python-2.7.5-77.el7_6.x86_64
- python36u-3.6.7-1.ius.centos7.x86_64
- pip 19.0.3 from /usr/lib/python2.7/site-packages/pip (python 2.7)
- pip 19.0.3 from /usr/lib/python3.6/site-packages/pip (python 3.6)
- aws-cli/1.16.140 Python/3.6.7 Linux/3.10.0-957.10.1.el7.x86_64 botocore/1.12.130
- aws==0.2.5
- aws-sam-cli==0.14.2
- aws-sam-translator==1.10.0
- awscli==1.16.140

via:

- sudo yum update
- sudo pip2 install -U awscli aws-sam-cli pip
- sudo pip3 install -U awscli aws-sam-cli pip

Commands completed without errors.

### Observed result

See traceback above.

### Expected result

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: CentOS 7.5 (yum update freshly run)
2. `sam --version`: 0.14.2 via pip freeze, as calling sam --version results in traceback

**Comment by Marakai** [comment]
UPDATE: I've been able to - for now - work around this by following:

https://github.com/ansible/tower-cli/issues/603

Plus a reinstall of AWS CLI, however this leads to an unsatisfactory situation where PIP and YUM end up out of sync on the requests and urllib3 packages, with other issues that aren't germane to this ticket.

**Comment by TheSriram** [comment]
Have you tried linuxbrew?

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html

**Comment by Marakai** [comment]
@TheSriram ironically (seeing as my other dev machine is a Macbook where I *do* use Brew) it's not an option in our Linux environment, in an attempt to stick to "standard" tools.

**Comment by jfuss** [comment]
@Marakai Unfortunately, this is a system problem and we can't control or make sure yum and pip do not get out of sync. If you must use pip, this is something you would need to handle. I would push you to use linuxbrew as @TheSriram mentioned above. We know it is no standard but is currently the only other option we have for linux. This would alleviated the pip and yum is out of date and give you a better isolated installation.

Closing as the way forward is moving off of pip onto our Linuxbrew installer.
