### ISSUE TITLE
"sam build --use-container" does not work from Ubuntu WSL

### ISSUE THREAD

**Issue by johnc44** [awslabs/aws-sam-cli#1145]
### Description

Building using "sam build --use-container" does not work in Ubuntu WSL.

Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt

Without "--use-container" it works fine.

Docker is running via the Windows host, but seems to be fine from Ubuntu otherwise.

### Steps to reproduce

sam init -r python3.6  -n container-test
cd container-test

This works providing that I have activated a python 3.6 venv:
sam build

This does not:
sam build --use-container --debug

### Observed result

2019-04-23 14:30:31 Using SAM Template at /home/johnc/container-test/template.yaml
2019-04-23 14:30:31 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-04-23 14:30:31 Changing event name from before-call.apigateway to before-call.api-gateway
2019-04-23 14:30:31 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-04-23 14:30:31 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-04-23 14:30:31 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-04-23 14:30:31 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-04-23 14:30:31 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-04-23 14:30:31 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-04-23 14:30:31 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-04-23 14:30:31 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-04-23 14:30:31 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-04-23 14:30:31 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-04-23 14:30:31 Changing event name from before-call.apigateway to before-call.api-gateway
2019-04-23 14:30:31 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-04-23 14:30:31 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-04-23 14:30:31 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-04-23 14:30:31 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-04-23 14:30:31 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-04-23 14:30:31 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-04-23 14:30:31 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-04-23 14:30:31 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-04-23 14:30:31 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-04-23 14:30:31 'build' command is called
2019-04-23 14:30:31 Starting Build inside a container
2019-04-23 14:30:31 No Parameters detected in the template
2019-04-23 14:30:31 2 resources found in the template
2019-04-23 14:30:31 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2019-04-23 14:30:31 Trying paths: ['/home/johnc/.docker/config.json', '/home/johnc/.dockercfg']
2019-04-23 14:30:31 Found file at path: /home/johnc/.docker/config.json
2019-04-23 14:30:31 Found 'auths' section
2019-04-23 14:30:31 Found entry (registry='178744626600.dkr.ecr.ap-southeast-2.amazonaws.com', username='AWS')
2019-04-23 14:30:31 Found entry (registry='191328608789.dkr.ecr.ap-southeast-2.amazonaws.com', username='AWS')
2019-04-23 14:30:31 Building resource 'HelloWorldFunction'
2019-04-23 14:30:31 Starting new HTTP connection (1): 127.0.0.1:2375
2019-04-23 14:30:31 http://127.0.0.1:2375 "GET /v1.35/_ping HTTP/1.1" 200 2
2019-04-23 14:30:31 Trying paths: ['/home/johnc/.docker/config.json', '/home/johnc/.dockercfg']
2019-04-23 14:30:31 Found file at path: /home/johnc/.docker/config.json
2019-04-23 14:30:31 Found 'auths' section
2019-04-23 14:30:31 Found entry (registry='178744626600.dkr.ecr.ap-southeast-2.amazonaws.com', username='AWS')
2019-04-23 14:30:31 Found entry (registry='191328608789.dkr.ecr.ap-southeast-2.amazonaws.com', username='AWS')
2019-04-23 14:30:31 http://127.0.0.1:2375 "GET /v1.35/images/lambci/lambda:build-python3.6/json HTTP/1.1" 200 None
2019-04-23 14:30:31 Looking for auth config
2019-04-23 14:30:31 Looking for auth entry for 'docker.io'
2019-04-23 14:30:31 No entry found
2019-04-23 14:30:31 No auth config found
2019-04-23 14:30:32 http://127.0.0.1:2375 "POST /v1.35/images/create?tag=build-python3.6&fromImage=lambci%2Flambda HTTP/1.1" 200 None

Fetching lambci/lambda:build-python3.6 Docker container image......
2019-04-23 14:30:32 Mounting /home/johnc/container-test/hello_world as /tmp/samcli/source:ro,delegated inside runtime container
2019-04-23 14:30:32 Starting new HTTP connection (1): 127.0.0.1:2375
2019-04-23 14:30:32 http://127.0.0.1:2375 "POST /v1.35/containers/create HTTP/1.1" 201 90
2019-04-23 14:30:32 http://127.0.0.1:2375 "GET /v1.35/containers/9a228dbed35117fb1d5473bec3a33a4a2248686b401f57b6665b6f1de2c35bf9/json HTTP/1.1" 200 None
2019-04-23 14:30:32 http://127.0.0.1:2375 "GET /v1.35/containers/9a228dbed35117fb1d5473bec3a33a4a2248686b401f57b6665b6f1de2c35bf9/json HTTP/1.1" 200 None
2019-04-23 14:30:33 http://127.0.0.1:2375 "POST /v1.35/containers/9a228dbed35117fb1d5473bec3a33a4a2248686b401f57b6665b6f1de2c35bf9/start HTTP/1.1" 204 0
2019-04-23 14:30:33 http://127.0.0.1:2375 "GET /v1.35/containers/9a228dbed35117fb1d5473bec3a33a4a2248686b401f57b6665b6f1de2c35bf9/json HTTP/1.1" 200 None
2019-04-23 14:30:33 http://127.0.0.1:2375 "POST /containers/9a228dbed35117fb1d5473bec3a33a4a2248686b401f57b6665b6f1de2c35bf9/attach?stdout=1&stderr=1&logs=1&stream=1&stdin=0 HTTP/1.1" 101 0
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    self.scratch_dir
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 140, in build_dependencies
    raise RequirementsFileNotFoundError(requirements_path)
aws_lambda_builders.workflows.python_pip.packager.RequirementsFileNotFoundError: Requirements file not found: /tmp/samcli/source/requirements.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Requirements file not found: /tmp/samcli/source/requirements.txt
Builder workflow failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    self.scratch_dir
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 140, in build_dependencies
    raise RequirementsFileNotFoundError(requirements_path)
aws_lambda_builders.workflows.python_pip.packager.RequirementsFileNotFoundError: Requirements file not found: /tmp/samcli/source/requirements.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Requirements file not found: /tmp/samcli/source/requirements.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/__main__.py", line 137, in main
    mode=params.get('mode', None))
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/builder.py", line 115, in build
    return workflow.run()
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 65, in wrapper
    func(self, *args, **kwargs)
  File "/var/lang/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 257, in run
    reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt
2019-04-23 14:30:33 Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt"}}
2019-04-23 14:30:33 Starting new HTTP connection (2): 127.0.0.1:2375
2019-04-23 14:30:33 http://127.0.0.1:2375 "GET /v1.35/containers/9a228dbed35117fb1d5473bec3a33a4a2248686b401f57b6665b6f1de2c35bf9/json HTTP/1.1" 200 None
2019-04-23 14:30:34 http://127.0.0.1:2375 "DELETE /v1.35/containers/9a228dbed35117fb1d5473bec3a33a4a2248686b401f57b6665b6f1de2c35bf9?v=False&link=False&force=True HTTP/1.1" 204 0
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt

### Expected result

Sam should build python 3.6 lambda.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04.1 LTS running in Windows 10 WSL
2. `sam --version`: 0.15.0

**Comment by jfuss** [comment]
@johnc44 Where is the requirements file located in your project? Where is docker installed (Ubuntu or Windows)?

This smells like a docker sharing issue. SAM CLI does a bind mount and if the share settings are not enabled for where you are working, then docker swallows the error and pretends everything is fine. On Windows, we have seen needing to toggle the share settings (on drives/directories) for Docker for Windows to pick up the settings. Both are really unclear and an issue with Docker.

**Comment by nicmeriano** [comment]
@johnc44 Thank you! After countless hours researching you finally solved my problem. 
One question though, what does the wsl.conf do exactly? It seems to have "broken" a couple of paths.

**Comment by memee** [comment]
Hey, I have `c:\` mounted under `/c` but it still giving me following error:

```
sam build --use-container
Starting Build inside a container
Building function 'LambdaFunction'

Fetching lambci/lambda:build-python3.8 Docker container image......
Mounting /home/<lambda_source> as /tmp/samcli/source:ro,delegated inside runtime container
```
