### ISSUE TITLE
SAM CLI can't find `pip` module

### ISSUE THREAD

**Issue by mplewis** [awslabs/aws-sam-cli#1240]
### Description

SAM CLI can't find the `pip` package and `sam build` fails in the example Python 3.6 project.

I'd like to continue debugging, but I'm not sure of the following:

* which python/pip install SAM is using
* which installation is missing pip

I installed AWS CLI via pip, so I'm not sure what's missing. I don't have a Python 3 installation on this system that I know of. Any guidance is appreciated!

### Steps to reproduce

```
sam init --runtime python3.6
cd sam-app
# add a dependency to src/requirements.txt, e.g. uncomment `requests`
sam build
```

### Observed result

```
2019-06-25 10:13:32 Using SAM Template at /mnt/c/Users/emacdon2/Documents/Dashboard project/DVR_functionality/dvr_data_code/data_wrangle_code/lambda/template.yaml
2019-06-25 10:13:32 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-06-25 10:13:32 Changing event name from before-call.apigateway to before-call.api-gateway
2019-06-25 10:13:32 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-06-25 10:13:32 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-06-25 10:13:32 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-06-25 10:13:32 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-06-25 10:13:32 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-06-25 10:13:32 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-06-25 10:13:32 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-06-25 10:13:32 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-06-25 10:13:32 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-06-25 10:13:32 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-06-25 10:13:32 Changing event name from before-call.apigateway to before-call.api-gateway
2019-06-25 10:13:32 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-06-25 10:13:32 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-06-25 10:13:32 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-06-25 10:13:32 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-06-25 10:13:32 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-06-25 10:13:32 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-06-25 10:13:32 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-06-25 10:13:32 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-06-25 10:13:32 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-06-25 10:13:32 'build' command is called
2019-06-25 10:13:32 No Parameters detected in the template
2019-06-25 10:13:32 2 resources found in the template
2019-06-25 10:13:32 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2019-06-25 10:13:32 Building resource 'HelloWorldFunction'
2019-06-25 10:13:32 Loading workflow module 'aws_lambda_builders.workflows'
2019-06-25 10:13:33 Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2019-06-25 10:13:33 Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2019-06-25 10:13:33 Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2019-06-25 10:13:33 Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
2019-06-25 10:13:33 Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2019-06-25 10:13:33 Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2019-06-25 10:13:33 Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2019-06-25 10:13:33 Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2019-06-25 10:13:33 Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2019-06-25 10:13:33 Running workflow 'PythonPipBuilder'
2019-06-25 10:13:33 Running PythonPipBuilder:ResolveDependencies
2019-06-25 10:13:33 calling pip download -r /mnt/c/Users/emacdon2/Documents/Dashboard project/DVR_functionality/dvr_data_code/data_wrangle_code/lambda/hello_world/requirements.txt --dest /tmp/tmpB6L6D4
2019-06-25 10:13:34 PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/home/lizmacdonald/.local/lib/python2.7/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/home/lizmacdonald/.local/lib/python2.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    raise ActionFailedError(str(ex))
ActionFailedError: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pip'
```

### Expected result

`sam build` succeeds and installs packages from `requirements.txt` into the proper place in the project directory.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10, WSL 1 (Ubuntu)
2. `sam --version`: 0.17.0

**Comment by jfuss** [comment]
@mplewis For python, you need the `pip` installed for the version of python you are trying to build for. This is due to the nature of how pip/python works. That means you will need to install python3.6 and it be in the path in order to build the function. If you are ok with slightly slower builds, you can do `sam build --use-container` which will build in the specific runtime build container and then not have to manage another python version on your system.

**Comment by awood45** [comment]
Answered above - closing, feel free to reopen if you have further issues.

**Comment by stiliajohny** [comment]
> @mplewis For python, you need the `pip` installed for the version of python you are trying to build for. This is due to the nature of how pip/python works. That means you will need to install python3.6 and it be in the path in order to build the function. If you are ok with slightly slower builds, you can do `sam build --use-container` which will build in the specific runtime build container and then not have to manage another python version on your system.

That works !
