### ISSUE TITLE
"sam build" install issue for linux (multiple distros)

### ISSUE THREAD

**Issue by chrisdlangton** [awslabs/aws-sam-cli#1270]
Searched all 5 pages of open issues with "build" in it

### Description

```
Command 'build' is not configured correctly. Unable to import 'samcli.commands.build'
```

Occurs for distros;
 - Ubuntu, Xubuntu, Kubuntu 18.04, 17.10, 17.04
 - Debian Stretch

### Steps to reproduce

Using Xubuntu 18.04 `uname -a` 

```
Linux zhurong 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

`virtualenv --version` 16.6.1
`python --version` 3.7.3

prepare;

```
pip uninstall aws-sam-cli
pip uninstall docker
virtualenv -p $(which python3) .env
source .env/bin/activate
pip install aws-sam-cli
```

check `pip freeze`

```
aws-sam-cli==0.18.0
docker==3.7.3
```

### Observed result

```
2019-07-13 14:54:59 Command 'build' is not configured correctly. Unable to import 'samcli.commands.build'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/samcli/cli/command.py", line 103, in get_command
    mod = importlib.import_module(pkg_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/samcli/commands/build/__init__.py", line 6, in <module>
    from .command import cli  # noqa
  File "/usr/local/lib/python2.7/dist-packages/samcli/commands/build/command.py", line 13, in <module>
    from samcli.commands.build.build_context import BuildContext
  File "/usr/local/lib/python2.7/dist-packages/samcli/commands/build/build_context.py", line 14, in <module>
    from samcli.local.docker.manager import ContainerManager
  File "/usr/local/lib/python2.7/dist-packages/samcli/local/docker/manager.py", line 8, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
Usage: sam [OPTIONS] COMMAND [ARGS]...

Error: No such command "build".
```

### Expected result

obviously sam cli to work after fresh install

**Comment by chrisdlangton** [comment]
nevermind, i see pip installed to python2.7 instead of virtualenv python3 somehow and doing a `rm` of everything installed (why didn't pip uninstall do this?) then somehow everthing installed in the virtualenv and works fine.
