### ISSUE TITLE
 Command 'build' is not configured correctly. Unable to import 'samcli.commands.build'

### ISSUE THREAD

**Issue by gbugn** [awslabs/aws-sam-cli#1309]
Hi,

I just installed AWS SAM CLI on Windows 7.
When I ran 'sam build' command. I get this reponse.

sam build --template template.yml
2019-08-01 17:59:22 Command 'build' is not configured correctly. Unable to import 'samcli.commands.build'
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\command.py", line 103, in get_command
    mod = importlib.import_module(pkg_name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\__init__.py", line 6, in <module>
    from .command import cli  # noqa
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 14, in <module>
    from samcli.lib.build.app_builder import ApplicationBuilder, BuildError, UnsupportedBuilderLibraryVersionError, \
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 18, in <module>
    from samcli.local.docker.lambda_build_container import LambdaBuildContainer
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\lambda_build_container.py", line 13, in <module>
    from .container import Container
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\container.py", line 11, in <module>
    from samcli.local.docker.attach_api import attach
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\attach_api.py", line 8, in <module>
    from docker.utils.socket import read, read_exactly, SocketError
ModuleNotFoundError: No module named 'docker.utils.socket'
Usage: sam [OPTIONS] COMMAND [ARGS]...

Error: No such command "build".

Does anyone know how solve this ?
I'm using SAM CLI version 0.19.0

Regards

**Comment by awood45** [comment]
How did you install AWS SAM CLI?

**Comment by TheSriram** [comment]
Looks like this has been installed via the MSI, I just ran build without any issues on windows. Can you uninstall and re-install just to be sure.

**Comment by sriram-mv** [comment]
Closing as there has been no response.
