### ISSUE TITLE
MacOSX: "sam init" fails with mkdir() got an unexpected keyword argument

### ISSUE THREAD

**Issue by slimandslam** [awslabs/aws-sam-cli#1346]
### Description

Sam init fails with " mkdir() got an unexpected keyword argument 'exist_ok'"

### Steps to reproduce

MacOSX 10.14.6

```
$
$ python --version
Python 2.7.14
$ sam --version
SAM CLI, version 0.19.0
$ docker --version
Docker version 19.03.1, build 74b1e89
$ sam init --runtime python2.7
Traceback (most recent call last):
  File "/Users/auser/Library/Python/2.7/bin/sam", line 10, in <module>
    sys.exit(cli())
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/samcli/cli/main.py", line 83, in cli
    if global_cfg.telemetry_enabled is None:
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/samcli/cli/global_config.py", line 113, in telemetry_enabled
    self._telemetry_enabled = self._get_value(TELEMETRY_ENABLED_KEY)
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/samcli/cli/global_config.py", line 145, in _get_value
    cfg_path = self._get_config_file_path(CONFIG_FILENAME)
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/samcli/cli/global_config.py", line 170, in _get_config_file_path
    self._create_dir()
  File "/Users/auser/Library/Python/2.7/lib/python/site-packages/samcli/cli/global_config.py", line 167, in _create_dir
    self.config_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'
$

```
### Observed result

Fails.

### Expected result

Hello World app and framework should be installed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOSX 10.14.6
2. `sam --version`:  SAM CLI, version 0.19.0

**Comment by sanathkr** [comment]
Thanks for the issue. This happens because you have an older version of pathlib library installed.

 Can you check if you have pathlib installed globally using `pip list | grep pathlib`? If so, you can uninstall using `pip uninstall pathlib`. 

Also, you are using Python27 that will be deprecated very soon. On Mac, we vend a Homebrew based installer ([docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html#serverless-sam-cli-install-mac-sam-cli)) that will use the latest Python and do all the right setup for you. I would recommend migrating to it by first uninstalling the current one and reinstalling through brew

```
pip uninstall aws-sam-cli
brew tap aws/tap
brew install aws-sam-cli
```

**Comment by sanathkr** [comment]
I am going to close the issue because it has a fix. But feel free to reopen if you are still running into issues.
