### ISSUE TITLE
SAM local invoke with secrets manager

### ISSUE THREAD

**Issue by disbelief** [awslabs/aws-sam-cli#1390]
### Description

Hi there. I'm having a problem with SAM local invoke and want to clarify whether it's expected behaviour or not.

What I have is a lambda function that fetches a payload from Secrets Manager during its execution. The operation works fine in the real Lambda, but locally I get a 404 trying to fetch the secret.

### Steps to reproduce

Implement a function that fetches a secret from Secrets Manager during invocation.

```
sam local invoke "MyFunction" -e ./event.json --region us-east-1 --debug
```

### Observed result

```
2019-08-30 15:30:45 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-08-30 15:30:45 Changing event name from before-call.apigateway to before-call.api-gateway
2019-08-30 15:30:45 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-08-30 15:30:45 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-08-30 15:30:45 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-08-30 15:30:45 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-08-30 15:30:45 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-08-30 15:30:45 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-08-30 15:30:45 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-08-30 15:30:45 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-08-30 15:30:45 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-08-30 15:30:45 Setting config variable for region to 'us-east-1'
2019-08-30 15:30:45 local invoke command is called
2019-08-30 15:30:45 No Parameters detected in the template
2019-08-30 15:30:45 5 resources found in the template
2019-08-30 15:30:45 Found Serverless function with name='MyFunction' and CodeUri='./myFunction.zip'
2019-08-30 15:30:45 Trying paths: ['.docker/config.json', '.dockercfg']
2019-08-30 15:30:45 Found file at path: .docker/config.json
2019-08-30 15:30:45 Found 'auths' section
2019-08-30 15:30:45 Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
2019-08-30 15:30:45 http://localhost:None "GET /v1.35/_ping HTTP/1.1" 200 2
2019-08-30 15:30:45 Trying paths: ['.docker/config.json', '.dockercfg']
2019-08-30 15:30:45 Found file at path: .docker/config.json
2019-08-30 15:30:45 Found 'auths' section
2019-08-30 15:30:45 Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
2019-08-30 15:30:45 Found one Lambda function with name 'MyFunction'
2019-08-30 15:30:45 Invoking myFunction.default (nodejs10.x)
2019-08-30 15:30:45 Environment variables overrides data is standard format
2019-08-30 15:30:45 Loading AWS credentials from session with profile 'None'
2019-08-30 15:30:45 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-08-30 15:30:45 Changing event name from before-call.apigateway to before-call.api-gateway
2019-08-30 15:30:45 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-08-30 15:30:45 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-08-30 15:30:45 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-08-30 15:30:45 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-08-30 15:30:45 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-08-30 15:30:45 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-08-30 15:30:45 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-08-30 15:30:45 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-08-30 15:30:45 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-08-30 15:30:45 Setting config variable for region to 'us-east-1'
2019-08-30 15:30:45 Looking for credentials via: env
2019-08-30 15:30:45 Looking for credentials via: assume-role
2019-08-30 15:30:45 Looking for credentials via: shared-credentials-file
2019-08-30 15:30:45 Found credentials in shared credentials file: ~/.aws/credentials
2019-08-30 15:30:45 Resolving code path. Cwd=Projects/code, CodeUri=Projects/code/myFunction.zip
2019-08-30 15:30:45 Resolved absolute path to code is Projects/code/myFunction.zip
2019-08-30 15:30:45 Decompressing Projects/myFunction.zip
2019-08-30 15:30:46 Skipping building an image since no layers were defined
2019-08-30 15:30:46 Trying paths: ['.docker/config.json', '.dockercfg']
2019-08-30 15:30:46 Found file at path: .docker/config.json
2019-08-30 15:30:46 Found 'auths' section
2019-08-30 15:30:46 Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
2019-08-30 15:30:46 http://localhost:None "GET /v1.35/images/lambci/lambda:nodejs10.x/json HTTP/1.1" 200 None
2019-08-30 15:30:46 Looking for auth config
2019-08-30 15:30:46 Looking for auth entry for 'docker.io'
2019-08-30 15:30:46 Found 'https://index.docker.io/v1/'
2019-08-30 15:30:46 No auth config found
2019-08-30 15:30:49 http://localhost:None "POST /v1.35/images/create?tag=nodejs10.x&fromImage=lambci%2Flambda HTTP/1.1" 200 None

Fetching lambci/lambda:nodejs10.x Docker container image......
2019-08-30 15:30:49 Mounting /private/var/folders/nl/9h1yt20s0816j3fy844lf36h0000gn/T/tmpxf5tfhnp as /var/task:ro,delegated inside runtime container
2019-08-30 15:30:49 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 201 90
2019-08-30 15:30:49 http://localhost:None "GET /v1.35/containers/2a583b253d11ebdd2af81bbb4d5df5c3688fb6e7c8f03da01a9c16f3d931ce8e/json HTTP/1.1" 200 None
2019-08-30 15:30:49 http://localhost:None "GET /v1.35/containers/2a583b253d11ebdd2af81bbb4d5df5c3688fb6e7c8f03da01a9c16f3d931ce8e/json HTTP/1.1" 200 None
2019-08-30 15:30:50 http://localhost:None "POST /v1.35/containers/2a583b253d11ebdd2af81bbb4d5df5c3688fb6e7c8f03da01a9c16f3d931ce8e/start HTTP/1.1" 204 0
2019-08-30 15:30:50 Starting a timer for 5 seconds for function 'MyFunction'
2019-08-30 15:30:50 http://localhost:None "GET /v1.35/containers/2a583b253d11ebdd2af81bbb4d5df5c3688fb6e7c8f03da01a9c16f3d931ce8e/json HTTP/1.1" 200 None
2019-08-30 15:30:50 http://localhost:None "POST /containers/2a583b253d11ebdd2af81bbb4d5df5c3688fb6e7c8f03da01a9c16f3d931ce8e/attach?stdout=1&stderr=1&logs=1&stream=1&stdin=0 HTTP/1.1" 101 0
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
2019-08-30T12:30:51.548Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	aurora.getConnection false false
2019-08-30T12:30:51.548Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	aurora.connect
2019-08-30T12:30:51.549Z	52fdfc07-2182-154f-163f-5f0f9a621d72	INFO	getSecret:  development/database
2019-08-30T12:30:52.791Z	52fdfc07-2182-154f-163f-5f0f9a621d72	ERROR	We can't find the resource that you asked for. Deal with the exception here, and/or rethrow at your discretion.
2019-08-30T12:30:52.792Z	52fdfc07-2182-154f-163f-5f0f9a621d72	ERROR	Invoke Error	{"errorType":"ResourceNotFoundException","errorMessage":"Secrets Manager can’t find the specified secret.","code":"ResourceNotFoundException","stack":["ResourceNotFoundException: Secrets Manager can’t find the specified secret.","    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)","    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"],"message":"Secrets Manager can’t find the specified secret.","time":"2019-08-30T12:30:52.787Z","requestId":"d5223803-2e94-4d0f-8b33-835cdddba97e","statusCode":400,"retryable":false,"retryDelay":61.77811977135919}
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72	Duration: 1258.83 ms	Billed Duration: 1300 ms	Memory Size: 512 MB	Max Memory Used: 65 MB	
{
  "errorType": "ResourceNotFoundException",
  "errorMessage": "Secrets Manager can’t find the specified secret."
}
2019-08-30 15:30:53 http://localhost:None "GET /v1.35/containers/2a583b253d11ebdd2af81bbb4d5df5c3688fb6e7c8f03da01a9c16f3d931ce8e/json HTTP/1.1" 200 None
2019-08-30 15:30:53 http://localhost:None "DELETE /v1.35/containers/2a583b253d11ebdd2af81bbb4d5df5c3688fb6e7c8f03da01a9c16f3d931ce8e?v=False&link=False&force=True HTTP/1.1" 204 0
```

### Expected result

Expect to be able to successfully fetch and decrypt secrets from secrets manager as I would in live environment.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 10.14.6
2. `sam --version`: SAM CLI, version 0.18.0

**Comment by TheSriram** [comment]
Just tested this on a python app and it worked as expected, do you have all the credentials and correct region being passed in? can you try exporting `AWS_REGION` and `AWS_DEFAULT_REGION` in your local environment as well?

**Comment by disbelief** [comment]
Thanks this pointed me in the right direction.

It was the `aws-cli` profile. My other tooling (serverless framework) has it pre-configured, but I forgot to set it in my shell's environment. `AWS_PROFILE=profileName sam local invoke...` works now.

**Comment by chasedenecke** [comment]
Setting the AWS_REGION fixed the issue for me. For some reason my region was defaulting to us-east-1 even though I'm specifying us-west-2 in my config file. I had to set it to us-west-2 in the env file I passed to "sam local invoke".

`{
  "MyLambda": {
    "ENVIRONMENT": "dev",
    "ES_REGION": "us-west-2"
  }
}`
