### ISSUE TITLE
"Could not find an activated virtualenv (required)." In virtualenv with PIP_REQUIRE_VIRTUALENV="true"

### ISSUE THREAD

**Issue by joel-alejandre** [awslabs/aws-sam-cli#1440]
### Description

Running `sam build` results in the below error when using a virtualenv and having the environment variable `PIP_REQUIRE_VIRTUALENV="true"`:

```
Build Failed
Error: PythonPipBuilder:ResolveDependencies - ERROR: Could not find an activated virtualenv (required).
```

The same error was observed when with aws-sam-cli installed from both HomeBrew and PyPi.

Setting `PIP_REQUIRE_VIRTUALENV=""` allowed the build to complete.

### Steps to reproduce

* Set the environment variable `PIP_REQUIRE_VIRTUALENV` to `true`
* Create and activate a venv: `python -m venv .venv && source .venv/bin/activate`
* Run `sam build`

### Observed result

```
(.venv)$ sam build --debug
Using SAM Template at /Users/joel/Documents/aws-sam-s3-reko/template.yaml
'build' command is called
No Parameters detected in the template
3 resources found in the template
Found Serverless function with name='DetectTextInImage' and CodeUri='.'
Building resource 'DetectTextInImage'
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /Users/joel/Documents/aws-sam-s3-reko/requirements.txt --dest /var/folders/jc/fcfpfcdn2tb47zpmv1_hxsqm5jsjts/T/tmpcmetplk1
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/Users/joel/Documents/aws-sam-s3-reko/.venv/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    requirements_path=self.manifest_path
  File "/Users/joel/Documents/aws-sam-s3-reko/.venv/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 143, in build_dependencies
    requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/Users/joel/Documents/aws-sam-s3-reko/.venv/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 209, in build_site_packages
    scratch_directory, requirements_filepath)
  File "/Users/joel/Documents/aws-sam-s3-reko/.venv/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 234, in _download_dependencies
    requirements_filename, directory)
  File "/Users/joel/Documents/aws-sam-s3-reko/.venv/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 330, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "/Users/joel/Documents/aws-sam-s3-reko/.venv/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 632, in download_all_dependencies
    raise PackageDownloadError(error)
aws_lambda_builders.workflows.python_pip.packager.PackageDownloadError: ERROR: Could not find an activated virtualenv (required).


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joel/Documents/aws-sam-s3-reko/.venv/lib/python3.6/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/Users/joel/Documents/aws-sam-s3-reko/.venv/lib/python3.6/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: ERROR: Could not find an activated virtualenv (required).


Build Failed
Error: PythonPipBuilder:ResolveDependencies - ERROR: Could not find an activated virtualenv (required).
```

### Expected result

`sam build` to successfully run

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 10.14.6
2. `sam --version`: SAM CLI, version 0.22.0
3. Environment variable `PIP_REQUIRE_VIRTUALENV` set to `true`

**Comment by sriram-mv** [comment]
I'm not able to repro this with the latest version of SAM CLI and python version: 3.7.6.
while being within an virtualenv, please re-open if this still an issue.

**Comment by joel-alejandre** [comment]
@sriram-mv 

I just reproduced the error in a fresh Cloud9 instance:

```sh
export PIP_REQUIRE_VIRTUALENV=true

python -m venv .venv
. .venv/bin/activate

pip install aws-sam-cli
# 1 (quick start), 9 (python3.6), sam-app, 1 (Hello World Example)

cd sam-app

sam build
```

Returns:

```sh
Build Failed
Error: PythonPipBuilder:ResolveDependencies - Could not find an activated virtualenv (required).
```

**Comment by Th3G4mbl3r** [comment]
I am using poetry and pyenv to manage my dependencies and python environments. And i can simulate this exact error. Python version 3.8.8 and SAM CLI version 1.21.1.

**Comment by emibcn** [comment]
Hi @Th3G4mbl3r @joel-alejandre  ,
I'm facing the same problem on another project. Could you explain how was this solved?

Thanks in advance!
