### ISSUE TITLE
SAM CLI Breaking for no obvious reason. JSON Decoder Error

### ISSUE THREAD

**Issue by ryanpeach** [awslabs/aws-sam-cli#1528]
### Description

Briefly describe the bug you are facing.

### Steps to reproduce

I've not been able to reliably reproduce it, it seems to be sporadic.

### Observed result

No --debug, sorry:

```
Fetching lambci/lambda:build-python3.6 Docker container image......
Mounting /home/ubuntu/jenkins/workspace/UPRDC75D46KJVPBHJE74DO73RDK3QOKAWIAUPUI2M6BTMHJ4E3NA/icevws/src/asdf as /tmp/samcli/source:ro,delegated inside runtime container
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.31.0', 'console_scripts', 'sam')()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 93, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 99, in cli
    skip_pull_image, parameter_overrides, mode)  # pragma: no cover
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 153, in do_cli
    artifacts = builder.build()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 104, in build
    lambda_function.runtime)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 195, in _build_function
    runtime)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 272, in _build_function_on_container
    response = self._parse_builder_response(stdout_data, container.image)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.31.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 290, in _parse_builder_response
    response = json.loads(stdout_data)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Expected result

Just a normal compilation.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu
2. `sam --version`: latest

Sorry I couldn't be more specific.

This is on a jenkins build node in AWS btw. It also appears to be calling telemetry if that's relevant.

**Comment by sanathkr** [comment]
Looks like the Docker container terminated prematurely. There is a logging statement right above where exception happens. `--debug` would be helpful.

The `telemetry` reference in stack trace is a red herring. It is a decorator is a part of almost every call stack in SAM CLI

**Comment by longliveDT** [comment]
I'm having the same issue previously posted here with JSON Decoder Error running `sam init` command.

Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
OS: macOS Monterey
ssam --version                                     
SAM CLI, version 1.46.0

```
sam init --name postconfig --runtime python3.9 --debug
2022-05-10 23:56:44,298 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-05-10 23:56:44,298 | Using config file: samconfig.toml, config environment: default
2022-05-10 23:56:44,298 | Expand command line arguments to:
2022-05-10 23:56:44,298 | --name=ec2-postconfig --runtime=python3.9 --package_type=Zip --output_dir=. 
Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: 1
2022-05-10 23:56:45,924 | Template is not provided in context, skip adding project type metric
2022-05-10 23:56:45,925 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '2038647d-b9f9-4082-9e7a-de0da27fd0ef', 'installationId': '010bc22e-6811-4c72-98eb-e4c23f44b334', 'sessionId': 'e8a98889-e743-40e2-a081-6708acdf0b84', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.46.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam init', 'duration': 1626, 'exitReason': 'JSONDecodeError', 'exitCode': 255}}]}
2022-05-10 23:56:46,330 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/__init__.py", line 128, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/__init__.py", line 260, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/__init__.py", line 348, in do_cli
    do_interactive(
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/interactive_init_flow.py", line 60, in do_interactive
    generate_application(
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/interactive_init_flow.py", line 91, in generate_application
    _generate_from_use_case(
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/interactive_init_flow.py", line 140, in _generate_from_use_case
    preprocessed_options = templates.get_preprocessed_manifest(
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/init_templates.py", line 178, in get_preprocessed_manifest
    manifest_body = self._get_manifest()
  File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/init_templates.py", line 224, in _get_manifest
    manifest_body = json.loads(body)
  File "/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 101 column 18 (char 3617)
```

**Comment by barshopen** [comment]
> I'm having the same issue previously posted here with JSON Decoder Error running `sam init` command.
> 
> Additional environment details (Ex: Windows, Mac, Amazon Linux etc) OS: macOS Monterey sam --version SAM CLI, version 1.46.0
> 
> ```
> sam init --name postconfig --runtime python3.9 --debug
> 2022-05-10 23:56:44,298 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
> 2022-05-10 23:56:44,298 | Using config file: samconfig.toml, config environment: default
> 2022-05-10 23:56:44,298 | Expand command line arguments to:
> 2022-05-10 23:56:44,298 | --name=ec2-postconfig --runtime=python3.9 --package_type=Zip --output_dir=. 
> Which template source would you like to use?
> 	1 - AWS Quick Start Templates
> 	2 - Custom Template Location
> Choice: 1
> 2022-05-10 23:56:45,924 | Template is not provided in context, skip adding project type metric
> 2022-05-10 23:56:45,925 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '2038647d-b9f9-4082-9e7a-de0da27fd0ef', 'installationId': '010bc22e-6811-4c72-98eb-e4c23f44b334', 'sessionId': 'e8a98889-e743-40e2-a081-6708acdf0b84', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.46.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam init', 'duration': 1626, 'exitReason': 'JSONDecodeError', 'exitCode': 255}}]}
> 2022-05-10 23:56:46,330 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
> Traceback (most recent call last):
>   File "/usr/local/bin/sam", line 8, in <module>
>     sys.exit(cli())
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/__init__.py", line 128, in wrapped
>     return func(*args, **kwargs)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
>     return ctx.invoke(f, obj, *args, **kwargs)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 166, in wrapped
>     raise exception  # pylint: disable=raising-bad-type
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 124, in wrapped
>     return_value = func(*args, **kwargs)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
>     actual_result = func(*args, **kwargs)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 87, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/__init__.py", line 260, in cli
>     do_cli(
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/__init__.py", line 348, in do_cli
>     do_interactive(
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/interactive_init_flow.py", line 60, in do_interactive
>     generate_application(
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/interactive_init_flow.py", line 91, in generate_application
>     _generate_from_use_case(
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/interactive_init_flow.py", line 140, in _generate_from_use_case
>     preprocessed_options = templates.get_preprocessed_manifest(
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/init_templates.py", line 178, in get_preprocessed_manifest
>     manifest_body = self._get_manifest()
>   File "/usr/local/Cellar/aws-sam-cli/1.46.0/libexec/lib/python3.8/site-packages/samcli/commands/init/init_templates.py", line 224, in _get_manifest
>     manifest_body = json.loads(body)
>   File "/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 353, in raw_decode
>     obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 101 column 18 (char 3617)
> ```
@longliveDT 
Had the same issue. A quick version upgrade solve it for me. I'm now using 1.49 and everything seems fine
