### ISSUE TITLE
SAM local fails to execute a simple function

### ISSUE THREAD

**Issue by pierreis** [awslabs/aws-sam-cli#1539]
### Description

`sam invoke local` fails to execute a simple local function

### Steps to reproduce

The template is the following:

```
Transform: AWS::Serverless-2016-10-31

Resources:
  OrchestratorFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OrchestratorFn
      CodeUri: functions/orchestrator
      Runtime: nodejs10.x
      Handler: index.handler
```

### Observed result

```
sam local invoke -t test.yaml --debug --no-event OrchestratorFn
local invoke command is called
No Parameters detected in the template
1 resources found in the template
Found Serverless function with name='OrchestratorFn' and CodeUri='functions/orchestrator'
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.31.1', 'console_scripts', 'sam')()
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 48, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/samcli/commands/local/invoke/cli.py", line 84, in cli
    parameter_overrides,
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/samcli/commands/local/invoke/cli.py", line 144, in do_cli
    aws_profile=ctx.profile,
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/samcli/commands/local/cli_common/invoke_context.py", line 136, in __enter__
    if not self._container_manager.is_docker_reachable:
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/samcli/local/docker/manager.py", line 47, in is_docker_reachable
    self.docker_client.ping()
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/docker/client.py", line 187, in ping
    return self.api.ping(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/docker/api/daemon.py", line 166, in ping
    return self._result(self._get(self._url('/_ping'))) == 'OK'
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.31.1/libexec/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

### Expected result

Successful function execution.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 10.15
2. `sam --version`: 0.31.1

**Comment by jfuss** [comment]
@pierreis This is happening in trying to talk to docker. Do you have docker installed? Is it running?

**Comment by pierreis** [comment]
@jfuss You were right. Docker was installed and running, but not responding for some reason. Restarting it fixed the issue. Thanks for indicating the right direction!

**Comment by mkotsollaris** [comment]
I restarted docker and sam ran properly in my case.
