### ISSUE TITLE
Bug: CLI crashes when manifest.json file is no serializable

### ISSUE THREAD

**Issue by jfuss** [awslabs/aws-sam-cli#1540]
### Description

Stack trace for integ tests: 
```
Traceback (most recent call last):
  File "/home/appveyor/venv3.7.4/bin/samdev", line 11, in <module>
    load_entry_point('aws-sam-cli', 'console_scripts', 'samdev')()
  File "/home/appveyor/venv3.7.4/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/appveyor/venv3.7.4/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/appveyor/venv3.7.4/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/appveyor/venv3.7.4/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appveyor/venv3.7.4/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/appveyor/venv3.7.4/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/appveyor/venv3.7.4/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/appveyor/projects/aws-sam-cli/samcli/lib/telemetry/metrics.py", line 48, in wrapped
    return func(*args, **kwargs)
  File "/home/appveyor/projects/aws-sam-cli/samcli/commands/init/__init__.py", line 117, in cli
    extra_context,
  File "/home/appveyor/projects/aws-sam-cli/samcli/commands/init/__init__.py", line 154, in do_cli
    location = templates.location_from_app_template(runtime, dependency_manager, app_template)
  File "/home/appveyor/projects/aws-sam-cli/samcli/commands/init/init_templates.py", line 65, in location_from_app_template
    options = self.init_options(runtime, dependency_manager)
  File "/home/appveyor/projects/aws-sam-cli/samcli/commands/init/init_templates.py", line 85, in init_options
    return self._init_options_from_manifest(runtime, dependency_manager)
  File "/home/appveyor/projects/aws-sam-cli/samcli/commands/init/init_templates.py", line 91, in _init_options_from_manifest
    manifest_body = json.loads(body)
  File "/home/appveyor/.localpython3.7.4/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/appveyor/.localpython3.7.4/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/appveyor/.localpython3.7.4/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 39 column 5 (char 1086)
```

### Steps to reproduce

Update https://github.com/awslabs/aws-sam-cli-app-templates/blob/master/manifest.json to be invalid json. The above stack trace will happen when sam init is run.

This line needs some guard against none serialize data. https://github.com/awslabs/aws-sam-cli/blob/develop/samcli/commands/init/init_templates.py#L91

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
Closing this issue, There is travis ci testing in place for aws-sam-cli-templates.

https://github.com/awslabs/aws-sam-cli-app-templates/blob/master/tests/unit/test_json.py

**Comment by jfuss** [comment]
@sriram-mv Shouldn't we still have a check in SAM CLI to guard against this as well? I know there are tests in the other repo but we would still crash the CLI if this happens again.
