### ISSUE TITLE
Error while using sam cli

### ISSUE THREAD

**Issue by lp060** [awslabs/aws-sam-cli#1614]
### Description

I have been using sam cli from quite some time now with no issues. Today, suddenly, running any sam cli command gives me the following error. Please help to resolve the same. I am using Mac.

### Steps to reproduce

Provide steps to replicate.

### Observed result

Please provide command output with `--debug` flag set.
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.11.0', 'console_scripts', 'sam')()
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/samcli/cli/main.py", line 10, in <module>
    from .options import debug_option, region_option, profile_option
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/samcli/cli/options.py", line 8, in <module>
    from .context import Context
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/samcli/cli/context.py", line 6, in <module>
    import boto3
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 30, in <module>
    import botocore.credentials
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 42, in <module>
    from botocore.utils import InstanceMetadataFetcher, parse_key_val_file
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/botocore/utils.py", line 31, in <module>
    import botocore.httpsession
  File "/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/botocore/httpsession.py", line 7, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/usr/local/Cellar/aws-sam-cli/0.11.0/libexec/lib/python3.7/site-packages/urllib3/util/ssl_.py)

**Comment by jfuss** [comment]
You are using a very outdated version of SAM CLI (latest is 0.34.0). So I would start with upgrading.

This looks like it could be an outdated version of something related to ssl (guessing based on the stack trace). Upgrading should resolve this.

**Comment by sanathkr** [comment]
This doesn't look like a bug. Closing. Please reopen if you need help

**Comment by benji6** [comment]
I seem to have hit this same issue when installing aws-sam-cli version 0.41.0. I'm on Mac and have a very similar error stack. This is the first time I've tried installing aws-sam-cli. I have spent a long time trying to fix this and am giving up now. If anyone has managed to resolve this (maybe @lp060?) I'd appreciate any pointers. Thanks!

**Comment by floydpink** [comment]
I am seeing this exact same issue with sam v1.2.0 when running any command.

```
➜ sam --version
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.2.0', 'console_scripts', 'sam')())
  File "/usr/local/bin/sam", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/samcli/cli/main.py", line 10, in <module>
    from samcli.lib.telemetry.metrics import send_installed_metric
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 11, in <module>
    from samcli.cli.context import Context
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/samcli/cli/context.py", line 8, in <module>
    import boto3
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/session.py", line 30, in <module>
    import botocore.credentials
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/awsrequest.py", line 25, in <module>
    import botocore.utils
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/usr/local/Cellar/aws-sam-cli/1.2.0/libexec/lib/python3.7/site-packages/urllib3/util/ssl_.py)
```

OS: macOS Catalina (10.15.6)

```
➜ python --version
Python 3.8.5
```

```
➜ pip --version
pip 20.2.3 from ~/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pip (python 3.8)
```

```
➜ pyenv --version
pyenv 1.2.20
```

Can someone please provide any pointers on how I can resolve this?
