### ISSUE TITLE
"Create new SAM application" failing

### ISSUE THREAD

**Issue by boxabirds** [awslabs/aws-sam-cli#1655]
### Description

I can't create new SAM applications from inside VSCode.

### Steps to reproduce

1. from AWS Explorer menu, Choose "Create new SAM Application" 
1. I get this message:

> Unable to find SAM CLI. It is required in order to work with Serverless Applications locally. 
> Source: AWS Toolkit for Visual Studio Code (Extension)
> 

But I had installed it successfully, and I have Docker installed. So I tried again, to no avail. 

```
(lisn) bash-3.2$ brew tap aws/tap
Updating Homebrew...
(lisn) bash-3.2$ brew install aws-sam-cli
Warning: aws/tap/aws-sam-cli 0.37.0 is already installed and up-to-date
To reinstall 0.37.0, run `brew reinstall aws-sam-cli`
(lisn) bash-3.2$ brew reinstall aws-sam-cli
… installs again successfully…
```

### Observed result

Same issue. I look for the binary. I'm assuming at this point that the binary is called `aws-sam-cli` but that fails. But I do find `sam` in `/usr/local/bin` and it's version 0.37.0. 

I go to settings and set the SAM CLI path (though it doesn't tell me what the binary name is still so I can't in theory still do this but I'm assuming it's "sam")

Bingo: it runs, but fails sadly

```
2019-12-11 07:05:23 [ERROR]: An error occurred while creating a new SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
2019-12-11 07:05:23 [ERROR]: Error: SAM CLI was not found
	at throwIfInvalid (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliValidationUtils.js:11:15)
	at Object.throwAndNotifyIfInvalid (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliValidationUtils.js:27:9)
	at /Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/lambda/commands/createNewSamApp.js:115:33
	at Generator.next (<anonymous>)
	at fulfilled (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/lambda/commands/createNewSamApp.js:8:58)
2019-12-11 07:14:47 [ERROR]: An error occurred while creating a new SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
2019-12-11 07:14:47 [ERROR]: TypeError: Cannot read property 'on' of undefined
	at ChildProcess.<anonymous> (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:60:38)
	at Generator.next (<anonymous>)
	at /Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:7:12)
	at ChildProcess.start (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:55:16)
	at ChildProcess.<anonymous> (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:34:28)
	at Generator.next (<anonymous>)
	at /Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:7:12)
	at Promise (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:30:59)
	at new Promise (<anonymous>)
	at ChildProcess.<anonymous> (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:30:26)
	at Generator.next (<anonymous>)
	at /Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:7:12)
	at ChildProcess.run (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/utilities/childProcess.js:29:16)
	at DefaultSamCliProcessInvoker.<anonymous> (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliInvoker.js:43:39)
	at Generator.next (<anonymous>)
	at /Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliInvoker.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliInvoker.js:7:12)
	at DefaultSamCliProcessInvoker.invoke (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliInvoker.js:40:16)
	at SamCliInfoInvocation.<anonymous> (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliInfo.js:24:59)
	at Generator.next (<anonymous>)
	at /Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliInfo.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliInfo.js:7:12)
	at SamCliInfoInvocation.execute (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliInfo.js:23:16)
	at DefaultSamCliValidatorContext.<anonymous> (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliValidator.js:129:37)
	at Generator.next (<anonymous>)
	at /Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliValidator.js:11:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliValidator.js:7:12)
	at DefaultSamCliValidatorContext.getSamCliInfo (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliValidator.js:127:16)
	at DefaultSamCliValidator.<anonymous> (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliValidator.js:71:65)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/julian/.vscode/extensions/amazonwebservices.aws-toolkit-vscode-1.4.0/out/src/shared/sam/cli/samCliValidator.js:8:58)
```

### Expected result

AWS SAM application flow to successfully be invoked. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:   System Version:	macOS 10.14.6 (18G1012)
  Kernel Version:	Darwin 18.7.0
1. `sam --version`: 0.37.0
1. Using `pipenv`

**Comment by TheSriram** [comment]
Thanks for the Report! Does `/usr/local/bin/sam init` generate prompts to create a new application?

**Comment by sriram-mv** [comment]
Closing this issue here, looks like the issue needs to be filed at: https://github.com/aws/aws-toolkit-vscode
