### ISSUE TITLE
Invalid path causes fail with Access is denied error

### ISSUE THREAD

**Issue by sasha-int** [awslabs/aws-sam-cli#1660]
Downloaded SAM for the first time and trying to deploy the sample application. Replied "Y" to 
> Quick start templates may have been updated. Do you want to re-download the latest [Y/n]:

This led to the following error. 
```
Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 93, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\__init__.py", line 119, in cli
    extra_context,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\__init__.py", line 176, in do_cli
    do_interactive(location, runtime, dependency_manager, output_dir, name, app_template, no_input)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\interactive_init_flow.py", line 36, in do_interactive
    _generate_from_app_template(location, runtime, dependency_manager, output_dir, name, app_template)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\interactive_init_flow.py", line 66, in _generate_from_app_template
    location, app_template = templates.prompt_for_location(runtime, dependency_manager)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 34, in prompt_for_location
    options = self.init_options(runtime, dependency_manager)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 82, in init_options
    self._clone_repo()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 125, in _clone_repo
    if self._should_clone_repo(expected_path):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 162, in _should_clone_repo
    shutil.rmtree(expected_path)  # fail hard if there is an issue
  File "shutil.py", line 494, in rmtree
  File "shutil.py", line 384, in _rmtree_unsafe
  File "shutil.py", line 384, in _rmtree_unsafe
  File "shutil.py", line 384, in _rmtree_unsafe
  File "shutil.py", line 389, in _rmtree_unsafe
  File "shutil.py", line 387, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\sasha\\AppData\\Roaming\\AWS SAM\\aws-sam-cli-app-templates\\.git\\objects\\pack\\pack-519630ea1cad60f98b65aa88c7c9928878e3d179.idx'
```

The object at the specified path is there, and no rules restricting access are applied to it. 
From what it looks like the path generated in windows is wrong.
Tried to do this with multiple application types.

**Comment by y-kitami** [comment]
@sasha-int
Is it for the first access?
It seems to looks like access more than once.

> > Quick start templates may have been updated. Do you want to **re-download** the latest [Y/n]:

If template files exists, try it. (be careful for typo)
`.git` below template directory may be the cause of failure.

```batch
rmdir /S /Q "%APPDATA%\AWS SAM\aws-sam-cli-app-templates"
```

**Comment by sasha-int** [comment]
1. Creating the application without re-downloading the templates works. 
1. Deleting 

> %APPDATA%\AWS SAM\aws-sam-cli-app-templates

Worked and the templates re-downloaded.

**Comment by awood45** [comment]
When the app templates are updated, we delete the old version of app templates. The logic for this is being updated to be a bit safer in this case, but if we don't have file deletion permissions in the shared directory, this will be an issue. Have you run into a recurrence of this problem?

**Comment by y-kitami** [comment]
@awood45 
On windows git, idx has readonly attributes.

```powershell
 (gi .\aws-sam-cli-app-templates\.git\objects\pack\pack-519630ea1cad60f98b65aa88c7c9928878e3d17
9.idx).Attributes
ReadOnly, Archive
```

for readonly files, `shutil.rmtree` needs some tricks.

https://stackoverflow.com/questions/21261132/shutil-rmtree-to-remove-readonly-files

**Comment by sriram-mv** [comment]
This has been since been fixed.

**Comment by SSkupien** [comment]
Hi, I encountered a similar problem.
I was running this command:
`PS C:\AWS\Repos\SomeRepo> sam init --location https://github.com/SomeRepo.git`
And get below errors:
```Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\init\__init__.py", line 80, in generate_project
    cookiecutter(**params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\cookiecutter\main.py", line 63, in cookiecutter
    password=password
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\cookiecutter\repository.py", line 122, in determine_repo_dir
    '\n'.join(repository_candidates)
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "https://github.com/SomeRepo.git" could not be found in the following locations:
C:\Users\sebastian.skupien\.cookiecutters\SomeRepo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 193, in _run_module_as_main
  File "runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\__init__.py", line 119, in cli
    extra_context,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\__init__.py", line 162, in do_cli
    do_generate(location, runtime, dependency_manager, output_dir, name, no_input, extra_context)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_generator.py", line 12, in do_generate
    generate_project(location, runtime, dependency_manager, output_dir, name, no_input, extra_context)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\init\__init__.py", line 89, in generate_project
    generate_non_cookiecutter_project(location=params["template"], output_dir=project_output_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\init\arbitrary_project.py", line 81, in generate_non_cookiecutter_project
    return _download_and_copy(download_fn, output_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\init\arbitrary_project.py", line 108, in _download_and_copy
    osutils.copytree(downloaded_dir, output_dir, ignore=shutil.ignore_patterns("*.git"))
  File "contextlib.py", line 88, in __exit__
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 49, in mkdir_temp
    shutil.rmtree(temp_dir)
  File "shutil.py", line 494, in rmtree
  File "shutil.py", line 384, in _rmtree_unsafe
  File "shutil.py", line 384, in _rmtree_unsafe
  File "shutil.py", line 384, in _rmtree_unsafe
  [Previous line repeated 1 more time]
  File "shutil.py", line 389, in _rmtree_unsafe
  File "shutil.py", line 387, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\SEBAST~1.SKU\\AppData\\Local\\Temp\\tmplsges85r\\SomeRepo\\.git\\objects\\00\\2faae162a383593bd1e795c1d0676487e37800'
```
Actually the files I wanted to copy to destination folder were successfully copied so I assume this errors occur during last part of command exectucion, possible on some clean up.

Maybe someone can give me some insight on this?

**Comment by jfuss** [comment]
@SSkupien what version of SAM cli are you running?

**Comment by SSkupien** [comment]
@jfuss SAM CLI, version 0.40.0

**Comment by jfuss** [comment]
@SSkupien This issue should have been solve in that version. I do notice this error in your output: `cookiecutter.exceptions.RepositoryNotFound: A valid repository for "https://github.com/SomeRepo.git" could not be found in the following locations:`. Is the thing you are init'ing a valid repo?

**Comment by SSkupien** [comment]
@jfuss Yes, it is a valid repo that I'm working on and I can normally clone it and do normal git "stuff".
I was trying to use this sam init for purposes of replicating this repo for a different kind of use, so treat it as template repo for future projects. I wanted to initialize it, then change namings and have a solution for different use to not start from scratch each time. 

Actually maybe I need to explain a little bit more:
- I really have no idea what is this cookiecutter
- When I use `sam init` the .cookiecutter folder is created and I think the repo is downloaded there first, then it is copied to my destination
- Maybe this error occurs because in this cookiecutter folder isn't a valid git folder? But it is created during execution so I am not sure about that

**Comment by sriram-mv** [comment]
@SSkupien Do you see this across all github repos, or any specific repo?

**Comment by SSkupien** [comment]
@sriram-mv I checked it today and it occurs for all github repos I tried

**Comment by candangonocanada** [comment]
Hi, I am facing a similar issue when trying to run the "sam init" for the first time.

Similar error is happening through Visual Studio.

`Documents\GitHub> sam init --runtime python3.8
Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 2

Template location (git, mercurial, http(s), zip, path): https://github.com/awslabs/aws-sam-cli-app-templates.git

-----------------------
Generating application:
-----------------------
Location: https://github.com/awslabs/aws-sam-cli-app-templates.git
Output Directory: .

You've downloaded C:\Users\ThiagoLimadeMenezes\.cookiecutters\aws-sam-cli-app-templates before. Is it okay to delete and re-download it? [yes]: y
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\init\__init__.py", line 80, in generate_project
    cookiecutter(**params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\cookiecutter\main.py", line 63, in cookiecutter
    password=password
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\cookiecutter\repository.py", line 122, in determine_repo_dir
    '\n'.join(repository_candidates)
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "https://github.com/awslabs/aws-sam-cli-app-templates.git" could not be found in the following locations:
C:\Users\ThiagoLimadeMenezes\.cookiecutters\aws-sam-cli-app-templates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 42, in mkdir_temp
    yield temp_dir
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\init\arbitrary_project.py", line 107, in _download_and_copy
    downloaded_dir = download_fn(clone_to_dir=tempdir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\cookiecutter\vcs.py", line 99, in clone
    stderr=subprocess.STDOUT,
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 411, in check_output
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/awslabs/aws-sam-cli-app-templates.git']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\__init__.py", line 118, in cli
    extra_context,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\__init__.py", line 177, in do_cli
    do_interactive(location, runtime, dependency_manager, output_dir, name, app_template, no_input)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\interactive_init_flow.py", line 33, in do_interactive
    _generate_from_location(location, runtime, dependency_manager, output_dir, name, app_template, no_input)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\interactive_init_flow.py", line 50, in _generate_from_location
    do_generate(location, runtime, dependency_manager, output_dir, name, no_input, None)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_generator.py", line 12, in do_generate
    generate_project(location, runtime, dependency_manager, output_dir, name, no_input, extra_context)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\init\__init__.py", line 89, in generate_project
    generate_non_cookiecutter_project(location=params["template"], output_dir=project_output_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\init\arbitrary_project.py", line 81, in generate_non_cookiecutter_project
    return _download_and_copy(download_fn, output_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\init\arbitrary_project.py", line 108, in _download_and_copy
    osutils.copytree(downloaded_dir, output_dir, ignore=shutil.ignore_patterns("*.git"))
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 130, in __exit__
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 49, in mkdir_temp
    shutil.rmtree(temp_dir)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  [Previous line repeated 1 more time]
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 400, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 398, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\THIAGO~1\\AppData\\Local\\Temp\\tmpcbtajw78\\aws-sam-cli-app-templates\\.git\\objects\\pack\\pack-698795756a16f2bbfbd283e5ce73ff2c211f5070.idx'`
