### ISSUE TITLE
Doesn't pick the right venv python

### ISSUE THREAD

**Issue by ruivapps** [awslabs/aws-sam-cli#1721]
Fresh new Python 3.8.1 venv environment with up2date pip and samcli.

```bash
$ /opt/local/bin/python3 -m venv /tmp/p3source /tmp/p3/bin/activate
$ source /tmp/p3/bin/activate
$ pip -q install -U pip aws-sam-cli

$ python -c "import sys, pip, samcli;print(f'Python: {sys.version}\nSamCLI: {samcli.__version__}\tPIP:{pip.__version__}\nExec: {sys.executable}')"

Python: 3.8.1 (default, Dec 22 2019, 00:43:28)
[Clang 11.0.0 (clang-1100.0.33.12)]
SamCLI: 0.39.0	PIP:19.3.1
Exec: /private/tmp/p3/bin/python
```

create a new hello example

```bash
$ sam init --name sam-app --runtime python3.8 --app-template hello-world                                                         <<<

Cloning app templates from https://github.com/awslabs/aws-sam-cli-app-templates.git

-----------------------
Generating application:
-----------------------
Name: sam-app
Runtime: python3.8
Dependency Manager: pip
Application Template: hello-world
Output Directory: .

Next steps can be found in the README file at ./sam-app/README.md
```

sam build does not work

```
$ cd sam-app
$ sam build

Building resource 'HelloWorldFunction'
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: ''
```

debug version

```bash
PythonPipBuilder:ResolveDependencies raised unhandled exception
Traceback (most recent call last):
  File "/private/tmp/p3/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/private/tmp/p3/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 27, in execute
    pip = SubprocessPip(osutils=os_utils, python_exe=python_path)
  File "/private/tmp/p3/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 556, in __init__
    import_string = pip_import_string(python_exe=self.python_exe)
  File "/private/tmp/p3/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/compat.py", line 16, in pip_import_string
    pip_major_version = int(pip_version.split('.')[0])
ValueError: invalid literal for int() with base 10: ''
```

**Issue**
aws_lambda_builders/workflows/python_pip -> pip_import_string was trying to

```python
cmd = [python_exe, "-c", "import pip; print(pip.__version__)"]
p = os_utils.popen(cmd, stdout=os_utils.pipe, stderr=os_utils.pipe)
stdout, stderr = p.communicate()
pip_version = stdout.decode('utf-8').strip()
pip_major_version = int(pip_version.split('.')[0])
pip_minor_version = int(pip_version.split('.')[1])
```

adding a **print** function to above to check cmd, stdout and stderr

```bash
print(f'CMD: {cmd}, stdout: {stdout}, stderr: {stderr}')

CMD: ['/opt/local/bin/python3.8', '-c', 'import pip; print(pip.__version__)'], stdout: b'', stderr: b'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nModuleNotFoundError: No module named \'pip\'\n'
```

How to reproduce:
1. Install Python3.8 without PIP
2. Create new venv environment (pip included)
3. active new venv environment
4. install/upgrade aws-sam-cli
5. sam init --name sam-app --runtime python3.8 --app-template hello-world 
6. cd sam-app && sam build --debug

**Comment by include** [comment]
Hi @ruivapps.

I've followed your 'reproduce' notes but didn't get the same results.

Here mine:

```
$ brew install python@3.8
$ echo 'export PATH="/usr/local/opt/python@3.8/bin:$PATH"' >> ~/.zshrc
$ source ~/.zshrc

$ mkdir /tmp/test ; cd /tmp/test
$ python3.8 -m venv py3.8
$ source ./py3.8/bin/activate
$ which pip
/private/tmp/test/p38/bin/pip
$ pip --version
pip 19.2.3 from /private/tmp/test/p38/lib/python3.8/site-packages/pip (python 3.8)
$ pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-19.3.1

$ pip install aws-sam-cli awscli
Collecting aws-sam-cli
  Using cached https://files.pythonhosted.org/packages/83/be/96f244486a18f062eb198b09a33b6d117b23fd3105a4509c0d6dee094143/aws_sam_cli-0.40.0-py3-none-any.whl
Collecting awscli
  Using cached https://files.pythonhosted.org/packages/cb/78/c8a148404328badf94a0e50dabe081175d414e1102208b47654e062344ee/awscli-1.17.0-py2.py3-none-any.whl
Collecting chevron~=0.12
  Using cached https://files.pythonhosted.org/packages/a3/1e/6ef58385f54c5bbf70b3b451930015aa2d30b3cd5ae324bba4da77c5b889/chevron-0.13.1-py3-none-any.whl
Collecting docker~=4.0
  Using cached https://files.pythonhosted.org/packages/cc/ca/699d4754a932787ef353a157ada74efd1ceb6d1fc0bfb7989ae1e7b33111/docker-4.1.0-py2.py3-none-any.whl
Collecting aws-sam-translator==1.19.1
  Using cached https://files.pythonhosted.org/packages/a4/fb/46a67369e4e71cab8e73ca73ca0b938c297767d0ef8cfcad21b4f064ed66/aws-sam-translator-1.19.1.tar.gz
Collecting serverlessrepo==0.1.9
  Using cached https://files.pythonhosted.org/packages/69/a8/3500d8ecd5e14a94b771e5f78a35313f94232cbde41b37888ce88fd9e07c/serverlessrepo-0.1.9-py2.py3-none-any.whl
Collecting Flask~=1.0.2
  Using cached https://files.pythonhosted.org/packages/d8/94/7350820ae209ccdba073f83220cea1c376f2621254d1e0e82609c9a65e58/Flask-1.0.4-py2.py3-none-any.whl
Collecting python-dateutil<2.8.1,~=2.6
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting cookiecutter~=1.6.0
  Using cached https://files.pythonhosted.org/packages/16/99/1ca3a75978270288354f419e9166666801cf7e7d8df984de44a7d5d8b8d0/cookiecutter-1.6.0-py2.py3-none-any.whl
Collecting PyYAML~=5.1
  Using cached https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz
Collecting aws-lambda-builders==0.6.0
  Using cached https://files.pythonhosted.org/packages/7d/53/167101e7c22921c64b9b823bfe56c946582d2e1aecf8ca8f3a1f73594194/aws_lambda_builders-0.6.0-py3-none-any.whl
Collecting jmespath~=0.9.4
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting boto3>=1.10.29,~=1.10
  Using cached https://files.pythonhosted.org/packages/4c/b7/a8504dce343495e6da14745280746634c27b0618355d5d7082489cb10673/boto3-1.11.0-py2.py3-none-any.whl
Collecting tomlkit==0.5.8
  Using cached https://files.pythonhosted.org/packages/3e/30/7c2693fc50bd466285ec22bf02ee344be1bde3e2e8267e302fdc82d11f2d/tomlkit-0.5.8-py2.py3-none-any.whl
Collecting click~=7.0
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting requests==2.22.0
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting dateparser~=0.7
  Using cached https://files.pythonhosted.org/packages/82/9d/51126ac615bbc4418478d725a5fa1a0f112059f6f111e4b48cfbe17ef9d0/dateparser-0.7.2-py2.py3-none-any.whl
Collecting colorama<0.4.2,>=0.2.5
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting s3transfer<0.4.0,>=0.3.0
  Using cached https://files.pythonhosted.org/packages/d5/29/2a79d0223617d255eccac5fd9c147d65ee32f9aabe0e47ab75fd7568af24/s3transfer-0.3.0-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting botocore==1.14.0
  Using cached https://files.pythonhosted.org/packages/44/22/ea0756613d704e2cab650b8defe07a1964d3a31133c5c10dcc1803b58b52/botocore-1.14.0-py2.py3-none-any.whl
Collecting rsa<=3.5.0,>=3.1.2
  Using cached https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl
Collecting websocket-client>=0.32.0
  Using cached https://files.pythonhosted.org/packages/4c/5f/f61b420143ed1c8dc69f9eaec5ff1ac36109d52c80de49d66e0c36c3dfdf/websocket_client-0.57.0-py2.py3-none-any.whl
Collecting six>=1.4.0
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting jsonschema~=3.0
  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.14
  Using cached https://files.pythonhosted.org/packages/ce/42/3aeda98f96e85fd26180534d36570e4d18108d62ae36f87694b476b83d6f/Werkzeug-0.16.0-py2.py3-none-any.whl
Collecting Jinja2>=2.10
  Using cached https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl
Collecting itsdangerous>=0.24
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting future>=0.15.2
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Collecting whichcraft>=0.4.0
  Using cached https://files.pythonhosted.org/packages/b5/a2/81887a0dae2e4d2adc70d9a3557fdda969f863ced51cd3c47b587d25bce5/whichcraft-0.6.1-py2.py3-none-any.whl
Collecting binaryornot>=0.2.0
  Using cached https://files.pythonhosted.org/packages/24/7e/f7b6f453e6481d1e233540262ccbfcf89adcd43606f44a028d7f5fae5eb2/binaryornot-0.4.4-py2.py3-none-any.whl
Collecting jinja2-time>=0.1.0
  Using cached https://files.pythonhosted.org/packages/6a/a1/d44fa38306ffa34a7e1af09632b158e13ec89670ce491f8a15af3ebcb4e4/jinja2_time-0.2.0-py2.py3-none-any.whl
Collecting poyo>=0.1.0
  Using cached https://files.pythonhosted.org/packages/42/50/0b0820601bde2eda403f47b9a4a1f270098ed0dd4c00c443d883164bdccc/poyo-0.5.0-py2.py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./p38/lib/python3.8/site-packages (from aws-lambda-builders==0.6.0->aws-sam-cli) (41.2.0)
Collecting idna<2.9,>=2.5
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
Collecting tzlocal
  Using cached https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl
Collecting pytz
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting regex
  Using cached https://files.pythonhosted.org/packages/73/d9/b58289d885180b5d538aa6df07974b5fe6088547ac846c0f76f77259c304/regex-2020.1.8.tar.gz
Collecting pyasn1>=0.1.3
  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
Collecting pyrsistent>=0.14.0
  Using cached https://files.pythonhosted.org/packages/90/aa/cdcf7ef88cc0f831b6f14c8c57318824c9de9913fe8de38e46a98c069a35/pyrsistent-0.15.7.tar.gz
Collecting attrs>=17.4.0
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23
  Using cached https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz
Collecting arrow
  Using cached https://files.pythonhosted.org/packages/92/fa/f84896dede5decf284e6922134bf03fd26c90870bbf8015f4e8ee2a07bcc/arrow-0.15.5-py2.py3-none-any.whl
ERROR: awscli 1.17.0 has requirement PyYAML<5.3,>=3.10, but you'll have pyyaml 5.3 which is incompatible.
Installing collected packages: chevron, six, websocket-client, idna, urllib3, chardet, certifi, requests, docker, docutils, python-dateutil, jmespath, botocore, s3transfer, boto3, pyrsistent, attrs, jsonschema, aws-sam-translator, PyYAML, serverlessrepo, Werkzeug, click, MarkupSafe, Jinja2, itsdangerous, Flask, future, whichcraft, binaryornot, arrow, jinja2-time, poyo, cookiecutter, wheel, aws-lambda-builders, tomlkit, pytz, tzlocal, regex, dateparser, aws-sam-cli, colorama, pyasn1, rsa, awscli
    Running setup.py install for pyrsistent ... done
    Running setup.py install for aws-sam-translator ... done
    Running setup.py install for PyYAML ... done
    Running setup.py install for MarkupSafe ... done
    Running setup.py install for future ... done
    Running setup.py install for regex ... done
Successfully installed Flask-1.0.4 Jinja2-2.10.3 MarkupSafe-1.1.1 PyYAML-5.3 Werkzeug-0.16.0 arrow-0.15.5 attrs-19.3.0 aws-lambda-builders-0.6.0 aws-sam-cli-0.40.0 aws-sam-translator-1.19.1 awscli-1.17.0 binaryornot-0.4.4 boto3-1.11.0 botocore-1.14.0 certifi-2019.11.28 chardet-3.0.4 chevron-0.13.1 click-7.0 colorama-0.4.1 cookiecutter-1.6.0 dateparser-0.7.2 docker-4.1.0 docutils-0.15.2 future-0.18.2 idna-2.8 itsdangerous-1.1.0 jinja2-time-0.2.0 jmespath-0.9.4 jsonschema-3.2.0 poyo-0.5.0 pyasn1-0.4.8 pyrsistent-0.15.7 python-dateutil-2.8.0 pytz-2019.3 regex-2020.1.8 requests-2.22.0 rsa-3.4.2 s3transfer-0.3.0 serverlessrepo-0.1.9 six-1.13.0 tomlkit-0.5.8 tzlocal-2.0.0 urllib3-1.25.7 websocket-client-0.57.0 wheel-0.33.6 whichcraft-0.6.1

$ sam init --name sam-app --runtime python3.8 --app-template hello-world
Cloning app templates from https://github.com/awslabs/aws-sam-cli-app-templates.git

-----------------------
Generating application:
-----------------------
Name: sam-app
Runtime: python3.8
Dependency Manager: pip
Application Template: hello-world
Output Directory: .

Next steps can be found in the README file at ./sam-app/README.md

$ sam build --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
Building resource 'HelloWorldFunction'
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /private/tmp/test/sam-app/hello_world/requirements.txt --dest /var/folders/0b/nbhcs96j7pz5v30ptkkbkbxr0000gn/T/tmp_ll2pekn
Full dependency closure: {certifi==2019.11.28(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), requests==2.22.0(wheel), chardet==3.0.4(wheel)}
initial compatible: {certifi==2019.11.28(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), requests==2.22.0(wheel), chardet==3.0.4(wheel)}
initial incompatible: set()
Downloading missing wheels: set()
compatible wheels after second download pass: {certifi==2019.11.28(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), requests==2.22.0(wheel), chardet==3.0.4(wheel)}
Build missing wheels from sdists (C compiling True): set()
compatible after building wheels (no C compiling): {certifi==2019.11.28(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), requests==2.22.0(wheel), chardet==3.0.4(wheel)}
Build missing wheels from sdists (C compiling False): set()
compatible after building wheels (C compiling): {certifi==2019.11.28(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), requests==2.22.0(wheel), chardet==3.0.4(wheel)}
Final compatible: {certifi==2019.11.28(wheel), chardet==3.0.4(wheel), idna==2.8(wheel), urllib3==1.25.7(wheel), requests==2.22.0(wheel)}
Final incompatible: set()
Final missing wheels: set()
PythonPipBuilder:ResolveDependencies succeeded
Running PythonPipBuilder:CopySource
PythonPipBuilder:CopySource succeeded

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided

Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 1806, 'exitReason': 'success', 'exitCode': 0, 'requestId': '27297942-2b5e-44bf-991f-d82b457b30ea', 'installationId': 'cd7907cc-fb59-4f6e-b388-1df20ac49294', 'sessionId': 'daf01e66-bb47-44e1-bd61-e2536557f941', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.40.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

(Yes I am able to deploy this sample app.)

Couple days I was having some env problems then I completely removed pyenv which was messing with sam.

Cheers,
F

**Comment by ruivapps** [comment]
I guess the homebrew will install the python with pip. 
In my case, the python I have in on OS that does not have pip. Pip is only available on venv environment.

**Comment by jfuss** [comment]
This is related to: https://github.com/awslabs/aws-lambda-builders/issues/135

@ruivapps In order to build a Python function, Pip needs to be installed in the Python version that matches the runtime. If Pip is not installed, we cannot build. The solution here is to install Pip into the python version, so that `sam build` can find the correct pip to build with.

**Comment by ruivapps** [comment]
the pip is available under venv environment, but not the OS python.  this is how I can install aws-sam-cli via pip.

**Comment by ruivapps** [comment]
I understand the solution. That is exactly what I did, install pip on OS python. I am just thinking if it's possible to have "sam build" realize venv python instead of OS python.

**Comment by jfuss** [comment]
@ruivapps From what I recall, we look at the path to find the python version that matches the runtime and then use that. This is done to ensure we are building with the correct version that matches the runtime. So for some reason, we are getting the system python version first.

Why do you want `sam build` to use that venv? We build into a different target, so we are isolating builds for you already. A venv is more important for you are a user, not so much `sam build`. There could be some cases I am overlooking though.

**Comment by ruivapps** [comment]
I don't have to use venv in sam build. I just encountered the error and trying to report it. I'm fine with sam build using system python instead venv python.
Maybe this behavior can document in the README.md to reduce confusion. (I see few people encounter the same issue and not everyone can figure out what went wrong)

**Comment by jfuss** [comment]
@ruivapps We are currently tracking an item to improve this error message for sure. So that is defiantly part of this.

I am also just trying to understand your expectations and reasoning. Maybe we have something off that would be more intuitive and clearer (outside of presenting a better output to customers).

**Comment by ruivapps** [comment]
I think something other than "ValueError: invalid literal for int() with base 10: '' would be great. 
something can help the entry-level user to figure out the issue. for example, raise with the stderr message instead have python raise the error when splitting the string.

**Comment by sriram-mv** [comment]
Fix out coming out in aws-lambda-builders: https://github.com/awslabs/aws-lambda-builders/pull/146

**Comment by sriram-mv** [comment]
Fix is out with the latest version of SAM CLI

**Comment by KomaGR** [comment]
@jfuss 
> Why do you want `sam build` to use that venv?
I needed to do this on a system where the target runtime was not available on the system-wide level (because the system-level was at the next python version). Is this still not possible?

For example, right now I need to use `python 3.8` for the Lambda runtime but my system uses `python 3.9` and downgrading my system python would break a lot of things.

**Comment by jfuss** [comment]
@KomaGR Solution is to use `--use-container` or install python3.8 and make it available on the `PATH`. You don't need to downgrade at all, as you can have multiple python installations on a single system.

**Comment by mrpatrick** [comment]
This is still an issue if you use the beta [sam sync command](https://aws.amazon.com/blogs/compute/accelerating-serverless-development-with-aws-sam-accelerate/):

1. Doesn't have an option to flag `--use-container` for the build portion
2. Doesn't recognize venv (as stated in this original ticket)

Appears there is no workaround.  Hopefully it's resolved before it's out of beta because it could be a really useful command.
