### ISSUE TITLE
sam build --use-container fails to build on macOS

### ISSUE THREAD

**Issue by StuMason** [awslabs/aws-sam-cli#1755]
### Description

Running `sam build --use-container` fails to complete. 

### Observed result

```
aws_lambda_builders.exceptions.WorkflowUnknownError: PythonPipBuilder:CopySource - [Errno 2] No such file or directory: '/tmp/samcli/source/env/bin/python3'
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:CopySource - [Errno 2] No such file or directory: '/tmp/samcli/source/env/bin/python3'"}}
```

### Steps to reproduce

`sam build --use-container --debug` 

produces following error:

```
sam build --use-container --debug -m ./requirements.txt
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
Collected default values for parameters: { 'Application': 'Search', 'BuildType': 'LINUX_CONTAINER', 'BuildComputeType': 'BUILD_GENERAL1_SMALL', 'BuildImage': '364215618558.dkr.ecr.eu-west-1.amazonaws.com/serverless-builder:latest', 'Example': 'EXAMPLE_001', 'UseAPIGateway': 'no', 'UseCustomDomain': 'no'}
Unable to resolve property AwsSecret: {'Fn::GetAtt': ['UserAccessKey', 'SecretAccessKey']}. Leaving as is.
31 resources found in the template
Found Serverless function with name='KeepAwake' and CodeUri='.'
Found Serverless function with name='WebScraperTest' and CodeUri='.'
Building resource 'KeepAwake'

Fetching lambci/lambda:build-python3.7 Docker container image..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Mounting /Volumes/Workspace/search as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch
Full dependency closure: {jmespath==0.9.4(wheel), packaging==20.1(wheel), lxml==4.3.3(wheel), py==1.8.1(wheel), requests==2.22.0(wheel), elasticsearch==7.0.0(wheel), html-sanitizer==1.7.2(wheel), future==0.18.2(sdist), xmltodict==0.12.0(wheel), requests-oauthlib==1.3.0(wheel), attrs==19.3.0(wheel), python-dateutil==2.8.1(wheel), python-dotenv==0.10.5(wheel), aws-xray-sdk==2.4.3(wheel), soupsieve==1.9.5(wheel), selenium==2.53.0(sdist), chromedriver-binary==2.37.0(sdist), jsonpickle==1.2(wheel), oauthlib==3.1.0(wheel), botocore==1.14.9(wheel), pyparsing==2.4.6(wheel), importlib-metadata==1.4.0(wheel), s3transfer==0.3.2(wheel), pyyaml==5.3(sdist), wcwidth==0.1.8(wheel), zipp==2.1.0(wheel), pytest==5.3.4(wheel), boto3==1.11.9(wheel), idna==2.8(wheel), urllib3==1.25.6(wheel), beautifulsoup4==4.8.1(wheel), six==1.14.0(wheel), more-itertools==8.1.0(wheel), chardet==3.0.4(wheel), wrapt==1.11.2(sdist), pluggy==0.13.1(wheel), requests-aws4auth==0.9(wheel), docutils==0.15.2(wheel), certifi==2019.9.11(wheel)}
initial compatible: {jmespath==0.9.4(wheel), packaging==20.1(wheel), lxml==4.3.3(wheel), py==1.8.1(wheel), requests==2.22.0(wheel), elasticsearch==7.0.0(wheel), html-sanitizer==1.7.2(wheel), xmltodict==0.12.0(wheel), requests-oauthlib==1.3.0(wheel), attrs==19.3.0(wheel), python-dateutil==2.8.1(wheel), python-dotenv==0.10.5(wheel), aws-xray-sdk==2.4.3(wheel), soupsieve==1.9.5(wheel), jsonpickle==1.2(wheel), oauthlib==3.1.0(wheel), botocore==1.14.9(wheel), pyparsing==2.4.6(wheel), certifi==2019.9.11(wheel), importlib-metadata==1.4.0(wheel), s3transfer==0.3.2(wheel), wcwidth==0.1.8(wheel), zipp==2.1.0(wheel), pytest==5.3.4(wheel), boto3==1.11.9(wheel), urllib3==1.25.6(wheel), beautifulsoup4==4.8.1(wheel), six==1.14.0(wheel), more-itertools==8.1.0(wheel), chardet==3.0.4(wheel), pluggy==0.13.1(wheel), requests-aws4auth==0.9(wheel), idna==2.8(wheel), docutils==0.15.2(wheel)}
initial incompatible: {selenium==2.53.0(sdist), chromedriver-binary==2.37.0(sdist), future==0.18.2(sdist), wrapt==1.11.2(sdist), pyyaml==5.3(sdist)}
Downloading missing wheels: {selenium==2.53.0(sdist), chromedriver-binary==2.37.0(sdist), future==0.18.2(sdist), wrapt==1.11.2(sdist), pyyaml==5.3(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch selenium==2.53.0
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch chromedriver-binary==2.37.0
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch future==0.18.2
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch wrapt==1.11.2
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/samcli/scratch pyyaml==5.3
compatible wheels after second download pass: {jmespath==0.9.4(wheel), packaging==20.1(wheel), lxml==4.3.3(wheel), py==1.8.1(wheel), requests==2.22.0(wheel), elasticsearch==7.0.0(wheel), html-sanitizer==1.7.2(wheel), xmltodict==0.12.0(wheel), requests-oauthlib==1.3.0(wheel), attrs==19.3.0(wheel), python-dateutil==2.8.1(wheel), python-dotenv==0.10.5(wheel), aws-xray-sdk==2.4.3(wheel), soupsieve==1.9.5(wheel), jsonpickle==1.2(wheel), oauthlib==3.1.0(wheel), botocore==1.14.9(wheel), pyparsing==2.4.6(wheel), importlib-metadata==1.4.0(wheel), s3transfer==0.3.2(wheel), wcwidth==0.1.8(wheel), zipp==2.1.0(wheel), pytest==5.3.4(wheel), boto3==1.11.9(wheel), idna==2.8(wheel), urllib3==1.25.6(wheel), beautifulsoup4==4.8.1(wheel), six==1.14.0(wheel), more-itertools==8.1.0(wheel), chardet==3.0.4(wheel), pluggy==0.13.1(wheel), requests-aws4auth==0.9(wheel), docutils==0.15.2(wheel), certifi==2019.9.11(wheel)}
Build missing wheels from sdists (C compiling True): {wrapt==1.11.2(sdist), pyyaml==5.3(sdist), selenium==2.53.0(sdist), chromedriver-binary==2.37.0(sdist), future==0.18.2(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/wrapt-1.11.2.tar.gz
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/PyYAML-5.3.tar.gz
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/selenium-2.53.0.tar.gz
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/chromedriver-binary-2.37.0.tar.gz
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/future-0.18.2.tar.gz
compatible after building wheels (no C compiling): {jmespath==0.9.4(wheel), packaging==20.1(wheel), lxml==4.3.3(wheel), py==1.8.1(wheel), requests==2.22.0(wheel), elasticsearch==7.0.0(wheel), html-sanitizer==1.7.2(wheel), future==0.18.2(wheel), xmltodict==0.12.0(wheel), requests-oauthlib==1.3.0(wheel), attrs==19.3.0(wheel), python-dateutil==2.8.1(wheel), python-dotenv==0.10.5(wheel), aws-xray-sdk==2.4.3(wheel), soupsieve==1.9.5(wheel), selenium==2.53.0(wheel), chromedriver-binary==2.37.0(wheel), jsonpickle==1.2(wheel), oauthlib==3.1.0(wheel), botocore==1.14.9(wheel), pyparsing==2.4.6(wheel), importlib-metadata==1.4.0(wheel), s3transfer==0.3.2(wheel), pyyaml==5.3(wheel), wcwidth==0.1.8(wheel), zipp==2.1.0(wheel), pytest==5.3.4(wheel), boto3==1.11.9(wheel), idna==2.8(wheel), urllib3==1.25.6(wheel), beautifulsoup4==4.8.1(wheel), six==1.14.0(wheel), more-itertools==8.1.0(wheel), chardet==3.0.4(wheel), wrapt==1.11.2(wheel), pluggy==0.13.1(wheel), requests-aws4auth==0.9(wheel), docutils==0.15.2(wheel), certifi==2019.9.11(wheel)}
Build missing wheels from sdists (C compiling False): set()
compatible after building wheels (C compiling): {jmespath==0.9.4(wheel), packaging==20.1(wheel), lxml==4.3.3(wheel), py==1.8.1(wheel), requests==2.22.0(wheel), elasticsearch==7.0.0(wheel), html-sanitizer==1.7.2(wheel), future==0.18.2(wheel), xmltodict==0.12.0(wheel), requests-oauthlib==1.3.0(wheel), attrs==19.3.0(wheel), python-dateutil==2.8.1(wheel), python-dotenv==0.10.5(wheel), aws-xray-sdk==2.4.3(wheel), soupsieve==1.9.5(wheel), selenium==2.53.0(wheel), chromedriver-binary==2.37.0(wheel), jsonpickle==1.2(wheel), oauthlib==3.1.0(wheel), botocore==1.14.9(wheel), pyparsing==2.4.6(wheel), importlib-metadata==1.4.0(wheel), s3transfer==0.3.2(wheel), pyyaml==5.3(wheel), wcwidth==0.1.8(wheel), zipp==2.1.0(wheel), pytest==5.3.4(wheel), boto3==1.11.9(wheel), idna==2.8(wheel), urllib3==1.25.6(wheel), beautifulsoup4==4.8.1(wheel), six==1.14.0(wheel), more-itertools==8.1.0(wheel), chardet==3.0.4(wheel), wrapt==1.11.2(wheel), pluggy==0.13.1(wheel), requests-aws4auth==0.9(wheel), docutils==0.15.2(wheel), certifi==2019.9.11(wheel)}
Final compatible: {jmespath==0.9.4(wheel), packaging==20.1(wheel), lxml==4.3.3(wheel), py==1.8.1(wheel), requests==2.22.0(wheel), elasticsearch==7.0.0(wheel), html-sanitizer==1.7.2(wheel), future==0.18.2(wheel), xmltodict==0.12.0(wheel), requests-oauthlib==1.3.0(wheel), attrs==19.3.0(wheel), python-dateutil==2.8.1(wheel), python-dotenv==0.10.5(wheel), aws-xray-sdk==2.4.3(wheel), soupsieve==1.9.5(wheel), selenium==2.53.0(wheel), chromedriver-binary==2.37.0(wheel), jsonpickle==1.2(wheel), oauthlib==3.1.0(wheel), botocore==1.14.9(wheel), pyparsing==2.4.6(wheel), importlib-metadata==1.4.0(wheel), s3transfer==0.3.2(wheel), pyyaml==5.3(wheel), wcwidth==0.1.8(wheel), zipp==2.1.0(wheel), pytest==5.3.4(wheel), boto3==1.11.9(wheel), idna==2.8(wheel), urllib3==1.25.6(wheel), beautifulsoup4==4.8.1(wheel), six==1.14.0(wheel), more-itertools==8.1.0(wheel), chardet==3.0.4(wheel), wrapt==1.11.2(wheel), pluggy==0.13.1(wheel), requests-aws4auth==0.9(wheel), docutils==0.15.2(wheel), certifi==2019.9.11(wheel)}
Final incompatible: set()
Final missing wheels: set()
PythonPipBuilder:ResolveDependencies succeeded
Running PythonPipBuilder:CopySource
PythonPipBuilder:CopySource raised unhandled exception
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/actions.py", line 101, in execute
    copytree(self.source_dir, self.dest_dir, ignore=shutil.ignore_patterns(*self.excludes))
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/utils.py", line 58, in copytree
    copytree(new_source, new_destination, ignore=ignore)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/utils.py", line 58, in copytree
    copytree(new_source, new_destination, ignore=ignore)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/utils.py", line 60, in copytree
    shutil.copy2(new_source, new_destination)
  File "/var/lang/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/var/lang/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/samcli/source/env/bin/python3'
Builder workflow failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 248, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/actions.py", line 101, in execute
    copytree(self.source_dir, self.dest_dir, ignore=shutil.ignore_patterns(*self.excludes))
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/utils.py", line 58, in copytree
    copytree(new_source, new_destination, ignore=ignore)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/utils.py", line 58, in copytree
    copytree(new_source, new_destination, ignore=ignore)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/utils.py", line 60, in copytree
    shutil.copy2(new_source, new_destination)
  File "/var/lang/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/var/lang/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/samcli/source/env/bin/python3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/__main__.py", line 137, in main
    mode=params.get('mode', None))
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/builder.py", line 115, in build
    return workflow.run()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 65, in wrapper
    func(self, *args, **kwargs)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 263, in run
    reason=str(ex))
aws_lambda_builders.exceptions.WorkflowUnknownError: PythonPipBuilder:CopySource - [Errno 2] No such file or directory: '/tmp/samcli/source/env/bin/python3'
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:CopySource - [Errno 2] No such file or directory: '/tmp/samcli/source/env/bin/python3'"}}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 156534, 'exitReason': 'BuildError', 'exitCode': 1, 'requestId': 'bb74fe52-b3fb-4f56-b2d5-a248814c237c', 'installationId': '77944511-ef0b-4d61-a3b2-7127635504fa', 'sessionId': '2d80fcf6-6639-42af-9382-e67d7d7f772c', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.40.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:CopySource - [Errno 2] No such file or directory: '/tmp/samcli/source/env/bin/python3'
```

### Expected result

Expect the build to complete successfully. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

os: `macOS Catalina 10.15.2`
aws-cli: `aws-cli/1.16.141 Python/3.7.5 Darwin/19.2.0 botocore/1.12.166`
sam: `SAM CLI, version 0.40.0`
python: `Python 3.7.5`

**Comment by StuMason** [comment]
rubber duck.
