### ISSUE TITLE
sam package is failing with no clear indication as to why

### ISSUE THREAD

**Issue by ajhool** [awslabs/aws-sam-cli#1763]
### Description

An error is thrown when running `sam package --profile MY_PROFILE --template-file ./template.yaml --output-template-file ./packaged.yaml --s3-bucket MY_BUCKET_NAME`

### Steps to reproduce

Install aws-sam-cli on ubuntu using the homebrew installation provided by aws-sam-cli
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html

### Observed result

```
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam package', 'duration': 3116, 'exitReason': 'AttributeError', 'exitCode': 255, 'requestId': '998ae279-9397-4d13-b2b4-fa768fbb0390', 'installationId': 'bdce0c79-b82d-4c46-b21e-be8d952d3944', 'sessionId': '510c8df3-4a8d-4d3e-912a-c261d82f9e19', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.40.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.40.0', 'console_scripts', 'sam')()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/commands/package/command.py", line 100, in cli
    ctx.profile,
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/commands/package/command.py", line 130, in do_cli
    package_context.run()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/commands/package/package_context.py", line 92, in run
    exported_str = self._export(self.template_file, self.use_json)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/commands/package/package_context.py", line 107, in _export
    exported_template = template.export()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.40.0/libexec/lib/python3.7/site-packages/samcli/lib/package/artifact_exporter.py", line 622, in export
    resource_type = resource.get("Type", None)
AttributeError: 'NoneType' object has no attribute 'get'
```

### Expected result

A packaged file.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu Budgie 
2. `sam --version`:  SAM CLI, version 0.40.0

```
~/.aws/config
[profile MY_PROFILE]
region = us-east-1
output = json
```

```
~/.aws/credentials
[MY_PROFILE]
aws_access_key_id=AKIA*REDACTED*AD
aws_secret_access_key=b*REDACTED*q
```

`Add --debug flag to command you are running`

**Comment by ajhool** [comment]
There was an issue in the SAM template causing the failure. Error message did not provide any indication that the template was invalid.

**Comment by bdew70** [comment]
> There was an issue in the SAM template causing the failure. Error message did not provide any indication that the template was invalid.

This was my issue also. The yaml was invalid but sam did not communicate this. Is adding a `--debug` flag really a "fix"? I think the cli should be explicit about what is going.
