### ISSUE TITLE
Failed to install AWS-SAM-CLI on Ubuntu 18.04.4

### ISSUE THREAD

**Issue by joernkleinbub** [awslabs/aws-sam-cli#1854]
### Description
I am failing to install AWS-SAM-CLI on my brand new Ubuntu 18.04-Laptop.
I get an error when I call "sam --version"

### Steps to reproduce
I followed https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html
I installed Python3.7 from source because libpython3.7m.so.1.0 was needed and was not installed by the package manager. 

### Observed result
The error is:
```
joern@joern-acer:~$ sam --version
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aws-sam-cli==0.43.0' distribution was not found and is required by the application
```

### Expected result
Here is a result from my old laptop with aws-sam-cli
```
joernkleinbub@joerns:~$ sam --version
SAM CLI, version 0.31.0
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04.4
2. `sam --version`: should be 0.43.0

**Comment by awood45** [comment]
I believe, if you've done this in the last ~12 hours, you attempted an install from source while we were in the process of a release where we were changing some of the build details, and this unstable state was possible during this release. I'm working on completing the release, after which this problem should go away. Will report back after, so we can see if the problem persists.

**Comment by awood45** [comment]
Please try again now and let me know if you continue to have issues. Sorry for the inconvenience either way.

**Comment by joernkleinbub** [comment]
Got it. It is running again. Thanks for the quick help.

**Comment by kmeelu** [comment]
Hi, is there a release ongoing? Our CircleCI pipeline (which uses [`aws-serverless/install`](https://circleci.com/orbs/registry/orb/circleci/aws-serverless#commands-install)), is failing on that step:

```
See: https://docs.brew.sh/Homebrew-and-Python
 
Traceback (most recent call last):
 
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 6, in <module>
 
    from pkg_resources import load_entry_point
 
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
 
    @_call_aside
 
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
 
    f(*args, **kwargs)
 
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
 
    working_set = WorkingSet._build_master()
 
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
 
    ws.require(__requires__)
 
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
 
    needed = self.resolve(parse_requirements(requirements))
 
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
 
    raise DistributionNotFound(req, requirers)
 
pkg_resources.DistributionNotFound: The 'aws-sam-cli==0.53.0' distribution was not found and is required by the application
 
 
Exited with code exit status 1 
CircleCI received exit code 1 
```

Looking at the releases, it seems like there was a [pre-release candidate](https://github.com/awslabs/aws-sam-cli/releases/tag/v1.0.0rc1) but no update since. Is that correct?

**Comment by jfuss** [comment]
@kmeelu We had an issue with our 0.53.0 bottles that were not installing correctly after Homebrew updated python from 3.7 to 3.8. We were addressing that earlier today. Everything should be fixed now. If you are still running into problem, please cut a new issue.
