### ISSUE TITLE
SAM cli throws error for git layer

### ISSUE THREAD

**Issue by kunjalr** [awslabs/aws-sam-cli#1907]
After adding git layer in template sam build throws InvalidResourceException error

### Steps to reproduce

- install aws-sam-cli to python directory in site-packages, it was done pycharm can use for aws toolkit
- python version: 3.8.2
-install pip 19.2.3 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
- Run sam build

Template: 

    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: /Users/xyz/test
      Handler: gitclone.lambda_handler
      layers:
        - 'arn:aws:lambda:us-west-2:553035198032:layer:git-lambda2:4'
      Runtime: python3.8
      Events:
        InvokeScan:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /scan
            Method: any

### Observed result

Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 243, 'exitReason': 'InvalidSamDocumentException', 'exitCode': 255, 'requestId': '34caf461-178e-4060-bd07-ff22dc62ba23', 'installationId': '07e1f297-5c77-4490-a00b-486043a9420a', 'sessionId': 'aae9a6d2-45eb-4d7d-811e-235d0cfb571e', 'executionEnvironment': 'CLI', 'pyversion': '3.8.2', 'samcliVersion': '0.46.0'}}]}
Telemetry response: 200
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 71, in run_plugins
    parser.parse(template_copy, all_plugins)  # parse() will run all configured plugins
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 140, in parse
    raise InvalidDocumentException(document_errors)
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('ScanRequestFunction', 'property layers not defined for resource of type AWS::Serverless::Function')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/sam", line 10, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/commands/build/command.py", line 117, in cli
    do_cli(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/commands/build/command.py", line 167, in do_cli
    with BuildContext(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/commands/build/build_context.py", line 61, in __enter__
    self._function_provider = SamFunctionProvider(self._template_dict, self._parameter_overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 44, in __init__
    self.template_dict = SamBaseProvider.get_template(template_dict, parameter_overrides)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/lib/providers/sam_base_provider.py", line 41, in get_template
    template_dict = SamTranslatorWrapper(template_dict).run_plugins()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 73, in run_plugins
    raise InvalidSamDocumentException(
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('ScanRequestFunction', 'property layers not defined for resource of type AWS::Serverless::Function')] ('ScanRequestFunction', 'property layers not defined for resource of type AWS::Serverless::Function')

### Expected result

The build should have been successful with git installed in container during sam build.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 10.14.6
2. `sam --version`: 0.46.0

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@kunjalr You have an error in your template. This is why it is throwing the `InvalidSamDocumentException`. `layers` should be `Layers`

**Comment by sriram-mv** [comment]
Sounds like @jfuss has hit the solution, closing this issue for now, can reopen if it does not solve it.
