### ISSUE TITLE
sam deploy: KeyError: 'Outputs'

### ISSUE THREAD

**Issue by pyk** [awslabs/aws-sam-cli#1939]
### Description

Cannot deploy the `HelloWord` example due to error in `sam deploy` command.

### Steps to reproduce
AWS access key & secret are already configured with `AdministratorAccess`.

1. Init new project with `sam init`
2. Choose `AWS Quick Start Templates`
3. Choose `python3.8` as runtime
4. Project name: `reproduce-error`
5. Choose `Hello World Example`
6. `cd .\reproduce-error\`
7. Build the app: `sam build --use-container`
7. Then deploy the the project `sam deploy --guided --debug`

### Observed result

Please provide command output with `--debug` flag set.

```
PS C:\Users\bayu\pyk\reproduce-error> sam deploy --guided --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

Configuring SAM deploy
======================

        Looking for samconfig.toml :  Not found

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [sam-app]: reproduce-error
        AWS Region [us-east-1]: ap-southeast-1
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [y/N]: Y
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]: Y
        Save arguments to samconfig.toml [Y/n]: Y

        Looking for resources needed for deployment: Found!
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam deploy', 'duration': 33920, 'exitReason': 'KeyError', 'exitCode': 255, 'requestId': '759b0b08-3a42-4a2b-917e-1ac4523e3205', 'installationId': '0401383f-7347-4051-8175-12422b39832c', 'sessionId': '6cd30d66-71ea-4721-8e39-1bf69b0538cb', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.47.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\deploy\command.py", line 180, in cli
    ctx.profile,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\deploy\command.py", line 223, in do_cli
    guided_context.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\deploy\guided_context.py", line 150, in run
    self.guided_prompts(_parameter_override_keys)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\deploy\guided_context.py", line 103, in guided_prompts
    s3_bucket = manage_stack(profile=self.profile, region=region)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\bootstrap\bootstrap.py", line 36, in manage_stack
    return _create_or_get_stack(cloudformation_client)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\bootstrap\bootstrap.py", line 70, in _create_or_get_stack
    outputs = stack["Outputs"]
KeyError: 'Outputs'
```

### Expected result

The app should be deployed.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 0.47.0

`Add --debug flag to command you are running`

**Comment by pyk** [comment]
It turns out that I need to attach `AmazonS3FullAccess` policy to the IAM role. 

I thought `AdministratorAccess` policy cover this access 😁

I do the following to fix the error above:
1. Delete the `aws-sam-cli-managed-default` stack in Cloudformation manually
2. Attach  `AmazonS3FullAccess` policy to the IAM role. 
3. Then re-run the `sam deploy`
