### ISSUE TITLE
Validation regression for ApplicationId in AWS::Serverless::Application resources

### ISSUE THREAD

**Issue by cnnrmtthws** [awslabs/aws-sam-cli#1956]
# Summary
Using SAM CLI 0.48.0, if a SAM template includes AWS::Serverless::Application resources and you are using !FindInMap and !Ref in the ApplicaitonId field, attempting to deploy fails with the error (full log below):
```
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('helloworld', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")] ('helloworld', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")
```
If I revert back to a previous version (in this case 0.46.0) the below steps succeed.

# Steps to reproduce
1. Extract the example template [example.zip](https://github.com/awslabs/aws-sam-cli/files/4559681/example.zip) (template also inline at the bottom of this post)
2. Using SAM CLI 0.48.0:
```
sam deploy -t example.yaml --stack-name testbug --profile cdv --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
```
# Expected result:
Successful deployment

# Actual result:
```
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics

        Deploying with following values
        ===============================
        Stack name                 : testbug
        Region                     : None
        Confirm changeset          : False
        Deployment s3 bucket       : None
        Capabilities               : ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
        Parameter overrides        : {}

Initiating deployment
=====================
Property Location of helloworld resource is not a URL
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam deploy', 'duration': 517, 'exitReason': 'InvalidSamDocumentException', 'exitCode': 255, 'requestId': 'e9cd6e75-4c53-49af-9866-99237d54a9ac', 'installationId': '1218f337-22cf-4127-980f-c061c99f17b5', 'sessionId': 'a74f3059-4ddb-4cc9-bf57-213ebfdc421c', 'executionEnvironment': 'CLI', 'pyversion': '3.7.7', 'samcliVersion': '0.48.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/lib/samlib/wrapper.py", line 71, in run_plugins
    parser.parse(template_copy, all_plugins)  # parse() will run all configured plugins
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/lib/samlib/wrapper.py", line 140, in parse
    raise InvalidDocumentException(document_errors)
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('helloworld', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.48.0', 'console_scripts', 'sam')()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/commands/deploy/command.py", line 180, in cli
    ctx.profile,
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/commands/deploy/command.py", line 271, in do_cli
    deploy_context.run()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/commands/deploy/deploy_context.py", line 133, in run
    self.confirm_changeset,
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/commands/deploy/deploy_context.py", line 152, in deploy
    auth_required_per_resource = auth_per_resource(parameters, get_template_data(self.template_file))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/commands/deploy/auth_utils.py", line 34, in auth_per_resource
    template_dict=template_dict, parameter_overrides=parameter_overrides, ignore_code_extraction_warnings=True
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/lib/providers/sam_function_provider.py", line 46, in __init__
    self.template_dict = SamBaseProvider.get_template(template_dict, parameter_overrides)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/lib/providers/sam_base_provider.py", line 41, in get_template
    template_dict = SamTranslatorWrapper(template_dict).run_plugins()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/lib/samlib/wrapper.py", line 74, in run_plugins
    functools.reduce(lambda message, error: message + " " + str(error), e.causes, str(e))
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('helloworld', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")] ('helloworld', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")
```

# Additional environment details
1. Windows via bash terminal using WSL
2. ```sam --version```: ```SAM CLI, version 0.48.0```

# Template
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Minimal example to reproduce FindInMap issue with SAM CLI 0.48.0

Mappings:
  MappingExample:
    eu-west-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    eu-west-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    eu-west-3:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    eu-central-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    eu-north-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    us-east-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    us-east-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    us-west-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    us-west-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    ap-east-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    ap-south-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    ap-northeast-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    ap-southeast-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    ap-southeast-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    ap-northeast-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    ca-central-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    me-south-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
    sa-east-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world

Resources:

  helloworld:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !FindInMap [MappingExample, !Ref AWS::Region, ApplicationId]
        SemanticVersion: 1.0.4
      Parameters: 
        IdentityNameParameter: TestName
```

**Comment by cnnrmtthws** [comment]
In case anyone else is having this issue and needs to revert to an old version. These were the steps I followed:

1. Navigate to the directory where your homebrew formulas are stored. For me on WSL this was:
```
cd /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/aws/homebrew-tap
```
2. Checkout an old version of the aws homebrew formula. I checked out a version that support 0.46.0:
```
git checkout 16a813e54d6b5d5eb00e0af371789f7a7ab51031
```
3. Unlink the current install of aws sam cli:
```
brew unlink aws-sam-cli
```
4. Install 0.46.0 of the sam cli. HOMEBREW_NO_AUTO_UPDATE=1 is needed otherwise it will auto update back to 0.48.0:
```
HOMEBREW_NO_AUTO_UPDATE=1 brew install aws-sam-cli
```
5. Run sam --version to verify 0.46.0 installed

I imagine there is probably a much easier way of doing this but I'm not familiar enough with homebrew :)

**Comment by sriram-mv** [comment]
Should be fixed in develop. https://github.com/awslabs/aws-sam-cli/pull/1961

**Comment by jfuss** [comment]
Closing as this was released in https://github.com/awslabs/aws-sam-cli/releases/tag/v0.49.0

**Comment by snilparuk** [comment]
I run into the same error with `sam publish` as well. Essentially the same setup here using `│SAM CLI, version 0.52.0` 

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API Gateway to maps requrest to lambda

Mappings: 
  ApplicationRegionMap: 
    us-east-1: 
      ApplicationId: 'arn:aws:serverlessrepo:us-east-1:<MASKED>:applications/app'
    us-west-2:
      ApplicationId: 'arn:aws:serverlessrepo:us-west-2:<MASKED>:applications/app'

Resources:
  Application:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !FindInMap [ApplicationRegionMap, !Ref 'AWS::Region', ApplicationId]
        SemanticVersion: 0.0.1
```

**Comment by prabaharang** [comment]
@jfuss This issue is occurring in sam-cli version [0.52.0](https://github.com/awslabs/aws-sam-cli/tree/v0.52.0)/[0.53.0](https://github.com/awslabs/aws-sam-cli/tree/v0.53.0). I guess this issue need to be reopened.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >

Parameters:
  ApplicationId:
    Type: String
  SemanticVersion:
    Type: String

Resources:
  MyApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !Ref ApplicationId
        SemanticVersion: !Ref SemanticVersion
```
The issue happens for both `ApplicationId` and `SemanticVersion`

```
Error: [InvalidResourceException('MyApplication', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")] ('MyApplication', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")
    
Error: [InvalidResourceException('MyApplication', "Property 'SemanticVersion' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")] ('MyApplication', "Property 'SemanticVersion' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")
```

`$ sam --version
SAM CLI, version 0.53.0`

**Comment by dihmuzikien** [comment]
ran into the same error with sam publish as well. Essentially the same setup here using SAM CLI, version 0.53.0

Is that just an expected behavior for publish?

```
Mappings: 
  ApplicationRegionMap: 
    us-east-1: 
      ApplicationId: 'arn:aws:serverlessrepo:us-east-1:12345789:applications/app'
    us-west-2:
      ApplicationId: 'arn:aws:serverlessrepo:us-west-2:12345789:applications/app'

Resources:
  Application:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !FindInMap [ApplicationRegionMap, !Ref 'AWS::Region', ApplicationId]
        SemanticVersion: 0.0.1
```

```
SAM CLI, version 0.53.0
```

**Comment by erickisos** [comment]
Same error with 1.0.0
In the sam build stage
```
sam build --parameter-overrides ApplicationArn=arn:aws:serverlessrepo:us-east-1:123456789012:applications/App
```
This is the traceback

```
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 76, in run_plugins
    parser.parse(template_copy, all_plugins)  # parse() will run all configured plugins
  File "~/.local/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 145, in parse
    raise InvalidDocumentException(document_errors)
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('NestedApplication', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "~/.local/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/samcli/commands/build/command.py", line 118, in cli
    do_cli(
  File "~/.local/lib/python3.8/site-packages/samcli/commands/build/command.py", line 168, in do_cli
    with BuildContext(
  File "~/.local/lib/python3.8/site-packages/samcli/commands/build/build_context.py", line 62, in __enter__
    self._function_provider = SamFunctionProvider(self._template_dict, self._parameter_overrides)
  File "~/.local/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 40, in __init__
    self.template_dict = SamFunctionProvider.get_template(template_dict, parameter_overrides)
  File "~/.local/lib/python3.8/site-packages/samcli/lib/providers/sam_base_provider.py", line 126, in get_template
    template_dict = SamTranslatorWrapper(template_dict, parameter_values=parameters_values).run_plugins()
  File "~/.local/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 78, in run_plugins
    raise InvalidSamDocumentException(
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('NestedApplication', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")] ('NestedApplication', "Property 'ApplicationId' cannot be resolved. Only FindInMap and Ref intrinsic functions are supported.")
```

And the current version

```
SAM CLI, version 1.0.0
```

**Comment by Leooo** [comment]
@jfuss how was https://github.com/aws/aws-sam-cli/releases/tag/v0.49.0 supposed to have resolved this error? Still failing for `sam publish` on SAM CLI version 1.21.1
