### ISSUE TITLE
Debugging with custom PHP runtime

### ISSUE THREAD

**Issue by umair-khokhar** [awslabs/aws-sam-cli#1964]
I have built and compiled custom PHP runtime for my lambda functions. I am using sam cli to run the functions locally. I am using VS code for coding. When I try to debug my application I can't get it to work. See logs below

```
Mounting HelloFunction at http://127.0.0.1:3000/hello [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2020-05-04 15:47:33  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
Invoking functions/api/handler.hello (provided)
PHPLayer is a local Layer in the template
Building image...
2020-05-04 15:47:44 Exception on /hello [GET]
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_debug_settings.py", line 215, in get_debug_settings
    return entrypoint_mapping[runtime]
KeyError: 'provided'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/local/apigw/local_apigw_service.py", line 200, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/commands/local/lib/local_lambda.py", line 100, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/local/lambdafn/runtime.py", line 77, in invoke
    debug_options=debug_context,
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_container.py", line 74, in __init__
    entry, debug_env_vars = LambdaContainer._get_debug_settings(runtime, debug_options)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_container.py", line 207, in _get_debug_settings
    options=LambdaContainer._DEBUG_ENTRYPOINT_OPTIONS,
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_debug_settings.py", line 217, in get_debug_settings
    raise DebuggingNotSupported("Debugging is not currently supported for {}".format(runtime))
samcli.local.docker.lambda_debug_settings.DebuggingNotSupported: Debugging is not currently supported for provided
```

My Vscode launch.json looks like 

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/var/task": "<path to my code directory>/api"
            }
        }
    ]
}
```

### Proposal

Can we add support to debug while using custom PHP runtime?

### Additional Details
I am able to run and test functions locally using `sam local start-api`.

**Comment by awood45** [comment]
We have no current plans to add debugging support for individual custom runtimes.

We are looking at alternative approaches to solving this problem in general, but for now will be closing this issue.

**Comment by dacgray** [comment]
For anyone else who lands on this.

I got debug working in IntelliJ PHPStorm on a custom PHP runtime with these configurations - the same as you would for any dockerized PHP CLI app.

1. PHP runtime must have xdebug - run PHP -v and you should see whether it's running.
2. Set these env vars in your PHP function - in this case these are set on my SAM AWS::Serverless::Function definition.  Note server name.

![image](https://user-images.githubusercontent.com/12794616/101325491-6e36b780-389e-11eb-955d-a359dcbb9927.png)

3. Create server in IDE.  Note server name must be the same you set in 2.

![image](https://user-images.githubusercontent.com/12794616/101325642-aa6a1800-389e-11eb-8f17-1e0410343476.png)

Then run:

```
sam local start-lambda
aws lambda invoke --function-name "PhpLayerFunction" --endpoint-url "http://localhost:3001" --no-verify-ssl out.txt
```

![image](https://user-images.githubusercontent.com/12794616/101326009-3c722080-389f-11eb-9896-89f25273208a.png)
