### ISSUE TITLE
Get an error when trying the AWS tutorial for running a Lambda locally under SAM

### ISSUE THREAD

**Issue by nickweavers** [awslabs/aws-sam-cli#1971]
### Description

When following the Tutorial: Deploying a Hello World Application here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html but using the node 12.x runtime instead of the Python one used in the example, I get an error when I send a request to the endpoint URL that is given.

### Steps to reproduce

My system
Windows 10 Pro version 1909 OS Build 18363.815 with WSL 1 running Ubuntu 18.04
Docker Desktop for Windows 
Under Ubuntu, Docker version 19.03.8, build afacb8b7f0 (Docker client)
Docker Desktop setting"Expose daemon on tcp://localhost:2375 without TLS" is checked
.bashrc contains ``export DOCKER_HOST=localhost:2375``
```
$ aws --version
aws-cli/2.0.0 Python/3.7.3 Linux/4.4.0-18362-Microsoft botocore/2.0.0dev4

$ sam --version
SAM CLI, version 0.48.0

$ npm --version
6.14.4

$ node --version
v12.16.3
```
With the above setup, follow the step given in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html

### Observed result

```
nickw@nicks-xps-15-9560:/mnt/c/var/www/lambda
$ sam init

        SAM CLI now collects telemetry to better understand customer needs.

        You can OPT OUT and disable telemetry collection by setting the
        environment variable SAM_CLI_TELEMETRY=0 in your shell.
        Thanks for your help!

        Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 1

Which runtime would you like to use?
        1 - nodejs12.x
        2 - python3.8
        3 - ruby2.7
        4 - go1.x
        5 - java11
        6 - dotnetcore3.1
        7 - nodejs10.x
        8 - python3.7
        9 - python3.6
        10 - python2.7
        11 - ruby2.5
        12 - java8
        13 - dotnetcore2.1
        14 - dotnetcore2.0
        15 - dotnetcore1.0
Runtime: 1

Project name [sam-app]:

Cloning app templates from https://github.com/awslabs/aws-sam-cli-app-templates.git

-----------------------
Generating application:
-----------------------
Name: sam-app
Runtime: nodejs12.x
Dependency Manager: npm
Application Template: hello-world
Output Directory: .

Next steps can be found in the README file at ./sam-app/README.md

nickw@nicks-xps-15-9560:/mnt/c/var/www/lambda/sam-app
$ sam build
Building resource 'HelloWorldFunction'
Running NodejsNpmBuilder:NpmPack
Running NodejsNpmBuilder:CopyNpmrc
Running NodejsNpmBuilder:CopySource
Running NodejsNpmBuilder:NpmInstall
Running NodejsNpmBuilder:CleanUpNpmrc

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided

nickw@nicks-xps-15-9560:/mnt/c/var/www/lambda/sam-app
$ sam local start-api --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
local start-api command is called
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
No Parameters detected in the template
2 resources found in the template
Found '1' API Events in Serverless function with name 'HelloWorldFunction'
Detected Inline Swagger definition
Lambda function integration not found in Swagger document at path='/hello' method='get'
Found '0' APIs in resource 'ServerlessRestApi'
Removed duplicates from '0' Explicit APIs and '1' Implicit APIs to produce '1' APIs
1 APIs found in the template
Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
Localhost server is starting up. Multi-threading = True
2020-05-08 19:15:25  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
```
While the command remains in this running state, bring up another WSL bash terminal and enter

```
nickw@nicks-xps-15-9560:~
$ curl http://127.0.0.1:3000/hello
{"message":"Internal server error"}
``` 
Back in the terminal that issued the statement ``Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
You can now browse to the above endpoints to invoke your functions.``
I see the following happen:
```
Constructed String representation of Event to invoke Lambda. Event: {"httpMethod": "GET", "body": null, "resource": "/hello", "requestContext": {"resourceId": "123456", "apiId": "1234567890", "resourcePath": "/hello", "httpMethod": "GET", "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef", "accountId": "123456789012", "stage": "Prod", "identity": {"apiKey": null, "userArn": null, "cognitoAuthenticationType": null, "caller": null, "userAgent": "Custom User Agent String", "user": null, "cognitoIdentityPoolId": null, "cognitoAuthenticationProvider": null, "sourceIp": "127.0.0.1", "accountId": null}, "extendedRequestId": null, "path": "/hello"}, "queryStringParameters": null, "multiValueQueryStringParameters": null, "headers": {"Host": "127.0.0.1:3000", "User-Agent": "curl/7.58.0", "Accept": "*/*", "X-Forwarded-Proto": "http", "X-Forwarded-Port": "3000"}, "multiValueHeaders": {"Host": ["127.0.0.1:3000"], "User-Agent": ["curl/7.58.0"], "Accept": ["*/*"], "X-Forwarded-Proto": ["http"], "X-Forwarded-Port": ["3000"]}, "pathParameters": null, "stageVariables": null, "path": "/hello", "isBase64Encoded": false}
Found one Lambda function with name 'HelloWorldFunction'
Invoking app.lambdaHandler (nodejs12.x)
No environment variables found for function 'HelloWorldFunction'
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'None'
Resolving code path. Cwd=/mnt/c/var/www/lambda/sam-app/.aws-sam/build, CodeUri=HelloWorldFunction
Resolved absolute path to code is /mnt/c/var/www/lambda/sam-app/.aws-sam/build/HelloWorldFunction
Code /mnt/c/var/www/lambda/sam-app/.aws-sam/build/HelloWorldFunction is not a zip/jar file
Skipping building an image since no layers were defined

Fetching lambci/lambda:nodejs12.x Docker container image.....
Mounting /mnt/c/var/www/lambda/sam-app/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
Container was not created. Skipping deletion
2020-05-08 19:19:13 Exception on /hello [GET]
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:2375/v1.35/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/local/apigw/local_apigw_service.py", line 200, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/commands/local/lib/local_lambda.py", line 100, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/local/lambdafn/runtime.py", line 83, in invoke
    self._container_manager.run(container)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/local/docker/manager.py", line 93, in run
    container.create()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/local/docker/container.py", line 133, in create
    real_container = self.docker_client.containers.create(self._image, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: lambci/lambda:nodejs12.x")
2020-05-08 19:19:14 127.0.0.1 - - [08/May/2020 19:19:14] "GET /hello HTTP/1.1" 502 -
```

### Expected result

Describe what you expected.

I expected the equivalent output for the Node version of the example that is shown in the https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html at step 4 here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html#serverless-getting-started-hello-world-test-locally where they show the results for a Python example

```
2019-07-12 15:29:57 Invoking app.lambda_handler (python3.7)
 2019-07-12 15:29:57 Found credentials in shared credentials file: ~/.aws/credentials

 Fetching lambci/lambda:python3.7 Docker container image......
 2019-07-12 15:29:58 Mounting /<working-development-path>/sam-app/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
 START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
 END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
 REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72  Duration: 7.92 ms       Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 22 MB
 {"statusCode":200,"body":"{\"message\": \"hello world\"}"}
``` 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

Windows 10 Pro version 1909 OS Build 18363.815 with WSL 1 running Ubuntu 18.04
Docker Desktop for Windows 
Under Ubuntu, Docker version 19.03.8, build afacb8b7f0 (Docker client)
Docker Desktop setting"Expose daemon on tcp://localhost:2375 without TLS" is checked
.bashrc contains ``export DOCKER_HOST=localhost:2375``
```
$ aws --version
aws-cli/2.0.0 Python/3.7.3 Linux/4.4.0-18362-Microsoft botocore/2.0.0dev4

$ sam --version
SAM CLI, version 0.48.0

$ npm --version
6.14.4

$ node --version
v12.16.3
```

`Add --debug flag to command you are running`

**Comment by nickweavers** [comment]
Just to show my Docker setup seems to be working okay:
```
nickw@nicks-xps-15-9560:~
$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0fe89239909b: Pull complete                                                                                                                                                                         d5764f3a7b3b: Pull complete                                                                                                                                                                         f48f3724e92b: Pull complete                                                                                                                                                                         Digest: sha256:8e3114318a995a1ee497790535e7b88365222a21771ae7e53687ad76563e8e76
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (windows-amd64, nanoserver-1809)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run a Windows Server container with:
 PS C:\> docker run -it mcr.microsoft.com/windows/servercore powershell

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

nickw@nicks-xps-15-9560:~
$
```

**Comment by michaelj-smith** [comment]
@nickweavers Can you show the contents of your directory at `.aws-sam/build/`? The system is looking for a zip file there. This is probably caused by a misconfiguration in the build step.

```
Code /mnt/c/var/www/lambda/sam-app/.aws-sam/build/HelloWorldFunction is not a zip/jar file
```

**Comment by nickweavers** [comment]
@michaelj-smith, /mnt/c/var/www/lambda/sam-app/.aws-sam/build/HelloWorldFunction is a directory
```
nickw@nicks-xps-15-9560:/mnt/c/var/www/lambda/sam-app/.aws-sam/build
$ ls -la
total 4
drwxrwxrwx 1 nickw nickw  512 May  8 17:20 .
drwxrwxrwx 1 nickw nickw  512 May  8 17:12 ..
drwxrwxrwx 1 nickw nickw  512 May  8 17:20 HelloWorldFunction
-rwxrwxrwx 1 nickw nickw 1002 May  8 17:20 template.yaml
nickw@nicks-xps-15-9560:/mnt/c/var/www/lambda/sam-app/.aws-sam/build
$
```
Inside are the following:
```
nickw@nicks-xps-15-9560:/mnt/c/var/www/lambda/sam-app/.aws-sam/build/HelloWorldFunction
$ ls -la
total 4
drwxrwxrwx 1 nickw nickw  512 May  8 17:20 .
drwxrwxrwx 1 nickw nickw  512 May  8 17:20 ..
-rwxrwxrwx 1 nickw nickw 1046 Oct 26  1985 app.js
drwxrwxrwx 1 nickw nickw  512 May  8 17:20 node_modules
-rwxrwxrwx 1 nickw nickw  468 Oct 26  1985 package.json
```

**Comment by michaelj-smith** [comment]
That seems about right. The project template files are here:
https://github.com/awslabs/aws-sam-cli-app-templates/tree/master/nodejs12.x/cookiecutter-aws-sam-hello-nodejs/%7B%7Bcookiecutter.project_name%7D%7D

It could be a docker permissions issue. You need to make sure that the C: drive is "Shared" in the Docker Desktop for Windows share settings. Are you running this in WSL? If so, I've found some success following this article for WSL setup with Docker:
https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

I've also heard that the new WSL 2 (https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) works much better with Docker, so that might be something to try.

**Comment by nickweavers** [comment]
That article for WSL setup with Docker has some interesting points. I didn't know about the fact that some Docker things expect a path on /c/something rather than /mnt/c/something so I have implemented the ``sudo mount --bind /mnt/c /c``.
In the latest DockerDesktop for Windows there does not appear to be anywhere that lets you specify drives that should be shared, but in my latest run now I have the /mnt/c monted at /c I still get the following error when I send a GET request to the endpoint:
```
Localhost server is starting up. Multi-threading = True
2020-05-08 21:06:44  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
Constructed String representation of Event to invoke Lambda. Event: {"httpMethod": "GET", "body": null, "resource": "/hello", "requestContext": {"resourceId": "123456", "apiId": "1234567890", "resourcePath": "/hello", "httpMethod": "GET", "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef", "accountId": "123456789012", "stage": "Prod", "identity": {"apiKey": null, "userArn": null, "cognitoAuthenticationType": null, "caller": null, "userAgent": "Custom User Agent String", "user": null, "cognitoIdentityPoolId": null, "cognitoAuthenticationProvider": null, "sourceIp": "127.0.0.1", "accountId": null}, "extendedRequestId": null, "path": "/hello"}, "queryStringParameters": null, "multiValueQueryStringParameters": null, "headers": {"Host": "127.0.0.1:3000", "User-Agent": "curl/7.58.0", "Accept": "*/*", "X-Forwarded-Proto": "http", "X-Forwarded-Port": "3000"}, "multiValueHeaders": {"Host": ["127.0.0.1:3000"], "User-Agent": ["curl/7.58.0"], "Accept": ["*/*"], "X-Forwarded-Proto": ["http"], "X-Forwarded-Port": ["3000"]}, "pathParameters": null, "stageVariables": null, "path": "/hello", "isBase64Encoded": false}
Found one Lambda function with name 'HelloWorldFunction'
Invoking app.lambdaHandler (nodejs12.x)
No environment variables found for function 'HelloWorldFunction'
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'None'
Resolving code path. Cwd=/c/var/www/lambda/sam-app/.aws-sam/build, CodeUri=HelloWorldFunction
Resolved absolute path to code is /c/var/www/lambda/sam-app/.aws-sam/build/HelloWorldFunction
Code /c/var/www/lambda/sam-app/.aws-sam/build/HelloWorldFunction is not a zip/jar file
Skipping building an image since no layers were defined

Fetching lambci/lambda:nodejs12.x Docker container image.....
Mounting /c/var/www/lambda/sam-app/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
Container was not created. Skipping deletion
2020-05-08 21:07:23 Exception on /hello [GET]
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:2375/v1.35/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/local/apigw/local_apigw_service.py", line 200, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/commands/local/lib/local_lambda.py", line 100, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/local/lambdafn/runtime.py", line 83, in invoke
    self._container_manager.run(container)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/local/docker/manager.py", line 93, in run
    container.create()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/samcli/local/docker/container.py", line 133, in create
    real_container = self.docker_client.containers.create(self._image, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/models/containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: lambci/lambda:nodejs12.x")
2020-05-08 21:07:23 127.0.0.1 - - [08/May/2020 21:07:23] "GET /hello HTTP/1.1" 502 -
```

**Comment by nickweavers** [comment]
It says the last message in the stack trace is the most recent, so
```
File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.48.0/libexec/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: lambci/lambda:nodejs12.x")
2020-05-08 21:07:23 127.0.0.1 - - [08/May/2020 21:07:23] "GET /hello HTTP/1.1" 502
```  
I wondered if this meant Docker could not find image lambci/lambda:nodejs12.x,  so I just tried to ``run lambci/lambda:nodejs12.x``  and see if it could:
```
nickw@nicks-xps-15-9560:~
$ docker run lambci/lambda:nodejs12.x
Unable to find image 'lambci/lambda:nodejs12.x' locally
nodejs12.x: Pulling from lambci/lambda
docker: image operating system "linux" cannot be used on this platform.
See 'docker run --help'.
```

**Comment by michaelj-smith** [comment]
Ah, yes that smells like the culprit. I didn't notice that in your first stack trace.

Linux containers should be able to run in WSL... i mean, that's the whole point, right? I haven't seen this error before. I myself I'm on a mac, but I've helped many engineers get setup on Windows. I just haven't used the latest versions recently. It seems to change significantly every month.

**Comment by nickweavers** [comment]
So, there is a gotcha in the DockerDesktop for Windows. You can inadvertently have installed with it set to use Windows containers. This isn't obvious because the toggle between Window/Linux containers isn't in the Dashboard, it is only in the Docker Desktop tray icon! That seems to be a "Fail" in useability to me, but it is what it is and my bad for missing it. Once that is set to Linux containers, I see the  "File sharing" and was able to check the C drive.

I checked if this had fixed the issue, first by running a simple test to ``docker pull busybox``
```
nickw@nicks-xps-15-9560:~
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
e2334dd9fee4: Pull complete                                                                                             Digest: sha256:a8cf7ff6367c2afa2a90acd081b484cbded349a7076e7bdf37a05279f276bc12
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest
```
So far so good. Next I tried ``docker pull lambci/lambda:nodejs12.x``
```
nickw@nicks-xps-15-9560:~
$ docker pull lambci/lambda:nodejs12.x
nodejs12.x: Pulling from lambci/lambda
7d98c0afbc5a: Pull complete                                                                                             5dd75bf9b4a5: Pull complete                                                                                             55c75a38a5a6: Pull complete                                                                                             Digest: sha256:42e440e3ca9d56f3f26b148f4187291bccefa9b5728efcffafee0678a20ce01c
Status: Downloaded newer image for lambci/lambda:nodejs12.x
docker.io/lambci/lambda:nodejs12.x
```

Finally, tried the ``sam local start-api --debug``
```
nickw@nicks-xps-15-9560:/c/var/www/lambda/sam-app
$ sam local start-api --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
local start-api command is called
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
No Parameters detected in the template
2 resources found in the template
Found '1' API Events in Serverless function with name 'HelloWorldFunction'
Detected Inline Swagger definition
Lambda function integration not found in Swagger document at path='/hello' method='get'
Found '0' APIs in resource 'ServerlessRestApi'
Removed duplicates from '0' Explicit APIs and '1' Implicit APIs to produce '1' APIs
1 APIs found in the template
Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
Localhost server is starting up. Multi-threading = True
2020-05-09 10:17:36  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
```
From  another bash terminal 
```
nickw@nicks-xps-15-9560:~
$ curl http://127.0.0.1:3000/hello
{"message":"hello world"}nickw@nicks-xps-15-9560:~
$
```
So all now good. I was just the container type toggle switch in the Docker Desktop tray icon that was the issue for me.

Thanks for your help @michaelj-smith.
