### ISSUE TITLE
vscode debug fail under WSL2: pip executable not found in your python environment

### ISSUE THREAD

**Issue by CircleOnCircles** [awslabs/aws-sam-cli#1974]
### Description

Facing a debug error using vscode WSL2. 
At first, I thought It is likely that my python installation was wrong.

but, after using the same python `/usr/bin/python3.8` to
`/usr/bin/python3.8 -m pip` it is work as expect.

### Steps to reproduce

1. run Ubuntu on Windows 10 WSL2 
2. Connect Vscode to Ubuntu  WSL2
3. set up aws and aws sam cli
4. click debug locally on the hello world template `lambda_handler()` function

### Observed result
This is the log from VScode output AWS Toolkit Logs
```
Error logs for this session are permanently stored in /home/cocs/.config/Code/logs/aws_toolkit/aws_toolkit_20200511T171542.log
2020-05-11 17:15:42 [INFO]: Retrieving AWS endpoint data
2020-05-11 17:15:42 [INFO]: OS:  Linux x64 4.19.84-microsoft-standard
Visual Studio Code Version:  1.45.0
AWS Toolkit Version:  1.9.0

2020-05-11 17:15:50 [INFO]: Preparing to run app.lambda_handler locally...
2020-05-11 17:15:50 [INFO]: Building SAM Application...
2020-05-11 17:15:50 [INFO]: Running command: /home/linuxbrew/.linuxbrew/bin/sam --info
2020-05-11 17:15:50 [INFO]: Running command: /home/linuxbrew/.linuxbrew/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctk9rU9B5/output --template /tmp/aws-toolkit-vscode/vsctk9rU9B5/input/input-template.yaml --base-dir /mnt/c/Users/lifep/Devs/jobsbot/jobsbot/hello_world --manifest /tmp/aws-toolkit-vscode/vsctk9rU9B5/debug-requirements.txt
2020-05-11 17:15:52 [ERROR]: Unexpected exitcode (1), expecting (0)
2020-05-11 17:15:52 [ERROR]: Error: undefined
2020-05-11 17:15:52 [ERROR]: stderr: Building resource 'awsToolkitSamLocalResource'
,Running PythonPipBuilder:ResolveDependencies
,Error: PythonPipBuilder:ResolveDependencies - pip executable not found in your python environment at /usr/bin/python3.8
2020-05-11 17:15:52 [ERROR]: stdout: Build Failed
2020-05-11 17:15:52 [ERROR]: An error occurred trying to run SAM Application locally: Error with child process: Building resource 'awsToolkitSamLocalResource'
,Running PythonPipBuilder:ResolveDependencies
,Error: PythonPipBuilder:ResolveDependencies - pip executable not found in your python environment at /usr/bin/python3.8 Error: Error with child process: Building resource 'awsToolkitSamLocalResource'
,Running PythonPipBuilder:ResolveDependencies
,Error: PythonPipBuilder:ResolveDependencies - pip executable not found in your python environment at /usr/bin/python3.8
	at Object.t.logAndThrowIfUnexpectedExitCode (/home/cocs/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.9.0/dist/extension.js:2:475204)
	at t.SamCliBuildInvocation.<anonymous> (/home/cocs/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.9.0/dist/extension.js:2:1209531)
	at Generator.next (<anonymous>)
	at o (/home/cocs/.vscode-server/extensions/amazonwebservices.aws-toolkit-vscode-1.9.0/dist/extension.js:2:1207761)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
2020-05-11 17:20:44 [INFO]: Successfully sent a telemetry batch of 20
2020-05-11 17:20:45 [INFO]: Successfully sent a telemetry batch of 5
```

### Expected result

It is successfully debug. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 WSL2 Ubuntu
2. VS Code using WSL extension
2. `sam --version`: SAM CLI, version 0.48.0

**Comment by sriram-mv** [comment]
Just so I understand correctly, did you manage to get it to work? you mention that pip does exist for the python version.

**Comment by CircleOnCircles** [comment]
I changed back to windows (powershell) which is already working.

**Comment by CircleOnCircles** [comment]
I did mention about  *pip does exist* but the **pip did exist** `python -m pip` works well.

**Comment by amanvishnani** [comment]
Running `sudo apt install python3-pip` worked for me.
