### ISSUE TITLE
Error: PythonPipBuilder:ResolveDependencies - {boto3==1.13.17(sdist)}

### ISSUE THREAD

**Issue by AdamMarton** [awslabs/aws-sam-cli#2013]
**Describe the bug**
Using boto3 as a dependency in my SAM Application and `build` is failing due to the following error:

`Error: PythonPipBuilder:ResolveDependencies - {boto3==1.13.17(sdist)}`

Hard to tell whether the bug is in pip, AWS SAM or something else as I'm seeing [1.13.17 on pypi.org](https://pypi.org/project/boto3/) - using latest version from all.

Fixing the version to `1.13.16` in `requirements.txt` eliminates the issue.

**Steps to reproduce**
* Create a SAM application
* Execute `sam build`

**Expected behavior**
1.13.17 should work fine just like previous versions.

**Debug logs**
```
$ sam build --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
No Parameters detected in the template
4 resources found in the template
Found Serverless function with name='MyFunction' and CodeUri='hello_world'
No Parameters detected in the template
Building function 'MyFunction'
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /Users/username/Documents/project-folder/requirements.txt --dest /var/folders/2_/1skgx3gn683b9kbfc9xnj8_40000gn/T/tmpj9534uax
Full dependency closure: {urllib3==1.25.9(wheel), python-dateutil==2.8.1(wheel), jmespath==0.10.0(wheel), six==1.15.0(wheel), boto3==1.13.17(sdist), chardet==3.0.4(wheel), requests==2.23.0(wheel), s3transfer==0.3.3(wheel), botocore==1.16.17(wheel), docutils==0.15.2(wheel), certifi==2020.4.5.1(wheel), idna==2.9(wheel)}
initial compatible: {urllib3==1.25.9(wheel), python-dateutil==2.8.1(wheel), jmespath==0.10.0(wheel), six==1.15.0(wheel), chardet==3.0.4(wheel), requests==2.23.0(wheel), s3transfer==0.3.3(wheel), botocore==1.16.17(wheel), docutils==0.15.2(wheel), certifi==2020.4.5.1(wheel), idna==2.9(wheel)}
initial incompatible: {boto3==1.13.17(sdist)}
Downloading missing wheels: {boto3==1.13.17(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp38 --dest /var/folders/2_/1skgx3gn683b9kbfc9xnj8_40000gn/T/tmpj9534uax boto3==1.13.17
compatible wheels after second download pass: {urllib3==1.25.9(wheel), python-dateutil==2.8.1(wheel), jmespath==0.10.0(wheel), six==1.15.0(wheel), chardet==3.0.4(wheel), requests==2.23.0(wheel), s3transfer==0.3.3(wheel), botocore==1.16.17(wheel), docutils==0.15.2(wheel), certifi==2020.4.5.1(wheel), idna==2.9(wheel)}
Build missing wheels from sdists (C compiling True): {boto3==1.13.17(sdist)}
calling pip wheel --no-deps --wheel-dir /var/folders/2_/1skgx3gn683b9kbfc9xnj8_40000gn/T/tmpj9534uax /var/folders/2_/1skgx3gn683b9kbfc9xnj8_40000gn/T/tmpj9534uax/boto3-1.13.17.tar.gz
compatible after building wheels (no C compiling): {urllib3==1.25.9(wheel), python-dateutil==2.8.1(wheel), jmespath==0.10.0(wheel), six==1.15.0(wheel), chardet==3.0.4(wheel), requests==2.23.0(wheel), s3transfer==0.3.3(wheel), botocore==1.16.17(wheel), docutils==0.15.2(wheel), certifi==2020.4.5.1(wheel), idna==2.9(wheel)}
Build missing wheels from sdists (C compiling False): {boto3==1.13.17(sdist)}
calling pip wheel --no-deps --wheel-dir /var/folders/2_/1skgx3gn683b9kbfc9xnj8_40000gn/T/tmpj9534uax /var/folders/2_/1skgx3gn683b9kbfc9xnj8_40000gn/T/tmpj9534uax/boto3-1.13.17.tar.gz
compatible after building wheels (C compiling): {urllib3==1.25.9(wheel), python-dateutil==2.8.1(wheel), jmespath==0.10.0(wheel), six==1.15.0(wheel), chardet==3.0.4(wheel), requests==2.23.0(wheel), s3transfer==0.3.3(wheel), botocore==1.16.17(wheel), docutils==0.15.2(wheel), certifi==2020.4.5.1(wheel), idna==2.9(wheel)}
Final compatible: {urllib3==1.25.9(wheel), python-dateutil==2.8.1(wheel), jmespath==0.10.0(wheel), six==1.15.0(wheel), chardet==3.0.4(wheel), requests==2.23.0(wheel), s3transfer==0.3.3(wheel), botocore==1.16.17(wheel), docutils==0.15.2(wheel), certifi==2020.4.5.1(wheel), idna==2.9(wheel)}
Final incompatible: set()
Final missing wheels: {boto3==1.13.17(sdist)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.51.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    requirements_path=self.manifest_path,
  File "/usr/local/Cellar/aws-sam-cli/0.51.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/Cellar/aws-sam-cli/0.51.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 201, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {boto3==1.13.17(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.51.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/Cellar/aws-sam-cli/0.51.0/libexec/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {boto3==1.13.17(sdist)}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 10242, 'exitReason': 'WorkflowFailedError', 'exitCode': 1, 'requestId': 'c8dad198-6e91-45fb-a38a-094107f477c6', 'installationId': 'dcd60592-1491-4b42-ab26-a91d10922847', 'sessionId': '75c4ff44-27b2-44fc-9acf-44c187d64c00', 'executionEnvironment': 'CLI', 'pyversion': '3.7.7', 'samcliVersion': '0.51.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {boto3==1.13.17(sdist)}
```

Carried over from https://github.com/boto/boto3/issues/2460

**Comment by awood45** [comment]
I am not able to replicate this issue (builds fine for me), which may mean that this is a PIP issue of some sort. We don't have any special logic around boto3 that should make PIP behavior change.

**Comment by awood45** [comment]
There are a couple of general workarounds:
- One, it's possible your PIP is getting an outdated cache? There's an old issue about this so it likely isn't the case still if you run build again, but there's some precedent: https://github.com/pypa/pip/issues/4888
- Two, you may be able to unblock by running `sam build --use-container` as the container may pick up a newer pip package manifest.

Closing for now, if you continue to have issues feel free to reopen.

**Comment by AdamMarton** [comment]
Thanks for looking into this @awood45, checked without version constraint now and it builds fine, so yes, it was a temporary issue in PIP.

Sorry for the inconvenience.
