### ISSUE TITLE
Python Layer: exception: aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {future==0.18.2(sdist), webexteamssdk==1.3(sdist)}

### ISSUE THREAD

**Issue by jbpratt78** [awslabs/aws-sam-cli#2055]
### Description
When using the template below, and trying to build a layer for [this](https://pypi.org/project/webexteamssdk/) package, `sam build` throws an exception.

### Steps to reproduce
```
mkdir -p tmp/teamssdk && cd tmp
echo "webexteamssdk==1.3" >> teamssdk/requirements.txt
# paste template
sam build --debug
```

### Observed result

```
 sam build --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
No Parameters detected in the template
1 resources found in the template
No Parameters detected in the template
Building layer 'WebexTeamsSdk'
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /home/jbpratt/projects/x/tmp/webexteamssdk/requirements.txt --dest /tmp/tmpptswj16s
Full dependency closure: {certifi==2020.4.5.2(wheel), urllib3==1.25.9(wheel), future==0.18.2(sdist), webexteamssdk==1.3(sdist), idna==2.9(wheel), requests==2.24.0(wheel), chardet==3.0.4(wheel), pyjwt==1.7.1(wheel), requests-toolbelt==0.9.1(wheel)}
initial compatible: {certifi==2020.4.5.2(wheel), urllib3==1.25.9(wheel), idna==2.9(wheel), requests==2.24.0(wheel), chardet==3.0.4(wheel), pyjwt==1.7.1(wheel), requests-toolbelt==0.9.1(wheel)}
initial incompatible: {future==0.18.2(sdist), webexteamssdk==1.3(sdist)}
Downloading missing wheels: {future==0.18.2(sdist), webexteamssdk==1.3(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/tmpptswj16s future==0.18.2
calling pip download --only-binary=:all: --no-deps --platform manylinux1_x86_64 --implementation cp --abi cp37m --dest /tmp/tmpptswj16s webexteamssdk==1.3
compatible wheels after second download pass: {certifi==2020.4.5.2(wheel), urllib3==1.25.9(wheel), idna==2.9(wheel), requests==2.24.0(wheel), chardet==3.0.4(wheel), pyjwt==1.7.1(wheel), requests-toolbelt==0.9.1(wheel)}
Build missing wheels from sdists (C compiling True): {future==0.18.2(sdist), webexteamssdk==1.3(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/tmpptswj16s /tmp/tmpptswj16s/future-0.18.2.tar.gz
calling pip wheel --no-deps --wheel-dir /tmp/tmpptswj16s /tmp/tmpptswj16s/webexteamssdk-1.3.tar.gz
compatible after building wheels (no C compiling): {certifi==2020.4.5.2(wheel), urllib3==1.25.9(wheel), idna==2.9(wheel), requests==2.24.0(wheel), chardet==3.0.4(wheel), pyjwt==1.7.1(wheel), requests-toolbelt==0.9.1(wheel)}
Build missing wheels from sdists (C compiling False): {future==0.18.2(sdist), webexteamssdk==1.3(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/tmpptswj16s /tmp/tmpptswj16s/future-0.18.2.tar.gz
calling pip wheel --no-deps --wheel-dir /tmp/tmpptswj16s /tmp/tmpptswj16s/webexteamssdk-1.3.tar.gz
compatible after building wheels (C compiling): {certifi==2020.4.5.2(wheel), urllib3==1.25.9(wheel), idna==2.9(wheel), requests==2.24.0(wheel), chardet==3.0.4(wheel), pyjwt==1.7.1(wheel), requests-toolbelt==0.9.1(wheel)}
Final compatible: {idna==2.9(wheel), requests==2.24.0(wheel), certifi==2020.4.5.2(wheel), chardet==3.0.4(wheel), pyjwt==1.7.1(wheel), urllib3==1.25.9(wheel), requests-toolbelt==0.9.1(wheel)}
Final incompatible: set()
Final missing wheels: {future==0.18.2(sdist), webexteamssdk==1.3(sdist)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 201, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {future==0.18.2(sdist), webexteamssdk==1.3(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {future==0.18.2(sdist), webexteamssdk==1.3(sdist)}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 5458, 'exitReason': 'WorkflowFailedError', 'exitCode': 1, 'requestId': 'cc72fbc6-55dd-4757-b941-00055ab68ca7', 'installationId': '6a175b4b-2582-4383-a90a-915453a15582', 'sessionId': '1a6e87ae-4161-4d0f-8dd6-b2cfa6e14717', 'executionEnvironment': 'CLI', 'pyversion': '3.8.3', 'samcliVersion': '0.52.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {future==0.18.2(sdist), webexteamssdk==1.3(sdist)}
```

### Expected result

a successful build

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: `SAM CLI, version 0.52.0`

**Comment by jbpratt78** [comment]
Forgot to add the template, then noticed that I was building for 3.7, swapping to 3.8 results in a successful build.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: [AWS::Serverless-2016-10-31]
Resources:
  WebexTeamsSdk:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.7
    Properties:
      LayerName: webexteamssdk
      Description: dependency
      ContentUri: webexteamssdk/
      CompatibleRuntimes:
        - python3.7
```

I believe this can be closed as user error.
