### ISSUE TITLE
Sending request to locally hosted API results in Internal Server Error

### ISSUE THREAD

**Issue by TJClifton90** [awslabs/aws-sam-cli#2084]
### Description

I have been unable to get SAM Local to work on Windows 10. I have followed the instructions [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html) and attempts to interact with the locally hosted API or invoke my lambda functions manually result in the error attached below.

### Steps to reproduce

1. Follow instructions on [Official Documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html) for setting up a sample application (Steps 1 and 2).
2. Host the API locally with `sam local start-api`
3. As per the doc above, send a request to the locally hosted API with `curl http://127.0.0.1:3000/hello`
4. Observe the error below:

### Observed result

```
PS C:\Projects\3rdParty\sam-app> sam local start-api --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
local start-api command is called
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
No Parameters detected in the template
2 resources found in the template
Found '1' API Events in Serverless function with name 'HelloWorldFunction'
Detected Inline Swagger definition
Lambda function integration not found in Swagger document at path='/hello' method='get'
Found '0' APIs in resource 'ServerlessRestApi'
Removed duplicates from '0' Explicit APIs and '1' Implicit APIs to produce '1' APIs
1 APIs found in the template
Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
Localhost server is starting up. Multi-threading = True
2020-07-02 13:25:26  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
Constructed String representation of Event to invoke Lambda. Event: {"httpMethod": "GET", "body": null, "resource": "/hello", "requestContext": {"resourceId": "123456", "apiId": "1234567890", "resourcePath": "/hello", "httpMethod": "GET", "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef", "accountId": "123456789012", "stage": "Prod", "identity": {"apiKey": null, "userArn": null, "cognitoAuthenticationType": null, "caller": null, "userAgent": "Custom User Agent String", "user": null, "cognitoIdentityPoolId": null, "cognitoAuthenticationProvider": null, "sourceIp": "127.0.0.1", "accountId": null}, "extendedRequestId": null, "path": "/hello"}, "queryStringParameters": null, "multiValueQueryStringParameters": null, "headers": {"Host": "127.0.0.1:3000", "User-Agent": "curl/7.55.1", "Accept": "*/*", "X-Forwarded-Proto": "http", "X-Forwarded-Port": "3000"}, "multiValueHeaders": {"Host": ["127.0.0.1:3000"], "User-Agent": ["curl/7.55.1"], "Accept": ["*/*"], "X-Forwarded-Proto": ["http"], "X-Forwarded-Port": ["3000"]}, "pathParameters": null, "stageVariables": null, "path": "/hello", "isBase64Encoded": false}
Found one Lambda function with name 'HelloWorldFunction'
Invoking HelloWorld::HelloWorld.Function::FunctionHandler (dotnetcore2.1)
Environment variables overrides data is standard format
Loading AWS credentials from session with profile 'None'
Resolving code path. Cwd=C:\Projects\3rdParty\sam-app\.aws-sam\build, CodeUri=HelloWorldFunction
Resolved absolute path to code is C:\Projects\3rdParty\sam-app\.aws-sam\build\HelloWorldFunction
Code C:\Projects\3rdParty\sam-app\.aws-sam\build\HelloWorldFunction is not a zip/jar file
Skipping building an image since no layers were defined

Fetching lambci/lambda:dotnetcore2.1 Docker container image......
Mounting C:\Projects\3rdParty\sam-app\.aws-sam\build\HelloWorldFunction as /var/task:ro,delegated inside runtime container
Container was not created. Skipping deletion
2020-07-02 13:25:36 Exception on /hello [GET]
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.35/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\apigw\local_apigw_service.py", line 203, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\lib\local_lambda.py", line 100, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\runtime.py", line 83, in invoke
    self._container_manager.run(container)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 93, in run
    container.create()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\container.py", line 133, in create
    real_container = self.docker_client.containers.create(self._image, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\models\containers.py", line 861, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 267, in _result
    self._raise_for_status(response)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("invalid bind mount spec "/c/Projects/3rdParty/sam-app/.aws-sam/build/HelloWorldFunction:/var/task:ro,delegated": invalid mode: ro,delegated")
```

### Expected result

The locally hosted API should return an output similar to that in the documentation.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 Pro 1903
2. `sam --version`: SAM CLI, version 0.53.0
3. `docker --version`: Docker version 17.03.1-ce-rc1, build 3476dbf
4. Docker set to use Linux Containers and has access to C drive.

**Comment by jfuss** [comment]
@TJClifton90 You are using a docker version from 2017, have you tried upgrading that? From the error, it seems like you docker is incompatible with what SAM CLI needs to do.

**Comment by sriram-mv** [comment]
definitely seems like an older version of the docker, thats the culprit. Closing the issue, feel free to reopen if you are still seeing this after upgrading docker version.

**Comment by TJClifton90** [comment]
Apologies for the late reply. Just to confirm that was indeed the issue. I only just installed docker so not sure how I managed to install such an antiquated version!

Thanks for the assistance.
