### ISSUE TITLE
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "...." could not be found.

### ISSUE THREAD

**Issue by imti283** [awslabs/aws-sam-cli#2085]
### Description

Issue while Init'ing cookiecutter as well non-cookiecutter github repo.

### Steps to reproduce

>>sam init --location gh:awslabs/aws-sam-cli-app-templates --debug --name my-test-app1

### Observed result

PS C:\Users\mdimtiya\Desktop\Scripts\LmbdaCIC\testy> sam --version
SAM CLI, version 0.53.0
PS C:\Users\mdimtiya\Desktop\Scripts\LmbdaCIC\testy>  sam init --location gh:awslabs/aws-sam-cli-app-templates --debug --name my-test-app1
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Parameters dict created with input given
{'template': 'gh:awslabs/aws-sam-cli-app-templates', 'output_dir': '.', 'no_input': False, 'extra_context': {'project_name': 'my-test-app1'}}
Baking a new template with cookiecutter with all parameters
You've downloaded C:\Users\mdimtiya\.cookiecutters\aws-sam-cli-app-templates before. Is it okay to delete and re-download it? [yes]: y
Unable to find cookiecutter.json in the project. Downloading it directly without treating it as a cookiecutter template
Downloading project from gh:awslabs/aws-sam-cli-app-templates to my-test-app1
https://github.com/awslabs/aws-sam-cli-app-templates.git location is a source control repository
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam init', 'duration': 31583, 'exitReason': 'PermissionError', 'exitCode': 255, 'requestId': 'e5221dee-dcce-4b42-a3b9-1edc9e1be7ff', 'installationId': '5e8ad87e-b364-46b8-a362-da8c21380d29', 'sessionId': '5c4601c7-051c-4672-a8e7-62cdaeb8073d', 'executionEnvironment': 'CLI', 'pyversion': '3.7.2', 'samcliVersion': '0.53.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\samcli\lib\init\__init__.py", line 80, in generate_project
    cookiecutter(**params)
  File "c:\python37\lib\site-packages\cookiecutter\main.py", line 63, in cookiecutter
    password=password
  File "c:\python37\lib\site-packages\cookiecutter\repository.py", line 122, in determine_repo_dir
    '\n'.join(repository_candidates)
cookiecutter.exceptions.RepositoryNotFound: A valid repository for "https://github.com/awslabs/aws-sam-cli-app-templates.git" could not be found in the following locations:
C:\Users\mdimtiya\.cookiecutters\aws-sam-cli-app-templates

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\sam.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python37\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python37\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "c:\python37\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "c:\python37\lib\site-packages\samcli\commands\init\__init__.py", line 118, in cli
    extra_context,
  File "c:\python37\lib\site-packages\samcli\commands\init\__init__.py", line 163, in do_cli
    do_generate(location, runtime, dependency_manager, output_dir, name, no_input, extra_context)
  File "c:\python37\lib\site-packages\samcli\commands\init\init_generator.py", line 12, in do_generate
    generate_project(location, runtime, dependency_manager, output_dir, name, no_input, extra_context)
  File "c:\python37\lib\site-packages\samcli\lib\init\__init__.py", line 89, in generate_project
    generate_non_cookiecutter_project(location=params["template"], output_dir=project_output_dir)
  File "c:\python37\lib\site-packages\samcli\lib\init\arbitrary_project.py", line 81, in generate_non_cookiecutter_project
    return _download_and_copy(download_fn, output_dir)
  File "c:\python37\lib\site-packages\samcli\lib\init\arbitrary_project.py", line 108, in _download_and_copy
    osutils.copytree(downloaded_dir, output_dir, ignore=shutil.ignore_patterns("*.git"))
  File "c:\python37\lib\contextlib.py", line 119, in __exit__
    next(self.gen)
  File "c:\python37\lib\site-packages\samcli\lib\utils\osutils.py", line 49, in mkdir_temp
    shutil.rmtree(temp_dir)
  File "c:\python37\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\python37\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\python37\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\python37\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "c:\python37\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\python37\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\mdimtiya\\AppData\\Local\\Temp\\tmpf3g9pr58\\aws-sam-cli-app-templates\\.git\\objects\\pack\\pack-01e9912e67cc4a806515aa98dc9b6678a20461ea.idx'
PS C:\Users\mdimtiya\Desktop\Scripts\LmbdaCIC\testy>

### Expected result

Should clone without giving any error. It is cloning the repo but statement exiting with error.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10,15063
2. `sam --version`: 0.53.0

`Add --debug flag to command you are running`

**Comment by awood45** [comment]
This is not the correct way to use the AWS SAM CLI App Templates. If you want to use a template from that repository, just run `sam init` without any parameters, and an interactive menu will guide you through those templates.

If you are passing in a custom location, the expectation is that the target repository is a valid Cookiecutter repo, or that we can download it directly. This DOES now work (in `1.0.0`) by expanding out the contents of the repository into your target folder, but you probably want to just run `sam init` to use the contents.

For an example of a custom location app template, you can try using https://github.com/awood45/aws-sam-sinatra-template as an example. Feel free to reopen if you're still seeing this issue in `1.0.0`, or with that template.
