### ISSUE TITLE
sam init works on windows but not on mac

### ISSUE THREAD

**Issue by setuk** [awslabs/aws-sam-cli#403]
Testing sam for the first time.
Installed it on Windows ok and sam init --runtime python worked fine.

Doing the same on mac yielded the following:-

sam init --runtime python
2018-05-10 17:24:49 Command 'init' is not configured correctly. Unable to import 'samcli.commands.init'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/samcli/cli/command.py", line 100, in get_command
    mod = importlib.import_module(pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/samcli/commands/init/__init__.py", line 9, in <module>
    from samcli.local.init import generate_project
  File "/Library/Python/2.7/site-packages/samcli/local/init/__init__.py", line 7, in <module>
    from cookiecutter.main import cookiecutter
  File "/Library/Python/2.7/site-packages/cookiecutter/main.py", line 15, in <module>
    from .generate import generate_context, generate_files
  File "/Library/Python/2.7/site-packages/cookiecutter/generate.py", line 27, in <module>
    from .hooks import run_hook
  File "/Library/Python/2.7/site-packages/cookiecutter/hooks.py", line 13, in <module>
    from cookiecutter import utils
  File "/Library/Python/2.7/site-packages/cookiecutter/utils.py", line 19, in <module>
    from .prompt import read_user_yes_no
  File "/Library/Python/2.7/site-packages/cookiecutter/prompt.py", line 14, in <module>
    from past.builtins import basestring
  File "/Library/Python/2.7/site-packages/past/__init__.py", line 88, in <module>
    from past.translation import install_hooks as autotranslate
  File "/Library/Python/2.7/site-packages/past/translation/__init__.py", line 42, in <module>
    from lib2to3.refactor import RefactoringTool
ImportError: No module named refactor

mac install

pip install awscli
pip install aws-sam-cli

python --version
python 2.7.10

no errors

**Comment by setuk** [comment]
This was a real pain for me when i tried to get it working it was down to a legacy version of aws-sam-cli

I had to do the following to get it working - but working now:-

	1. Upgrade python
	2. Uninstall awscli
	3. Uninstall aws-sam-cli
	4. Still had 2to3 files lying about - deleted the dir as I couldn’t pip uninstall
	5. Also removed them from aws/local/site_packages
	6. Reinstall awscli
	7. Reinstall aws-sam-cli

**Comment by jkeczan** [comment]
where does aws/local/site_packages reside usually?

**Comment by setuk** [comment]
I think it was under .aws - but i deleted it and it doesnt exist there now - didn't write that part down!

**Comment by jkeczan** [comment]
Hmm..Ok, I did your steps but I am getting the same error. 

My last error line is: ImportError: No module named refactor instead of the one above

**Comment by setuk** [comment]
That error is similar to this one
https://github.com/Entware/Entware-ng/issues/268

The issue is you have python3-lib2to3 in your site packages from what i recall

**Comment by AlexOugh** [comment]
I have the same problem in my mac even if I re-installed awscli & sam-cli.

Fetching lambci/lambda:python2.7 Docker container image......
2018-06-07 12:02:25 Mounting /Users/alex.ough/Projects/sam_cli/sam-app/hello_world/build as /var/task:ro inside runtime container
START RequestId: 81384622-066c-462a-a976-a29041f75caa Version: $LATEST
Unable to import module 'app': No module named app
END RequestId: 81384622-066c-462a-a976-a29041f75caa

**Comment by AlexOugh** [comment]
I did a little bit of investigation and I found that the python source file (app.py) and necessary libraries (requests) are NOT deployed in 'build' folder when I run 'sam local start-api' after I created the sample project using 'sam init --runtime python'.

Should the files be deployed to 'build' folder or am I missing any commands before running 'sam local start-api' for deployment?

**Comment by setuk** [comment]
You need to create a deployment package and reference that from your SAM template. Have a look at these docs. https://docs.aws.amazon.com/lambda/latest/dg/deployment-package-v2.html

**Comment by AlexOugh** [comment]
I know how to package the deployment files, but I thought this sam cli does it for you when it starts the container.

Anyway, it may be helpful to make this clear in the sam-cli documentation.

**Comment by setuk** [comment]
i just went up this learning curve so i share your pain.
I ended up with a debug build process that looks like this:-

![image](https://user-images.githubusercontent.com/10343466/41120724-53bfc4c2-6a8e-11e8-8724-b94a9bf472c8.png)


Note i build my dependencies within a docker container which is Amazon Linux based else you end up with ELF header mismatch errors. Also copy all sources into the container. Output of the docker build is a zip which i reference in the SAM template.

**Comment by setuk** [comment]
I think its fine to close
