### ISSUE TITLE
Package and Deploy needs AWS CLI

### ISSUE THREAD

**Issue by goldenbearkin** [awslabs/aws-sam-cli#432]
I ran "sam package ..." in circleci, below is what I got (I can successfully run locally on my mac High Sierra):
````
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/samcli/commands/package/__init__.py", line 22, in cli
    do_cli(args)  # pragma: no cover
  File "/usr/local/lib/python2.7/site-packages/samcli/commands/package/__init__.py", line 26, in do_cli
    execute_command("package", args)
  File "/usr/local/lib/python2.7/site-packages/samcli/lib/samlib/cloudformation_command.py", line 17, in execute_command
    subprocess.check_call([aws_cmd, 'cloudformation', command] + list(args))
  File "/usr/local/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
````
docker image: circleci/python:2.7.15

**Comment by jfuss** [comment]
The package and deploy commands need the AWS CLI installed. I thought we already had this called out in the README, but that doesn't look to be the case.

Marking this as a doc update related to package and deploy.

**Comment by funkybob** [comment]
Any mention at all in the docs that you need to "pip install awscli" would be _really_ helpful.

**Comment by jfuss** [comment]
Our docs point to install AWS CLI already. Example: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html

Closing as it is resolved.
