### ISSUE TITLE
dockerpycreds.errors.InitializationError: docker-credential-wincred not installed or not available in PATH

### ISSUE THREAD

**Issue by red8888** [awslabs/aws-sam-cli#486]
**Description:**

**Steps to reproduce the issue:**
1. uninstall sam npm
2. install sam with pip (python 2)

**Observed result:**
`sam local invoke zzzz--template temps/blah.yaml -e events/test.json`

2018-06-15 19:18:20 Invoking lambda_function.lambda_handler (python3.6)
2018-06-15 19:18:20 Found credentials in shared credentials file: ~/.aws/credentials
Traceback (most recent call last):
  File "C:\users\meeee\appdata\roaming\python\Scripts\sam-script.py", line 11, in <module>
    load_entry_point('aws-sam-cli==0.3.0', 'console_scripts', 'sam')()
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\samcli\commands\local\invoke\cli.py", line 44, in cli
    docker_network, log_file, skip_pull_image, profile)  # pragma: no cover
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\samcli\commands\local\invoke\cli.py", line 76, in do_cli
    stderr=context.stderr)
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\samcli\commands\local\lib\local_lambda.py", line 80, in invoke
    stdout=stdout, stderr=stderr)
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\samcli\local\lambdafn\runtime.py", line 83, in invoke
    self._container_manager.run(container)
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\samcli\local\docker\manager.py", line 53, in run
    self.pull_image(image_name)
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\samcli\local\docker\manager.py", line 83, in pull_image
    result_itr = self.docker_client.api.pull(image_name, stream=True, decode=True)
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\docker\api\image.py", line 380, in pull
    header = auth.get_config_header(self, registry)
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\docker\auth.py", line 47, in get_config_header
    authcfg = resolve_authconfig(client._auth_configs, registry)
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\docker\auth.py", line 94, in resolve_authconfig
    authconfig, registry, store_name
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\docker\auth.py", line 124, in _resolve_authconfig_credstore
    store = dockerpycreds.Store(credstore_name)
  File "C:\Users\meeee\AppData\Roaming\Python\Python27\site-packages\dockerpycreds\store.py", line 25, in __init__
    self.program
dockerpycreds.errors.InitializationError: docker-credential-wincred not installed or not available in PATH

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Windows 10

**Output of `sam --version`**:
SAM CLI, version 0.3.0

**Comment by jfuss** [comment]
@red8888 This is coming from the docker-py library we are using. Unfortunately, we don't have much control of that.

Closing this as it is a docker issue.
