### ISSUE TITLE
Getting TypeError: load_config() got an unexpected keyword argument 'config_dict' when trying to run sam local start-api

### ISSUE THREAD

**Issue by eranation** [awslabs/aws-sam-cli#536]
**Description:**

This is probably a docker version issue, but when trying out the example, I'm getting this error: TypeError: load_config() got an unexpected keyword argument 'config_dict'

**Steps to reproduce the issue:**
1. install sam cli via pip install --user aws-sam-cli
2. follow the hello world tutorial
3. sam local start-api

**Observed result:**

Error is printed (See below)

**Expected result:**

No errors 

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

Mac. Sierra, 10.12.6 
Python 2.7.10
pip 10.0.1 from /Library/Python/2.7/site-packages/pip (python 2.7)
Docker version 17.12.0-ce, build c97c6d6

**Output of `sam --version`**:

SAM CLI, version 0.4.0

**Optional Debug logs**:

`Add --debug flag to command you are running`

This probably explains the root cause, I assume the docker config structure changed or something? 

```
sam local start-api --debug
2018-07-05 14:22:46 local start-api command is called
2018-07-05 14:22:46 2 resources found in the template
2018-07-05 14:22:46 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2018-07-05 14:22:46 Trying paths: ['/Users/****/.docker/config.json', '/Users/****/.dockercfg']
2018-07-05 14:22:46 Found file at path: /Users/****/.docker/config.json
Traceback (most recent call last):
  File "/Users/****/Library/Python/2.7/bin/sam", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/samcli/commands/local/start_api/cli.py", line 56, in cli
    docker_network, log_file, skip_pull_image, profile)  # pragma: no cover
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/samcli/commands/local/start_api/cli.py", line 80, in do_cli
    aws_profile=profile) as invoke_context:
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/samcli/commands/local/cli_common/invoke_context.py", line 93, in __enter__
    self._check_docker_connectivity()
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/samcli/commands/local/cli_common/invoke_context.py", line 284, in _check_docker_connectivity
    docker_client = docker_client or docker.from_env()
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/docker/client.py", line 85, in from_env
    timeout=timeout, version=version, **kwargs_from_env(**kwargs)
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/docker/client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/Users/****/Library/Python/2.7/lib/python/site-packages/docker/api/client.py", line 113, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'
```

**Comment by jfuss** [comment]
@johncblandii and @eranation This is happening for inside the docker client when trying to load your docker config. [Here](https://github.com/docker/docker-py/issues/1916) is an issue on docker-py about this error. 

Do either of you have docker and docker-py installed (a `pip freeze` would help in determining this)? The suggestion looks like you uninstall docker from the env. Can one of you try this?

**Comment by ianaya89** [comment]
I was having the same issue, I check that I had installed `docker` and `docker-py`.
I run `pip uninstall docker-py` and that solved the issue.

Thanks @jfuss

**Comment by sergeir72** [comment]
still happens

El Capitan, latest docker, latest sam cli


sam init
mvn clean package
sam local start-lambda

File "/usr/local/homebrew/lib/python2.7/site-packages/flask/app.py", line 976, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'provide_automatic_options'

**Comment by jpascoe** [comment]
Still happening (14th Jul 2019)

**Comment by jpascoe** [comment]
I dont have docker-py installed

**Comment by nem035** [comment]
@jpascoe I had the same issue but after installing awscli and aws-sam-cli using python3, it worked for me:

```sh
pip3 install awscli aws-sam-cli
```
