### ISSUE TITLE
DistributionNotFound - requires aws-sam-cli==0.5.0

### ISSUE THREAD

**Issue by Ploppz** [awslabs/aws-sam-cli#592]
After installing with `pip install --user aws-sam-cli`, whenever I try to use it I get this error:

```
$ sam
Traceback (most recent call last):
  File "/home/ploppz/.local/bin/sam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ploppz/sam-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/home/ploppz/sam-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/home/ploppz/sam-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ploppz/sam-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/home/ploppz/sam-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ploppz/sam-venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aws-sam-cli==0.5.0' distribution was not found and is required by the application
```

I am installing it inside a venv. But when I run `pip show aws-sam-cli`, nothing it output. I don't know whether there is a problem with the installation.

**Comment by Ploppz** [comment]
Seems to be related to how I installed `aws-sam-cli`. Never mind.

**Comment by Mexx77** [comment]
Hey @Ploppz ,
I see the same error. How did you fix it?

**Comment by Ploppz** [comment]
If I remember correctly now... I think I first had to upgrade `pip` possibly? And then try again to install the latestversion of `aws-sam-cli`. I think this problem has to do with having a too old version.

**Comment by Mexx77** [comment]
I found my mistake. I installed sam to `.local/` via `pip install --user aws-sam-cli`. 
`$HOME/.local/bin` was wrongly owned by root. `chown -R $USER: $HOME/.local/bin` fixed it :)
