### ISSUE TITLE
Quick Start Hello World Application cannot build/find container

### ISSUE THREAD

**Issue by SCalwas** [awslabs/aws-sam-cli#837]
**Description:**

Running the Quick Start Hello World Application described at https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-quick-start.html raises a RuntimeError.

**Steps to reproduce the issue:**
1. Install Docker for Windows using default settings
2. Install SAM CLI version 0.8.1
3. Follow Quick Start Hello World Application, including commands "sam init --runtime python3.7" and "cd sam-app"
4. Run "sam build --use-container" raises RuntimeError

**Observed result:**
Relevant command output:
Fetching lambci/lambda:build-python3.7 Docker container image.............
2018-12-05 19:07:12 Mounting C:\PythonCode\sampoc\sam-app\hello_world as /tmp/samcli/source:ro inside runtime container
Traceback ....
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\samcli\local\docker\container.py", line 195, in wait_for_logs
  raise RuntimeError ("Container does not exist. Cannot get logs for this container")

**Expected result:**
Expected the result described in the Quick Start instructions.

**Comment by TheSriram** [comment]
I just tried to repro this and didn't run into this issue. Could you try restarting your docker, maybe?

**Comment by SCalwas** [comment]
Yes, I did restart both Docker and my computer. I ran these commands both yesterday and today with the same results.
I'm not familiar with Docker, but its Windows default uses Linux containers(?). An output message I quoted in my OP describes mounting a Windows item to a Linux reference. Could this be an issue?

**Comment by TheSriram** [comment]
the path mount shouldn't be an issue, we want to choose Linux containers. can you try running with ```--debug``` and the paste the entire trace here

**Comment by SCalwas** [comment]
Here is all the output from the command "sam build --use-container --debug".

2018-12-06 17:01:30 Using SAM Template at C:\PythonCode\sampoc\sam-app\template.yaml
2018-12-06 17:01:30 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2018-12-06 17:01:30 Changing event name from before-call.apigateway to before-call.api-gateway
2018-12-06 17:01:30 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2018-12-06 17:01:30 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2018-12-06 17:01:30 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2018-12-06 17:01:30 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2018-12-06 17:01:30 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2018-12-06 17:01:30 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2018-12-06 17:01:30 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2018-12-06 17:01:30 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2018-12-06 17:01:30 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2018-12-06 17:01:30 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2018-12-06 17:01:30 Changing event name from before-call.apigateway to before-call.api-gateway
2018-12-06 17:01:30 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2018-12-06 17:01:30 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2018-12-06 17:01:30 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2018-12-06 17:01:30 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2018-12-06 17:01:30 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2018-12-06 17:01:30 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2018-12-06 17:01:30 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2018-12-06 17:01:30 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2018-12-06 17:01:30 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2018-12-06 17:01:30 'build' command is called
2018-12-06 17:01:30 Starting Build inside a container
2018-12-06 17:01:30 Looking for credentials via: env
2018-12-06 17:01:30 Looking for credentials via: assume-role
2018-12-06 17:01:30 Looking for credentials via: shared-credentials-file
2018-12-06 17:01:30 Found credentials in shared credentials file: ~/.aws/credentials
2018-12-06 17:01:30 Loading JSON file: C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\botocore\data\endpoints.json
2018-12-06 17:01:30 Event choose-service-name: calling handler <function handle_service_name_alias at 0x000001DF332F4F28>
2018-12-06 17:01:30 Loading JSON file: C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\botocore\data\serverlessrepo\2017-09-08\service-2.json
2018-12-06 17:01:30 Event creating-client-class.serverlessapplicationrepository: calling handler <function add_generate_presigned_url at 0x000001DF332B8D90>
2018-12-06 17:01:30 The s3 config key is not a dictionary type, ignoring its value of: None
2018-12-06 17:01:30 Setting serverlessrepo timeout as (60, 60)
2018-12-06 17:01:30 Loading JSON file: C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\botocore\data\_retry.json
2018-12-06 17:01:30 Registering retry handlers for service: serverlessrepo
2018-12-06 17:01:30 No Parameters detected in the template
2018-12-06 17:01:30 2 resources found in the template
2018-12-06 17:01:30 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2018-12-06 17:01:30 Trying paths: ['C:\\Users\\scalwas\\.docker\\config.json', 'C:\\Users\\scalwas\\.dockercfg']
2018-12-06 17:01:30 Found file at path: C:\Users\scalwas\.docker\config.json
2018-12-06 17:01:30 Couldn't find auth-related section ; attempting to interpret as auth-only file
2018-12-06 17:01:30 Config entry for key stackOrchestrator is not auth config
2018-12-06 17:01:30 Building resource 'HelloWorldFunction'
2018-12-06 17:01:30 Trying paths: ['C:\\Users\\scalwas\\.docker\\config.json', 'C:\\Users\\scalwas\\.dockercfg']
2018-12-06 17:01:30 Found file at path: C:\Users\scalwas\.docker\config.json
2018-12-06 17:01:30 Couldn't find auth-related section ; attempting to interpret as auth-only file
2018-12-06 17:01:30 Config entry for key stackOrchestrator is not auth config
2018-12-06 17:01:30 http://localhost:None "GET /v1.35/images/lambci/lambda:build-python3.7/json HTTP/1.1" 200 None
2018-12-06 17:01:30 Looking for auth config
2018-12-06 17:01:30 Looking for auth entry for 'docker.io'
2018-12-06 17:01:30 No entry found
2018-12-06 17:01:30 No auth config found
2018-12-06 17:01:32 http://localhost:None "POST /v1.35/images/create?tag=build-python3.7&fromImage=lambci%2Flambda HTTP/1.1" 200 None

Fetching lambci/lambda:build-python3.7 Docker container image......
2018-12-06 17:01:32 Mounting C:\PythonCode\sampoc\sam-app\hello_world as /tmp/samcli/source:ro inside runtime container
2018-12-06 17:01:58 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 500 26
Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\Scripts\sam.exe\__main__.py", line 9, in <module>
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\samcli\commands\build\command.py", line 94, in cli
    skip_pull_image, parameter_overrides)  # pragma: no cover
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\samcli\commands\build\command.py", line 132, in do_cli
    artifacts = builder.build()
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\samcli\lib\build\app_builder.py", line 117, in build
    lambda_function.runtime)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\samcli\lib\build\app_builder.py", line 189, in _build_function
    runtime)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\samcli\lib\build\app_builder.py", line 249, in _build_function_on_container
    container.wait_for_logs(stdout=stdout_stream, stderr=stderr_stream)
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\site-packages\samcli\local\docker\container.py", line 195, in wait_for_logs
    raise RuntimeError("Container does not exist. Cannot get logs for this container")
RuntimeError: Container does not exist. Cannot get logs for this container

**Comment by SCalwas** [comment]
Any news on this issue? I tried the newest SAM v0.10.0 and backtracking from Python 3.7.1 to 3.6.8, but they had no effect. I also tried backtracking the pypiwin32 package from 223 to 220 as described in issue #847, but again had no effect.

Here is the debug output from running SAM 0.10.0, Python 3.6.8, pypiwin32 223.

$ sam build --use-container --debug > log.txt                                                                                                                                               
2018-12-27 17:40:40 Using SAM Template at C:\PythonCode\sampoc\sam-app\template.yaml                                                                                                        
2018-12-27 17:40:40 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane                                                                         
2018-12-27 17:40:40 Changing event name from before-call.apigateway to before-call.api-gateway                                                                                              
2018-12-27 17:40:40 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict                                                            
2018-12-27 17:40:40 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration                  
2018-12-27 17:40:40 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53                                                                              
2018-12-27 17:40:40 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search                                                          
2018-12-27 17:40:40 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section                
2018-12-27 17:40:40 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask                                        
2018-12-27 17:40:40 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section                                      
2018-12-27 17:40:40 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search                                            
2018-12-27 17:40:40 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section                                          
2018-12-27 17:40:40 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane                                                                         
2018-12-27 17:40:40 Changing event name from before-call.apigateway to before-call.api-gateway                                                                                              
2018-12-27 17:40:40 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict                                                            
2018-12-27 17:40:40 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration                  
2018-12-27 17:40:40 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53                                                                              
2018-12-27 17:40:40 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search                                                          
2018-12-27 17:40:40 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section                
2018-12-27 17:40:40 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask                                        
2018-12-27 17:40:40 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section                                      
2018-12-27 17:40:40 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search                                            
2018-12-27 17:40:40 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section                                          
2018-12-27 17:40:40 'build' command is called                                                                                                                                               
2018-12-27 17:40:40 Starting Build inside a container                                                                                                                                       
2018-12-27 17:40:40 Looking for credentials via: env                                                                                                                                        
2018-12-27 17:40:40 Looking for credentials via: assume-role                                                                                                                                
2018-12-27 17:40:40 Looking for credentials via: shared-credentials-file                                                                                                                    
2018-12-27 17:40:40 Found credentials in shared credentials file: ~/.aws/credentials                                                                                                        
2018-12-27 17:40:40 Loading JSON file: C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\botocore\data\endpoints.json                                                          
2018-12-27 17:40:40 Event choose-service-name: calling handler <function handle_service_name_alias at 0x000001F206AC4EA0>                                                                   
2018-12-27 17:40:40 Loading JSON file: C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\botocore\data\serverlessrepo\2017-09-08\service-2.json                                
2018-12-27 17:40:40 Event creating-client-class.serverlessapplicationrepository: calling handler <function add_generate_presigned_url at 0x000001F206A85B70>                                
2018-12-27 17:40:40 The s3 config key is not a dictionary type, ignoring its value of: None                                                                                                 
2018-12-27 17:40:40 Setting serverlessrepo timeout as (60, 60)                                                                                                                              
2018-12-27 17:40:40 Loading JSON file: C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\botocore\data\_retry.json                                                             
2018-12-27 17:40:40 Registering retry handlers for service: serverlessrepo                                                                                                                  
2018-12-27 17:40:41 No Parameters detected in the template                                                                                                                                  
2018-12-27 17:40:41 2 resources found in the template                                                                                                                                       
2018-12-27 17:40:41 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'                                                                                     
2018-12-27 17:40:41 Trying paths: ['C:\\Users\\scalwas\\.docker\\config.json', 'C:\\Users\\scalwas\\.dockercfg']                                                                            
2018-12-27 17:40:41 Found file at path: C:\Users\scalwas\.docker\config.json                                                                                                                
2018-12-27 17:40:41 Couldn't find auth-related section ; attempting to interpret as auth-only file2018-12-27 17:40:41 Config entry for key stackOrchestrator is not auth config             
2018-12-27 17:40:41 Building resource 'HelloWorldFunction'                                                                                                                                  
2018-12-27 17:40:41 Trying paths: ['C:\\Users\\scalwas\\.docker\\config.json', 'C:\\Users\\scalwas\\.dockercfg']                                                                            
2018-12-27 17:40:41 Found file at path: C:\Users\scalwas\.docker\config.json                                                                                                                
2018-12-27 17:40:41 Couldn't find auth-related section ; attempting to interpret as auth-only file2018-12-27 17:40:41 Config entry for key stackOrchestrator is not auth config             
2018-12-27 17:40:41 http://localhost:None "GET /v1.35/images/lambci/lambda:build-python3.6/json HTTP/1.1" 200 None                                                                          
2018-12-27 17:40:41 Looking for auth config                                                                                                                                                 
2018-12-27 17:40:41 Looking for auth entry for 'docker.io'                                                                                                                                  
2018-12-27 17:40:41 No entry found                                                                                                                                                          
2018-12-27 17:40:41 No auth config found                                                                                                                                                    
2018-12-27 17:40:42 http://localhost:None "POST /v1.35/images/create?tag=build-python3.6&fromImage=lambci%2Flambda HTTP/1.1" 200 None                                                       
                                                                                                                                                                                            
Fetching lambci/lambda:build-python3.6 Docker container image......                                                                                                                         
2018-12-27 17:40:42 Mounting C:\PythonCode\sampoc\sam-app\hello_world as /tmp/samcli/source:ro inside runtime container                                                                     
2018-12-27 17:40:49 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 500 42                                                                                                   
Traceback (most recent call last):                                                                                                                                                          
  File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main                                                                                                                          
    "__main__", mod_spec)                                                                                                                                                                   
  File "c:\python3\lib\runpy.py", line 85, in _run_code                                                                                                                                     
    exec(code, run_globals)                                                                                                                                                                 
  File "C:\Users\scalwas\AppData\Roaming\Python\Python37\Scripts\sam.exe\__main__.py", line 9, in <module>                                                                                  
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 722, in __call__                                                                                
    return self.main(*args, **kwargs)                                                                                                                                                       
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 697, in main                                                                                    
    rv = self.invoke(ctx)                                                                                                                                                                   
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 1066, in invoke                                                                                 
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                                                 
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 895, in invoke                                                                                  
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                                          
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 535, in invoke                                                                                  
    return callback(*args, **kwargs)                                                                                                                                                        
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\click\decorators.py", line 64, in new_func                                                                           
    return ctx.invoke(f, obj, *args[1:], **kwargs)                                                                                                                                          
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\click\core.py", line 535, in invoke                                                                                  
    return callback(*args, **kwargs)                                                                                                                                                        
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\samcli\commands\build\command.py", line 94, in cli                                                                   
    skip_pull_image, parameter_overrides)  # pragma: no cover                                                                                                                               
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\samcli\commands\build\command.py", line 132, in do_cli                                                               
    artifacts = builder.build()                                                                                                                                                             
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\samcli\lib\build\app_builder.py", line 129, in build                                                                 
    lambda_function.runtime)                                                                                                                                                                
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\samcli\lib\build\app_builder.py", line 201, in _build_function                                                       
    runtime)                                                                                                                                                                                
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\samcli\lib\build\app_builder.py", line 261, in _build_function_on_container                                          
    container.wait_for_logs(stdout=stdout_stream, stderr=stderr_stream)                                                                                                                     
  File "C:\Users\scalwas\AppData\Roaming\Python\Python36\site-packages\samcli\local\docker\container.py", line 196, in wait_for_logs                                                        
    raise RuntimeError("Container does not exist. Cannot get logs for this container")                                                                                                      
RuntimeError: Container does not exist. Cannot get logs for this container

**Comment by jfuss** [comment]
@SCalwas Looking at your output, this is the key part:
```
2018-12-27 17:40:42 http://localhost:None "POST /v1.35/images/create?tag=build-python3.6&fromImage=lambci%2Flambda HTTP/1.1" 200 None

Fetching lambci/lambda:build-python3.6 Docker container image......
2018-12-27 17:40:42 Mounting C:\PythonCode\sampoc\sam-app\hello_world as /tmp/samcli/source:ro inside runtime container
2018-12-27 17:40:49 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 500 42
```

You can see that the container appears to be downloaded locally but we we go to create the container, docker blows up. 

Given you are on Windows, can you make sure that the container type is linux and not windows. My current guess is that docker is giving an internal service error because of this. You are able to download so that means docker is running and responsive.

**Comment by SCalwas** [comment]
Docker is using Linux containers. During installation, Linus containers were the default type, and I left that unchanged. Also, right-clicking the Docker icon pops up a menu with an item of "Switch to Windows containers..." When clicked, a dialog asks if I'm sure I want to change from Linux containers to Windows containers. So definitely using Linux containers.

FYI: Using SAM 0.10.0 and Python 3.6.8 and running "sam build --use-container," Docker prompts whether I want to share drive C:. This prompt did not occur with SAM 0.08.0 and Python 3.7.1.

**Comment by jfuss** [comment]
That prompt is from Docker not SAM CLI.

You want to share the C: drive, if that is the drive you are working from. Does sharing solve this for you?

**Comment by SCalwas** [comment]
:-) FYI: I work at AWS. SDK Programmer Writer. Think I have any chance of getting past the firewall??? :-)

**Comment by ChristopherAyling** [comment]
I had the same error (I'm running Windows 10), sharing C drive solved it. Thank you very much!

![image](https://user-images.githubusercontent.com/28856397/51013309-7c460580-15ad-11e9-92ee-7080e0610c1e.png)

**Comment by jpaulino04** [comment]
Hey guys, 

Just in case, ensure that you initialize and build using the latest sam cli install.

I had this issue when I tried initializing the app with an old version of the aws sam cli while doing the build with the newer version.

**Comment by jfuss** [comment]
Initially issue was due to a firewall blocking the traffic to the Docker Daemon. Closing as it was an issue with the system and not SAM CLI
