### ISSUE TITLE
cannot load such file -- app

### ISSUE THREAD

**Issue by daveroberts** [awslabs/aws-sam-cli#865]
### Description

When trying to run the default project with ruby2.5 runtime, get the following error:

```
2018-12-17 16:58:29  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2018-12-17 16:58:53 Invoking app.lambda_handler (ruby2.5)

Fetching lambci/lambda:ruby2.5 Docker container image.......
2018-12-17 16:58:53 Mounting /home/daver/code/sam-app/hello_world as /var/task:ro inside runtime container
Init error when loading handler app.lambda_handler
{
  "errorMessage": "cannot load such file -- app",
  "errorType": "Init<LoadError>",
  "stackTrace": [
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
  ]
}
```

### Steps to reproduce

```
// Install Docker and start service
// Install Ruby 2.5 via rvm
// Install SAM local 0.9.0 via python pip venv
$ sam init --runtime ruby2.5
$ cd sam-app/
$ bundle install --deployment --path hello_world/vendor/bundle
$ sam local start-api
```

### Observed result

When trying to navigate to http://localhost:3000/hello

```
2018-12-17 16:58:29  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2018-12-17 16:58:53 Invoking app.lambda_handler (ruby2.5)

Fetching lambci/lambda:ruby2.5 Docker container image.......
2018-12-17 16:58:53 Mounting /home/daver/code/sam-app/hello_world as /var/task:ro inside runtime container
Init error when loading handler app.lambda_handler
{
  "errorMessage": "cannot load such file -- app",
  "errorType": "Init<LoadError>",
  "stackTrace": [
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
    "/var/lang/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'"
  ]
}
```

### Expected result

No error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: 0.9.0

**Comment by daveroberts** [comment]
This isn't exclusive to ruby, this happens for me with Python too:

```
daver@localhost:[~/code/sam-app]: echo '{"message": "Hey, are you there?" }' | sam local invoke "HelloWorldFunction"
2018-12-18 09:11:49 Reading invoke payload from stdin (you can also pass it from file with --event)
2018-12-18 09:11:49 Found credentials in shared credentials file: ~/.aws/credentials
2018-12-18 09:11:49 Invoking app.lambda_handler (python3.7)

Fetching lambci/lambda:python3.7 Docker container image...................................................................................................................................................................
2018-12-18 09:12:07 Mounting /home/daver/code/sam-app/hello_world as /var/task:ro inside runtime container
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72	Duration: 7.26 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 16 MB	
{
  "errorMessage": "Unable to import module 'app'"
}
```

**Comment by daveroberts** [comment]
Updating docker; moving app.rb to the root level and updating CodeUri to be . make this work for me.  Still not working "out of the box" though, so leaving this open.

**Comment by jfuss** [comment]
@daveroberts I just did `sam init --runtime ruby2.5`, followed the README instructions and the example worked as expected. 

You seem to be missing something in your flow. I would read and follow the README that is generated. 

Looking at your commands, you are missing a `bundle install` before your `bundle install --deployment --path hello_world/vendor/bundle`.

**Comment by jfuss** [comment]
Closing due to no response. We have also updated the Ruby examples to work with `sam build` support for Ruby where we tested the init examples and haven't seen the initially issue reported.

**Comment by daveroberts** [comment]
added bundle install and re-read the readme.  Reopened under #918
