### ISSUE TITLE
Hello world fails to run local on Windows 10 using dotnetcore2.1

### ISSUE THREAD

**Issue by matheusmaximo** [awslabs/aws-sam-cli#909]
### Description

dotnetcore2.1 version of helloworld fails to run on Windows 10

### Steps to reproduce

sam init --runtime dotnetcore2.1
cd .\sam-app\
.\build.ps1 --target=Package
sam local start-api --profile personal --debug
GET http://127.0.0.1:3000/hello from Postman

### Observed result

2019-01-04 14:42:24 Constructed String representation of Event to invoke Lambda. Event: {"httpMethod": "GET", "body": null, "resource": "/hello", "requestContext": {"resourceId": "123456", "apiId": "1234567890", "resourcePath": "/hello", "httpMethod": "GET", "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef", "accountId": "123456789012", "stage": "prod", "identity": {"apiKey": null, "userArn": null, "cognitoAuthenticationType": null, "caller": null, "userAgent": "Custom User Agent String", "user": null, "cognitoIdentityPoolId": null, "cognitoAuthenticationProvider": null, "sourceIp": "127.0.0.1", "accountId": null}, "extendedRequestId": null, "path": "/hello"}, "queryStringParameters": null, "headers": {"Cache-Control": "no-cache", "Postman-Token": "f54f43fb-7e26-4e7c-9f5c-ddd9bf75f763", "User-Agent": "PostmanRuntime/7.4.0", "Accept": "*/*", "Host": "127.0.0.1:3000", "Accept-Encoding": "gzip, deflate", "Connection": "keep-alive", "X-Forwarded-Proto": "http", "X-Forwarded-Port": "3000"}, "pathParameters": null, "stageVariables": null, "path": "/hello", "isBase64Encoded": false}
2019-01-04 14:42:24 Found one Lambda function with name 'HelloWorldFunction'
2019-01-04 14:42:24 Invoking HelloWorld::HelloWorld.Function::FunctionHandler (dotnetcore2.1)
2019-01-04 14:42:24 Environment variables overrides data is standard format
2019-01-04 14:42:24 Loading AWS credentials from session with profile 'personal'
2019-01-04 14:42:24 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-01-04 14:42:24 Changing event name from before-call.apigateway to before-call.api-gateway
2019-01-04 14:42:24 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-01-04 14:42:24 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-01-04 14:42:24 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-01-04 14:42:24 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-01-04 14:42:24 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-01-04 14:42:24 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-01-04 14:42:24 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-01-04 14:42:24 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-01-04 14:42:24 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-01-04 14:42:24 Setting config variable for profile to 'personal'
2019-01-04 14:42:25 Skipping environment variable credential check because profile name was explicitly set.
2019-01-04 14:42:25 Looking for credentials via: assume-role
2019-01-04 14:42:25 Looking for credentials via: shared-credentials-file
2019-01-04 14:42:25 Found credentials in shared credentials file: ~/.aws/credentials
2019-01-04 14:42:25 Resolving code path. Cwd=E:\Personal\sam-app, CodeUri=./artifacts/HelloWorld.zip
2019-01-04 14:42:25 Resolved absolute path to code is E:\Personal\sam-app\artifacts\HelloWorld.zip
2019-01-04 14:42:25 Decompressing E:\Personal\sam-app\artifacts\HelloWorld.zip
2019-01-04 14:42:25 File Amazon.Lambda.APIGatewayEvents.dll in zipfile does not have permission information
2019-01-04 14:42:25 File Amazon.Lambda.Core.dll in zipfile does not have permission information
2019-01-04 14:42:25 File Amazon.Lambda.Serialization.Json.dll in zipfile does not have permission information
2019-01-04 14:42:25 File HelloWorld.deps.json in zipfile does not have permission information
2019-01-04 14:42:25 File HelloWorld.dll in zipfile does not have permission information
2019-01-04 14:42:25 File HelloWorld.pdb in zipfile does not have permission information
2019-01-04 14:42:25 File HelloWorld.runtimeconfig.json in zipfile does not have permission information
2019-01-04 14:42:25 File Newtonsoft.Json.dll in zipfile does not have permission information
2019-01-04 14:42:25 Trying paths: ['C:\\Users\user_name\\.docker\\config.json', 'C:\\Users\\user_name\\.dockercfg']
2019-01-04 14:42:25 Found file at path: C:\Users\user_name\.docker\config.json
2019-01-04 14:42:25 Found 'auths' section
2019-01-04 14:42:25 Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
2019-01-04 14:42:25 Found 'credsStore' section
2019-01-04 14:42:25 http://localhost:None "GET /v1.35/images/lambci/lambda:dotnetcore2.1/json HTTP/1.1" 200 None
2019-01-04 14:42:25 Looking for auth config
2019-01-04 14:42:25 Using credentials store "wincred"
2019-01-04 14:42:25 Looking for auth entry for 'https://index.docker.io/v1/'
2019-01-04 14:42:25 Found auth config
2019-01-04 14:42:26 http://localhost:None "POST /v1.35/images/create?tag=dotnetcore2.1&fromImage=lambci%2Flambda HTTP/1.1" 200 None

Fetching lambci/lambda:dotnetcore2.1 Docker container image......
2019-01-04 14:42:26 Mounting C:\Users\user_name~1\AppData\Local\Temp\tmp1v405hy9 as /var/task:ro inside runtime container
2019-01-04 14:42:26 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 201 90
2019-01-04 14:42:26 http://localhost:None "GET /v1.35/containers/070e24bf0fdff4496546b3308dfb1dfacb29c0d012ebd7479edce71fd11da388/json HTTP/1.1" 200 None
2019-01-04 14:42:26 http://localhost:None "GET /v1.35/containers/070e24bf0fdff4496546b3308dfb1dfacb29c0d012ebd7479edce71fd11da388/json HTTP/1.1" 200 None
2019-01-04 14:42:27 http://localhost:None "POST /v1.35/containers/070e24bf0fdff4496546b3308dfb1dfacb29c0d012ebd7479edce71fd11da388/start HTTP/1.1" 500 174
2019-01-04 14:42:27 http://localhost:None "GET /v1.35/containers/070e24bf0fdff4496546b3308dfb1dfacb29c0d012ebd7479edce71fd11da388/json HTTP/1.1" 200 None
2019-01-04 14:42:27 http://localhost:None "DELETE /v1.35/containers/070e24bf0fdff4496546b3308dfb1dfacb29c0d012ebd7479edce71fd11da388?v=False&link=False&force=True HTTP/1.1" 204 0
2019-01-04 14:42:27 Exception on /hello [GET]
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.35/containers/070e24bf0fdff4496546b3308dfb1dfacb29c0d012ebd7479edce71fd11da388/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\apigw\local_apigw_service.py", line 140, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream, stderr=self.stderr)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\lib\local_lambda.py", line 81, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\runtime.py", line 79, in invoke
    self._container_manager.run(container)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 73, in run
    container.start(input_data=input_data)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\container.py", line 186, in start
    real_container.start()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\models\containers.py", line 374, in start
    return self.client.api.start(self.id, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\utils\decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\container.py", line 1066, in start
    self._raise_for_status(res)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("error while creating mount source path '/host_mnt/c/Users/user_name/AppData/Local/Temp/tmp1v405hy9': mkdir /host_mnt/c/Users/user_name/AppData: permission denied")
2019-01-04 14:42:27 127.0.0.1 - - [04/Jan/2019 14:42:27] "GET /hello HTTP/1.1" 502 -

### Expected result

Running server I believe on port 3000, returning "hello world".

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 Version 1809 (OS Build 17763.195)
2. `sam --version`: SAM CLI, version 0.7.0
3. Docker version: 

Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false

4. `dotnet --version`: 2.1.502
5. Powershell version: 5.1.17763.134

`Add --debug flag to command you are running`

**Comment by matheusmaximo** [comment]
I tried to run: `docker run --rm -v e:/Personal/sam-app/publish/HelloWorld:/var/task lambci/lambda:dotnetcore2.1 HelloWorld::HelloWorld.Function::FunctionHandler '{}'`

Got the following result:
START RequestId: c5868501-876e-4035-8bde-bf2726398282 Version: $LATEST
END  RequestId: c5868501-876e-4035-8bde-bf2726398282
REPORT RequestId c5868501-876e-4035-8bde-bf2726398282   Duration: 589 ms        Billed Duration: 600 ms       Memory Size 1536 MB     Max Memory Used: 44 MB
{"statusCode":200,"headers":{"Content-Type":"application/json"},"body":"{\"message\":\"hello world\",\"location\":\"148.252.9.218\"}"}

**Comment by jfuss** [comment]
@matheusmaximo Thanks for submitting the issue. Do you have the C: drive shared in docker? When SAM CLI sees a zip, we unzip into a temp directory (looks to be `c/Users/user_name/AppData/Local/Temp/tmp1v405hy9` in your case). This is getting a permission denied error, most likely due to docker not having access to that specific drive (it looks like you work on your E: drive).

**Comment by matheusmaximo** [comment]
I actually was using a local user different than mine to run Docker and that didn't have access to my user_data folder. I gave it access and now it's working fine.
Thanks for your help!

**Comment by edcu11** [comment]
Just as a side note: I ran into this issue last week (7/4/2020), updating docker worked for me.
