### ISSUE TITLE
Error installing aws-sam-cli

### ISSUE THREAD

**Issue by IsraelGboluwaga** [awslabs/aws-sam-cli#922]
### Error installing aws-sam-cli
Could not find a version that satisfies the requirement serverlessrepo==0.1.5 (from aws-sam-cli)

### Steps to reproduce

1. Enter `sudo pip3 install --user aws-sam-cli` or `sudo pip3 install --user --upgrade aws-sam-cli`
### Observed result
```
The directory '/home/israel/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/israel/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting aws-sam-cli
  Downloading https://files.pythonhosted.org/packages/c3/7c/79463add5772a98f044fab3024c27db61550bb1d9bbd06a715e3c3dc6b2a/aws_sam_cli-0.10.0-py3-none-any.whl (423kB)
    100% |████████████████████████████████| 430kB 1.6MB/s 
Requirement already satisfied: Flask~=1.0.2 in /usr/local/lib/python3.5/dist-packages (from aws-sam-cli) (1.0.2)
Collecting dateparser~=0.7 (from aws-sam-cli)
  Downloading https://files.pythonhosted.org/packages/ac/9e/1aa87c0c59f9731820bfd20a8b148d97b315530c2c92d1fb300328c8c42f/dateparser-0.7.0-py2.py3-none-any.whl (357kB)
    100% |████████████████████████████████| 358kB 1.4MB/s 
Collecting serverlessrepo==0.1.5 (from aws-sam-cli)
  Could not find a version that satisfies the requirement serverlessrepo==0.1.5 (from aws-sam-cli) (from versions: 0.1.6)
No matching distribution found for serverlessrepo==0.1.5 (from aws-sam-cli)

```

### Expected result
Successful Installation

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
1. OS: Ubuntu 16.04
2. `sam --version`: n/a

**Comment by jfuss** [comment]
@IsraelGboluwaga What is the version of Python you are trying to install into?

**Comment by IsraelGboluwaga** [comment]
Python 3.5.2

**Comment by jfuss** [comment]
SAM CLI supports [Python2.7, 3.6, and 3.7](https://github.com/awslabs/aws-sam-cli/blob/develop/setup.py#L49). If you elect to install through pip instead of one of our installers (installers are preferred) then the python version you install into must be one of our supported versions.

**Comment by jfuss** [comment]
https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory 
Looks like you are missing header files from the python language.

**Comment by IsraelGboluwaga** [comment]
Thanks @jfuss 

I have this now:

```
Collecting aws-sam-cli
  Using cached https://files.pythonhosted.org/packages/c3/7c/79463add5772a98f044fab3024c27db61550bb1d9bbd06a715e3c3dc6b2a/aws_sam_cli-0.10.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: boto3>=1.9.56,~=1.9 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (1.9.75)
Requirement already satisfied, skipping upgrade: python-dateutil~=2.6 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (2.7.5)
Requirement already satisfied, skipping upgrade: aws-lambda-builders==0.0.5 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (0.0.5)
Collecting dateparser~=0.7 (from aws-sam-cli)
  Using cached https://files.pythonhosted.org/packages/ac/9e/1aa87c0c59f9731820bfd20a8b148d97b315530c2c92d1fb300328c8c42f/dateparser-0.7.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: serverlessrepo==0.1.5 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (0.1.5)
Requirement already satisfied, skipping upgrade: docker>=3.3.0 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (3.6.0)
Requirement already satisfied, skipping upgrade: six~=1.11.0 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (1.11.0)
Collecting cookiecutter~=1.6.0 (from aws-sam-cli)
  Using cached https://files.pythonhosted.org/packages/16/99/1ca3a75978270288354f419e9166666801cf7e7d8df984de44a7d5d8b8d0/cookiecutter-1.6.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: requests==2.20.1 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (2.20.1)
Requirement already satisfied, skipping upgrade: chevron~=0.12 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (0.13.1)
Requirement already satisfied, skipping upgrade: click~=6.7 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (6.7)
Requirement already satisfied, skipping upgrade: PyYAML~=3.12 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (3.13)
Collecting aws-sam-translator==1.9.0 (from aws-sam-cli)
Requirement already satisfied, skipping upgrade: Flask~=1.0.2 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-cli) (1.0.2)
Requirement already satisfied, skipping upgrade: botocore<1.13.0,>=1.12.75 in /home/israel/.local/lib/python3.6/site-packages (from boto3>=1.9.56,~=1.9->aws-sam-cli) (1.12.75)
Requirement already satisfied, skipping upgrade: s3transfer<0.2.0,>=0.1.10 in /home/israel/.local/lib/python3.6/site-packages (from boto3>=1.9.56,~=1.9->aws-sam-cli) (0.1.13)
Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in /usr/lib/python3/dist-packages (from boto3>=1.9.56,~=1.9->aws-sam-cli) (0.9.0)
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3/dist-packages (from aws-lambda-builders==0.0.5->aws-sam-cli) (20.7.0)
Requirement already satisfied, skipping upgrade: wheel in /usr/lib/python3/dist-packages (from aws-lambda-builders==0.0.5->aws-sam-cli) (0.29.0)
Requirement already satisfied, skipping upgrade: pytz in /usr/lib/python3/dist-packages (from dateparser~=0.7->aws-sam-cli) (2014.10)
Collecting tzlocal (from dateparser~=0.7->aws-sam-cli)
Collecting regex (from dateparser~=0.7->aws-sam-cli)
  Using cached https://files.pythonhosted.org/packages/16/07/ee3e02770ed456a088b90da7c9b1e9aa227e3c956d37b845cef2aab93764/regex-2018.11.22.tar.gz
Requirement already satisfied, skipping upgrade: docker-pycreds>=0.3.0 in /home/israel/.local/lib/python3.6/site-packages (from docker>=3.3.0->aws-sam-cli) (0.4.0)
Requirement already satisfied, skipping upgrade: websocket-client>=0.32.0 in /home/israel/.local/lib/python3.6/site-packages (from docker>=3.3.0->aws-sam-cli) (0.54.0)
Collecting binaryornot>=0.2.0 (from cookiecutter~=1.6.0->aws-sam-cli)
  Using cached https://files.pythonhosted.org/packages/24/7e/f7b6f453e6481d1e233540262ccbfcf89adcd43606f44a028d7f5fae5eb2/binaryornot-0.4.4-py2.py3-none-any.whl
Collecting jinja2-time>=0.1.0 (from cookiecutter~=1.6.0->aws-sam-cli)
  Using cached https://files.pythonhosted.org/packages/6a/a1/d44fa38306ffa34a7e1af09632b158e13ec89670ce491f8a15af3ebcb4e4/jinja2_time-0.2.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: jinja2>=2.7 in /home/israel/.local/lib/python3.6/site-packages (from cookiecutter~=1.6.0->aws-sam-cli) (2.10)
Collecting whichcraft>=0.4.0 (from cookiecutter~=1.6.0->aws-sam-cli)
  Using cached https://files.pythonhosted.org/packages/ab/c6/eb4d1dfbb68168bb01c4394420e5e71d5851e64b910838aa0f14ebd5c7a0/whichcraft-0.5.2-py2.py3-none-any.whl
Collecting poyo>=0.1.0 (from cookiecutter~=1.6.0->aws-sam-cli)
  Using cached https://files.pythonhosted.org/packages/e0/16/e00e3001007a5e416ca6a51def6f9e4be6a774bf1c8486d20466f834d113/poyo-0.4.2-py2.py3-none-any.whl
Collecting future>=0.15.2 (from cookiecutter~=1.6.0->aws-sam-cli)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/israel/.local/lib/python3.6/site-packages (from requests==2.20.1->aws-sam-cli) (2018.11.29)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /home/israel/.local/lib/python3.6/site-packages (from requests==2.20.1->aws-sam-cli) (1.24.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /home/israel/.local/lib/python3.6/site-packages (from requests==2.20.1->aws-sam-cli) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /home/israel/.local/lib/python3.6/site-packages (from requests==2.20.1->aws-sam-cli) (2.7)
Requirement already satisfied, skipping upgrade: jsonschema~=2.6 in /home/israel/.local/lib/python3.6/site-packages (from aws-sam-translator==1.9.0->aws-sam-cli) (2.6.0)
Collecting enum34~=1.1 (from aws-sam-translator==1.9.0->aws-sam-cli)
  Using cached https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Requirement already satisfied, skipping upgrade: Werkzeug>=0.14 in /home/israel/.local/lib/python3.6/site-packages (from Flask~=1.0.2->aws-sam-cli) (0.14.1)
Requirement already satisfied, skipping upgrade: itsdangerous>=0.24 in /home/israel/.local/lib/python3.6/site-packages (from Flask~=1.0.2->aws-sam-cli) (1.1.0)
Requirement already satisfied, skipping upgrade: docutils>=0.10 in /usr/lib/python3/dist-packages (from botocore<1.13.0,>=1.12.75->boto3>=1.9.56,~=1.9->aws-sam-cli) (0.12)
Collecting arrow (from jinja2-time>=0.1.0->cookiecutter~=1.6.0->aws-sam-cli)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from jinja2>=2.7->cookiecutter~=1.6.0->aws-sam-cli) (0.23)
Building wheels for collected packages: regex
  Running setup.py bdist_wheel for regex ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-obd5rx2_/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-esowcqhr --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  copying regex_3/regex.py -> build/lib.linux-x86_64-3.6
  copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.6
  copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.6
  running build_ext
  building '_regex' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/regex_3
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o
  regex_3/_regex.c:46:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for regex
  Running setup.py clean for regex
Failed to build regex
Installing collected packages: tzlocal, regex, dateparser, binaryornot, arrow, jinja2-time, whichcraft, poyo, future, cookiecutter, enum34, aws-sam-translator, aws-sam-cli
  Running setup.py install for regex ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-obd5rx2_/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-vpv7qosg/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying regex_3/regex.py -> build/lib.linux-x86_64-3.6
    copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.6
    copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.6
    running build_ext
    building '_regex' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/regex_3
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o
    regex_3/_regex.c:46:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-obd5rx2_/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-vpv7qosg/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-obd5rx2_/regex/```

**Comment by jfuss** [comment]
Is there any reason you don't just want to use LinuxBrew to install? All this should be avoidable if you just use the installers instead of pip. Using pip will have these pitfalls where our installation is completely dependent on how you install python (among other things), which is something outside of installing our CLI.

**Comment by IsraelGboluwaga** [comment]
I'm simply following the steps from `https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html`

I'll take a look at using LinuxBrew and give you feedback.

**Comment by jfuss** [comment]
The Linux specific guide has details on LinuxBrew: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html. We are working on removing the pip details to customers can get started on the right foot and hopefully avoid some of the pain points you have run into.

**Comment by IsraelGboluwaga** [comment]
Do I simply do `brew install aws-sam-cli` ??

**Comment by jfuss** [comment]
You can follow the docs under "Install the AWS SAM CLI Using Linuxbrew" in the link I have above. This describes the step need to install.

**Comment by IsraelGboluwaga** [comment]
After seeming successful installation, I ran `sam --version` and I got this output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/dbm/gnu.py", line 4, in <module>
    from _gdbm import *
ModuleNotFoundError: No module named '_gdbm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 7, in <module>
    import dbm.gnu as gdbm
  File "/usr/lib/python3.6/dbm/gnu.py", line 6, in <module>
    raise ImportError(str(msg) + ', please install the python3-gdbm package')
ImportError: No module named '_gdbm', please install the python3-gdbm package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 27, in <module>
    from CommandNotFound.util import crash_guard
  File "/usr/lib/python3/dist-packages/CommandNotFound/__init__.py", line 3, in <module>
    from CommandNotFound.CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 9, in <module>
    import gdbm
ModuleNotFoundError: No module named 'gdbm'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.6/dbm/gnu.py", line 4, in <module>
    from _gdbm import *
ModuleNotFoundError: No module named '_gdbm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 7, in <module>
    import dbm.gnu as gdbm
  File "/usr/lib/python3.6/dbm/gnu.py", line 6, in <module>
    raise ImportError(str(msg) + ', please install the python3-gdbm package')
ImportError: No module named '_gdbm', please install the python3-gdbm package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 27, in <module>
    from CommandNotFound.util import crash_guard
  File "/usr/lib/python3/dist-packages/CommandNotFound/__init__.py", line 3, in <module>
    from CommandNotFound.CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 9, in <module>
    import gdbm
ModuleNotFoundError: No module named 'gdbm'
```

**Comment by IsraelGboluwaga** [comment]
Thank you @jfuss for all the help. It's successfully installed now. I should have used a virtual environment all along.

**Comment by yort-feng** [comment]
> Thank you @jfuss for all the help. It's successfully installed now. I should have used a virtual environment all along.

@IsraelGboluwaga I'm facing a same problem, what do you mean by "virtual environment"?

**Comment by kyuridenamida** [comment]
I faced the same error on Python 3.5.2.
I switched to python 3.7 instead and the installation succeeded with the following command:
 `python3.7 -m pip install aws-sam-cli`

**Comment by yort-feng** [comment]
> I faced the same error on Python 3.5.2.
> I switched to python 3.7 instead and the installation succeeded with the following command:
> `python3.7 -m pip install aws-sam-cli`

I'd tried it, but it didn't work for me, thank you anyway!

**Comment by Scottbae37** [comment]
> ild_ext
>   building '_regex' extension
>   creating build/temp.linux-x86_64-3.6
>   creating build/temp.linux-x86_64-3.6/regex_3
>   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.6/regex_3/_regex.o
>   regex_3/_regex.c:46:20: fatal error: Python.h: No such file or directory
>   compilation termina

https://github.com/awslabs/aws-sam-cli/issues/922#issuecomment-452366133

It seems that you have already solved in other ways.
Just for anyone who wants to solve the problem above, Please try again after installing python dev package. That works for me, I'm using python3.6, pip3.6

$ sudo apt-get install python3.6-dev 
$ sudo pip3.6 install aws-sam-cli


For the problem installing aws-sam-cli with pip3.6

**Comment by yashdattsawant** [comment]
> I faced the same error on Python 3.5.2.
> I switched to python 3.7 instead and the installation succeeded with the following command:
> `python3.7 -m pip install aws-sam-cli`

This worked for me as well. Thanks

**Comment by pequetreques** [comment]
Not sure if this is the right way to reopen this issue.
I followed the [Installing the AWS SAM CLI on Linux](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html) steps with Homebrew for Linux (Ubuntu 20) but after a successfull installation I got a command not found error when tried: `sam --version`

So I did `brew uninstall aws-sam-cli`, and then tried:
`git clone https://github.com/awslabs/aws-sam-cli.git
cd aws-sam-cli
sudo python3 ./setup.py build install`

I have this Python:
$ python3 --version
Python 3.8.5

Everything seemed well until I got this:
Installed /usr/local/lib/python3.8/dist-packages/aws_sam_cli-1.15.0-py3.8.egg
Processing dependencies for aws-sam-cli==1.15.0
error: six 1.14.0 is installed but six~=1.15 is required by {'aws-sam-translator'}
(first two lines for context)

Then I tried this:
```
$ sam --version
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.14.0 (/usr/lib/python3/dist-packages), Requirement.parse('six~=1.15'), {'aws-sam-translator'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.14.0 (/usr/lib/python3/dist-packages), Requirement.parse('six~=1.15'), {'aws-sam-translator'})
```

Could you please support me with this issue?
I'm trying to set up my environment properly, in order to run locally a lambda function written in TypeScript over Node.js

Thanks in advance!
