### ISSUE TITLE
Sam local command does not work on Ubuntu 16.04 venv

### ISSUE THREAD

**Issue by IsraelGboluwaga** [awslabs/aws-sam-cli#923]
### Sam local does not work on Ubuntu 16.04 venv

Trying to run `sam local start-api`, I ran into a docker blocker. Asking for installation, even though installed.

### Steps to reproduce

Run `sam local start-api`
### Observed result
```
2019-01-09 14:14:55 Found credentials in shared credentials file: ~/.aws/credentials
Error: Running AWS SAM projects locally requires Docker. Have you got it installed?
```

With the `--debug` flag set:
```
2019-01-09 14:19:29 Using SAM Template at /home/israel/lambda/sam-app/template.yaml
2019-01-09 14:19:29 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-01-09 14:19:29 Changing event name from before-call.apigateway to before-call.api-gateway
2019-01-09 14:19:29 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-01-09 14:19:29 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-01-09 14:19:29 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-01-09 14:19:29 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-01-09 14:19:29 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-01-09 14:19:29 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-01-09 14:19:29 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-01-09 14:19:29 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-01-09 14:19:29 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-01-09 14:19:29 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-01-09 14:19:29 Changing event name from before-call.apigateway to before-call.api-gateway
2019-01-09 14:19:29 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-01-09 14:19:29 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-01-09 14:19:29 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-01-09 14:19:29 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-01-09 14:19:29 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-01-09 14:19:29 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-01-09 14:19:29 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-01-09 14:19:29 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-01-09 14:19:29 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-01-09 14:19:29 local start-api command is called
2019-01-09 14:19:29 Looking for credentials via: env
2019-01-09 14:19:29 Looking for credentials via: assume-role
2019-01-09 14:19:29 Looking for credentials via: shared-credentials-file
2019-01-09 14:19:29 Found credentials in shared credentials file: ~/.aws/credentials
2019-01-09 14:19:29 Loading JSON file: /home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/botocore/data/endpoints.json
2019-01-09 14:19:29 Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f6181c3a8c0>
2019-01-09 14:19:29 Loading JSON file: /home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/botocore/data/serverlessrepo/2017-09-08/service-2.json
2019-01-09 14:19:29 Event creating-client-class.serverlessapplicationrepository: calling handler <function add_generate_presigned_url at 0x7f6181c64230>
2019-01-09 14:19:29 The s3 config key is not a dictionary type, ignoring its value of: None
2019-01-09 14:19:29 Setting serverlessrepo timeout as (60, 60)
2019-01-09 14:19:29 Loading JSON file: /home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/botocore/data/_retry.json
2019-01-09 14:19:29 Registering retry handlers for service: serverlessrepo
2019-01-09 14:19:29 No Parameters detected in the template
2019-01-09 14:19:29 2 resources found in the template
2019-01-09 14:19:29 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2019-01-09 14:19:29 Trying paths: ['/home/israel/.docker/config.json', '/home/israel/.dockercfg']
2019-01-09 14:19:29 No config file found
2019-01-09 14:19:29 Trying paths: ['/home/israel/.docker/config.json', '/home/israel/.dockercfg']
2019-01-09 14:19:29 No config file found
2019-01-09 14:19:29 Docker is not reachable
Traceback (most recent call last):
  File "/home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/samcli/local/docker/manager.py", line 50, in is_docker_reachable
    self.docker_client.ping()
  File "/home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/docker/client.py", line 187, in ping
    return self.api.ping(*args, **kwargs)
  File "/home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/docker/api/daemon.py", line 166, in ping
    return self._result(self._get(self._url('/_ping'))) == 'OK'
  File "/home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/docker/api/client.py", line 215, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/israel/lambda/AWS-AppSync-Lambda-GraphQL-API/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))
Error: Running AWS SAM projects locally requires Docker. Have you got it installed?
```

Note: I'm running it in a virtual environment using Python 2.7.12

### Expected result
Normal function execution

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 16.04 LTS
2. `sam --version`:  0.10.0

**Comment by jfuss** [comment]
Is docker running on your machine?

**Comment by IsraelGboluwaga** [comment]
Yes, it is.

**Comment by jfuss** [comment]
Looks like the key piece is this: `ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))`. Docker saying the user needs access to the docker group. What is weird is that you can run docker from the command line. Did you follow https://docs.docker.com/install/linux/linux-postinstall/ when installing docker?

**Comment by IsraelGboluwaga** [comment]
Did you follow https://docs.docker.com/install/linux/linux-postinstall/ when installing docker?
=> I just did. Didn't change anything.

**Comment by DevOpsChris** [comment]
It's something to do with your docker service on ubuntu, not with aws sam.  

Stupid question, have you rebooted the machine?  Sometimes it works for me when I log out of my user.

**Comment by IsraelGboluwaga** [comment]
I'll restart my machine now and give feedback. Thanks @DevOpsChris 

I apologize for my stupid question. Try could be nicer too. 🙂

**Comment by DevOpsChris** [comment]
Oh that got lost in translation.  I'm sorry.

"Stupid question", was describing "have you rebooted the machine?"  It's a way of asking a question without assumptions, even if it does sound silly.  

It was not to describe your question for this issue that you started. 

Not having a tech work easily is frustrating.  Hope this helps!

**Comment by IsraelGboluwaga** [comment]
lol... It's okay. I read that over and got it. I'm sorry for misunderstanding you.

It worked after restarting my system. Thank you so much @DevOpsChris 
Once again, forgive me for misunderstanding.
Enjoy the rest of your day.

**Comment by freddie-freeloader** [comment]
Rebooting after sam-cli installation helped me too. Maybe this could be added to the installation manual. :relaxed:

**Comment by maglkp** [comment]
sadly, rebooting haven't worked for me - followed all the above too, on ubuntu 20.04

**Comment by KueiChinHuang** [comment]
Rebooting isn't working for me either. Does anyone have other solutions?

**Comment by Tilko** [comment]
me too (on WSL2), rebooting virtual ubuntu and even windows didn't solve it :(

**Comment by hikui** [comment]
Add your current user to the docker user group may help.

**Comment by rajanpanchal** [comment]
I also need solution..  getting same error
`sam local start-api
Error: Running AWS SAM projects locally requires Docker. Have you got it installed?
`

**Comment by fusion27** [comment]
### My Conditions
* Ubuntu 18.04
* Ran `sam local invoke HelloWorldFunction -e events/event.json`, yielded the following
```sh
Running AWS SAM projects locally requires Docker. Have you got it installed?
```

### What Worked

1. Visited [Docker's  post-installation recommendations](https://docs.docker.com/install/linux/linux-postinstall/)
2. Created group **docker** (_I already had it_)
    ```sh
    sudo groupadd docker
    groupadd: group 'docker' already exists
    ```
3. Added my user to the **docker** group
    ```sh
    sudo usermod -aG docker $USER
    ```
4. Rebooted my machine, ran the sam command again, exhaled, smiled
    ```sh
    sam local invoke HelloWorldFunction -e events/event.json
    ```

**Comment by rajanpanchal** [comment]
> ### My Conditions
> * Ubuntu 18.04
> * Ran `sam local invoke HelloWorldFunction -e events/event.json`, yielded the following
> 
> ```shell
> Running AWS SAM projects locally requires Docker. Have you got it installed?
> ```
> 
> ### What Worked
> 1. Visited [Docker's  post-installation recommendations](https://docs.docker.com/install/linux/linux-postinstall/)
> 2. Created group **docker** (_I already had it_)
>    ```shell
>    sudo groupadd docker
>    groupadd: group 'docker' already exists
>    ```
> 3. Added my user to the **docker** group
>    ```shell
>    sudo usermod -aG docker $USER
>    ```
> 4. Rebooted my machine, ran the sam command again, exhaled, smiled
>    ```shell
>    sam local invoke HelloWorldFunction -e events/event.json
>    ```

For me, user was already added to the group. What worked for me was running the command with sudo su

**Comment by nkpatil11** [comment]
i have also rebooted my machine it does not work for me
any please helps me out?

Thanks

**Comment by fusion27** [comment]
@nkpatil11 please indicate

1. What are you trying to do and what do you expect to happen?
2. What command(s) are you attempting to execute?
3. What is the error message you're receiving?
4. What the OS and version of the machine you're working on?

**Comment by nkpatil11** [comment]
> @nkpatil11 please indicate
> 
> 1. What are you trying to do and what do you expect to happen?
> 2. What command(s) are you attempting to execute?
> 3. What is the error message you're receiving?
> 4. What the OS and version of the machine you're working on?

Hey @fusion27 thanks for the reply
below commands, I have tried and my os and version is 'ubuntu 16.04 LTS'

> 1. What are you trying to do and what do you expect to happen?
>> I am trying to run sam apis in the docker container.

> 2. What command(s) are you attempting to execute?
>>  sam local start-api --docker-network local-dev --env-vars config/config.json

> 3. What is the error message you're receiving?
>> Error: Running AWS SAM projects locally requires Docker. Have you got it installed and running?

> 4. What the OS and version of the machine you're working on?
>> ubuntu 16.04 LTS

Thanks

**Comment by rajanpanchal** [comment]
@nkpatil11 have you tried executing the same command with "sudo su"?

**Comment by nkpatil11** [comment]
> @nkpatil11 have you tried executing the same command with "sudo su"?

thanks @rajanpanchal 
yes, I tried with 'sudo su' but in this case returning another message -
The program 'sam' is currently not installed. You can install it by typing:
apt install simon

even i have installed SAM CLI version 1.15.0

**Comment by fusion27** [comment]
@nkpatil11 I'm suspicious of your installations.  This is what is returned when I execute the following commands:

#### SAM version 

```sh
sam --version
SAM CLI, version 0.53.0
```

#### Docker version

```sh
docker --version
Docker version 19.03.13, build 4484c46d9d
```

### QUESTIONS

1. What does your terminal return when you run :point_up:  these commands :point_up:  ?
2. Can you please post a link to documentation you followed to install Docker on Ubuntu?

**Comment by nkpatil11** [comment]
Thanks, @fusion27  now i got the success to run sam api with the help of your first message

OS > Ubuntu 18.04
SAM version -> SAM CLI, version 1.15.0
Docker version -> Docker version 20.10.2, build 2291f61

> 
> ### What Worked
> 1. Visited [Docker's  post-installation recommendations](https://docs.docker.com/install/linux/linux-postinstall/)
> 2. Created group **docker** (_I already had it_)
>    ```
>    sudo groupadd docker
>    groupadd: group 'docker' already exists
>    ```
> 3. Added my user to the **docker** group
>    ```
>    sudo usermod -aG docker $USER
>    ```
> 4. Rebooted my machine, ran the sam command again, exhaled, smiled
>    ```
>    sam local invoke HelloWorldFunction -e events/event.json
>    ```


Thank you so much again :)
