### ISSUE TITLE
aws-sam-local for aws-serverless-java-container not working for Spring Boot 2 Pets Store sample

### ISSUE THREAD

**Issue by giaunv** [awslabs/aws-sam-cli#932]
### Description
aws-sam-local can work with aws-serverless-java-container on Jersey Pets Store example as #70  but can not with Spring Boot 2 sample

### Steps to reproduce

```
sam --version
SAM CLI, version 0.10.0

git clone git@github.com:awslabs/aws-serverless-java-container.git

cd aws-serverless-java-container/samples/springboot2/pet-store

mvn clean package

sam local start-api -t sam.yaml

curl http://localhost:3000/pets
```

Get this error

```
java.lang.ClassNotFoundException: com.amazonaws.serverless.sample.springboot.StreamLambdaHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

Function returned an invalid response (must include one of: body, headers or statusCode in the response object

```

**Comment by medinarrior** [comment]
sam.yaml has a mistake.

Change line 14 to:

Handler: com.amazonaws.serverless.sample.**springboot2**.StreamLambdaHandler::handleRequest

**Comment by jfuss** [comment]
Issue was in aws-serverless-java-container and @medinarrior submitted a fix to that repo. Closing as no issue with SAM CLI.
