### ISSUE TITLE
sam local invoke (Hello World lambda) MAC

### ISSUE THREAD

**Issue by es-karthic** [awslabs/aws-sam-cli#938]
### Description

I am getting the following exception while running sam local invoke --no-event
2019-01-15 20:27:14 Found credentials in shared credentials file: ~/.aws/credentials
2019-01-15 20:27:14 Invoking app.lambdaHandler (nodejs8.10)

Fetching lambci/lambda:nodejs8.10 Docker container image......
2019-01-15 20:27:19 Mounting /Volumes/MHD3/aws/lambda-sam/my-hello-world/hello-world as /var/task:ro inside runtime container
START RequestId: 24707dcc-b8f0-172e-3367-dfabec7bcc59 Version: $LATEST
Unable to import module 'app': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
END RequestId: 24707dcc-b8f0-172e-3367-dfabec7bcc59
REPORT RequestId: 24707dcc-b8f0-172e-3367-dfabec7bcc59  Duration: 4.68 ms       Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 30 MB

{"errorMessage":"Cannot find module '/var/task/app'","errorType":"Error","stackTrace":["Function.Module._load (module.js:474:25)","Module.require (module.js:596:17)","require (internal/module.js:11:18)"]}
### Steps to reproduce

sam init --runtime nodejs8.10 --name my-hello-world 
cd hello-world
npm install
cd ..
sam local invoke --no-event 

I have not done any changes to the code. I am running docker from the docker tool kit.
I don't find /var/task folder in the docker container. Please let me know.

### Observed result

2019-01-15 20:29:01 Using SAM Template at /Volumes/MHD3/aws/lambda-sam/my-hello-world/template.yaml
2019-01-15 20:29:01 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-01-15 20:29:01 Changing event name from before-call.apigateway to before-call.api-gateway
2019-01-15 20:29:01 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-01-15 20:29:01 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-01-15 20:29:01 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-01-15 20:29:01 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-01-15 20:29:01 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-01-15 20:29:01 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-01-15 20:29:01 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-01-15 20:29:01 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-01-15 20:29:01 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-01-15 20:29:01 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-01-15 20:29:01 Changing event name from before-call.apigateway to before-call.api-gateway
2019-01-15 20:29:01 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-01-15 20:29:01 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-01-15 20:29:01 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-01-15 20:29:01 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-01-15 20:29:01 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-01-15 20:29:01 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-01-15 20:29:01 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-01-15 20:29:01 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-01-15 20:29:01 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-01-15 20:29:01 local invoke command is called
2019-01-15 20:29:01 Looking for credentials via: env
2019-01-15 20:29:01 Looking for credentials via: assume-role
2019-01-15 20:29:01 Looking for credentials via: shared-credentials-file
2019-01-15 20:29:01 Found credentials in shared credentials file: ~/.aws/credentials
2019-01-15 20:29:01 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/endpoints.json
2019-01-15 20:29:01 Event choose-service-name: calling handler <function handle_service_name_alias at 0x110bdd598>
2019-01-15 20:29:01 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/serverlessrepo/2017-09-08/service-2.json
2019-01-15 20:29:01 Event creating-client-class.serverlessapplicationrepository: calling handler <function add_generate_presigned_url at 0x110ba4488>
2019-01-15 20:29:01 The s3 config key is not a dictionary type, ignoring its value of: None
2019-01-15 20:29:01 Setting serverlessrepo timeout as (60, 60)
2019-01-15 20:29:01 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/_retry.json
2019-01-15 20:29:01 Registering retry handlers for service: serverlessrepo
2019-01-15 20:29:01 No Parameters detected in the template
2019-01-15 20:29:01 2 resources found in the template
2019-01-15 20:29:01 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2019-01-15 20:29:01 Trying paths: ['/Users/eskarthic/.docker/config.json', '/Users/eskarthic/.dockercfg']
2019-01-15 20:29:01 Found file at path: /Users/eskarthic/.docker/config.json
2019-01-15 20:29:01 Couldn't find auth-related section ; attempting to interpret as auth-only file
2019-01-15 20:29:01 Config entry for key stackOrchestrator is not auth config

2019-01-15 20:29:01 Event choose-service-name: calling handler <function handle_service_name_alias at 0x110bdd598>
2019-01-15 20:29:01 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/lambda/2015-03-31/service-2.json
2019-01-15 20:29:01 Event creating-client-class.lambda: calling handler <function add_generate_presigned_url at 0x110ba4488>
2019-01-15 20:29:01 The s3 config key is not a dictionary type, ignoring its value of: None
2019-01-15 20:29:02 Setting lambda timeout as (60, 60)
2019-01-15 20:29:02 Registering retry handlers for service: lambda
2019-01-15 20:29:02 Trying paths: ['/Users/eskarthic/.docker/config.json', '/Users/eskarthic/.dockercfg']
2019-01-15 20:29:02 Found file at path: /Users/eskarthic/.docker/config.json
2019-01-15 20:29:02 Couldn't find auth-related section ; attempting to interpret as auth-only file
2019-01-15 20:29:02 Config entry for key stackOrchestrator is not auth config
2019-01-15 20:29:02 Found one Lambda function with name 'HelloWorldFunction'
2019-01-15 20:29:02 Invoking app.lambdaHandler (nodejs8.10)
2019-01-15 20:29:02 Environment variables overrides data is standard format
2019-01-15 20:29:02 Loading AWS credentials from session with profile 'default'
2019-01-15 20:29:02 Resolving code path. Cwd=/Volumes/MHD3/aws/lambda-sam/my-hello-world, CodeUri=hello-world/
2019-01-15 20:29:02 Resolved absolute path to code is /Volumes/MHD3/aws/lambda-sam/my-hello-world/hello-world
2019-01-15 20:29:02 Code /Volumes/MHD3/aws/lambda-sam/my-hello-world/hello-world is not a zip/jar file
2019-01-15 20:29:02 Skipping building an image since no layers were defined
2019-01-15 20:29:02 Trying paths: ['/Users/eskarthic/.docker/config.json', '/Users/eskarthic/.dockercfg']
2019-01-15 20:29:02 Found file at path: /Users/eskarthic/.docker/config.json
2019-01-15 20:29:02 Couldn't find auth-related section ; attempting to interpret as auth-only file

2019-01-15 20:29:02 Looking for auth config
2019-01-15 20:29:02 No auth config in memory - loading from filesystem
2019-01-15 20:29:02 Trying paths: ['/Users/eskarthic/.docker/config.json', '/Users/eskarthic/.dockercfg']
2019-01-15 20:29:02 Found file at path: /Users/eskarthic/.docker/config.json
2019-01-15 20:29:02 Couldn't find auth-related section ; attempting to interpret as auth-only file
2019-01-15 20:29:02 Config entry for key stackOrchestrator is not auth config
2019-01-15 20:29:02 Looking for auth entry for 'docker.io'
2019-01-15 20:29:02 No entry found
2019-01-15 20:29:02 No auth config found

Fetching lambci/lambda:nodejs8.10 Docker container image......
2019-01-15 20:29:06 Mounting /Volumes/MHD3/aws/lambda-sam/my-hello-world/hello-world as /var/task:ro inside runtime container

2019-01-15 20:29:06 https://***** "POST /containers/2ba097787a5e732a718c91a1024f02aa7e7e9a973b491990ac2dbb8869e6c645/attach?stdout=1&stderr=1&logs=1&stream=1&stdin=0 HTTP/1.1" 101 0
START RequestId: a712e2c9-3b48-1b87-3bbe-019ad5400e6c Version: $LATEST
Unable to import module 'app': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
END RequestId: a712e2c9-3b48-1b87-3bbe-019ad5400e6c
REPORT RequestId: a712e2c9-3b48-1b87-3bbe-019ad5400e6c  Duration: 6.98 ms       Billed Duration: 100 ms Memory Size: 128 MB     Max Memory Used: 29 MB
2019-01-15 20:29:06 Starting new HTTPS connection (2): 192.168.99.100:2376
2019-01-15 20:29:06 https://***** "GET /v1.35/containers/2ba097787a5e732a718c91a1024f02aa7e7e9a973b491990ac2dbb8869e6c645/json HTTP/1.1" 200 None
2019-01-15 20:29:06 https://**** "DELETE /v1.35/containers/2ba097787a5e732a718c91a1024f02aa7e7e9a973b491990ac2dbb8869e6c645?v=False&link=False&force=True HTTP/1.1" 204 0

{"errorMessage":"Cannot find module '/var/task/app'","errorType":"Error","stackTrace":["Function.Module._load (module.js:474:25)","Module.require (module.js:596:17)","require (internal/module.js:11:18)"]}

### Expected result

Describe what you expected.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MAC
2. `sam --version`SAM CLI, version 0.10.0

`Add --debug flag to command you are running`

**Comment by es-karthic** [comment]
I will try that. Thanks for the help

**Comment by jaakkomutikainen** [comment]
I'm having the same issue. Unfortunately @phijacobs, your solution didn't work for me :(

**Comment by TheSriram** [comment]
I would suggest moving to docker for windows instead.

**Comment by es-karthic** [comment]
@jaakkomutikainen  Apologize for the delay in response. I could resolve the issue. @phijacobs solution worked for me. 

@TheSriram Thanks for your response. But I don't get why you were asking me to move to windows.
