### ISSUE TITLE
`sam build --use-container` fails with hello_world, ConnectionError, FileNotFoundError

### ISSUE THREAD

**Issue by mxye** [awslabs/aws-sam-cli#958]
### Description

On MacOSX Mojave (10.14.2) `sam build --use-container` fails with the "hello-world" app in the aws lambda [quick start guide](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-quick-start.html).  

### Steps to reproduce

Install both awscli and aws-sam-cli with homebrew. Follow the guide. 

### Observed result

Error message:

```
2019-01-24 20:01:34 Building resource 'HelloWorldFunction'
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.10.0', 'console_scripts', 'sam')()
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 94, in cli
    skip_pull_image, parameter_overrides)  # pragma: no cover
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/commands/build/command.py", line 132, in do_cli
    artifacts = builder.build()
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 129, in build
    lambda_function.runtime)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 201, in _build_function
    runtime)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/lib/build/app_builder.py", line 249, in _build_function_on_container
    self._container_manager.run(container)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/local/docker/manager.py", line 75, in run
    is_image_local = self.has_image(image_name)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/local/docker/manager.py", line 153, in has_image
    self.docker_client.images.get(image_name)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/docker/api/image.py", line 245, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/docker/api/client.py", line 225, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

### Interventions tried

- `aws --version` shows:
aws-cli/1.16.94 Python/3.7.2 Darwin/18.2.0 botocore/1.12.84
- reinstalled awscli and aws-sam-cli
- brew doctor reports no error

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOSX Mojave (10.14.2)
2. `sam --version`: 
> SAM CLI, version 0.10.0

`Add --debug flag to command you are running`

**Comment by izjenie** [comment]
Hi, got the same error. Here's the --debug flag output:

```
2019-01-28 05:30:41 Using SAM Template at /Users/izakjenie/Documents/Proogramming/javascript/sam-app/template.yaml
2019-01-28 05:30:41 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-01-28 05:30:41 Changing event name from before-call.apigateway to before-call.api-gateway
2019-01-28 05:30:41 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-01-28 05:30:41 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-01-28 05:30:41 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-01-28 05:30:41 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-01-28 05:30:41 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-01-28 05:30:41 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-01-28 05:30:41 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-01-28 05:30:41 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-01-28 05:30:41 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-01-28 05:30:41 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-01-28 05:30:41 Changing event name from before-call.apigateway to before-call.api-gateway
2019-01-28 05:30:41 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-01-28 05:30:41 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-01-28 05:30:41 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-01-28 05:30:41 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-01-28 05:30:41 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-01-28 05:30:41 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-01-28 05:30:41 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-01-28 05:30:41 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-01-28 05:30:41 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-01-28 05:30:41 'build' command is called
2019-01-28 05:30:41 Starting Build inside a container
2019-01-28 05:30:42 Looking for credentials via: env
2019-01-28 05:30:42 Looking for credentials via: assume-role
2019-01-28 05:30:42 Looking for credentials via: shared-credentials-file
2019-01-28 05:30:42 Found credentials in shared credentials file: ~/.aws/credentials
2019-01-28 05:30:42 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/endpoints.json
2019-01-28 05:30:42 Event choose-service-name: calling handler <function handle_service_name_alias at 0x105e54510>
2019-01-28 05:30:42 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/serverlessrepo/2017-09-08/service-2.json
2019-01-28 05:30:42 Event creating-client-class.serverlessapplicationrepository: calling handler <function add_generate_presigned_url at 0x105e14400>
2019-01-28 05:30:42 The s3 config key is not a dictionary type, ignoring its value of: None
2019-01-28 05:30:42 Setting serverlessrepo timeout as (60, 60)
2019-01-28 05:30:42 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/_retry.json
2019-01-28 05:30:42 Registering retry handlers for service: serverlessrepo
2019-01-28 05:30:42 No Parameters detected in the template
2019-01-28 05:30:42 2 resources found in the template
2019-01-28 05:30:42 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2019-01-28 05:30:42 Trying paths: ['/Users/izakjenie/.docker/config.json', '/Users/izakjenie/.dockercfg']
2019-01-28 05:30:42 Found file at path: /Users/izakjenie/.docker/config.json
2019-01-28 05:30:42 Couldn't find auth-related section ; attempting to interpret as auth-only file
2019-01-28 05:30:42 Config entry for key credSstore is not auth config
2019-01-28 05:30:42 Building resource 'HelloWorldFunction'
2019-01-28 05:30:42 Trying paths: ['/Users/izakjenie/.docker/config.json', '/Users/izakjenie/.dockercfg']
2019-01-28 05:30:42 Found file at path: /Users/izakjenie/.docker/config.json
2019-01-28 05:30:42 Couldn't find auth-related section ; attempting to interpret as auth-only file
2019-01-28 05:30:42 Config entry for key credSstore is not auth config
```

**Comment by TestAndunR** [comment]
I am also facing this issue

**Comment by kikuomax** [comment]
I also faced the same issue.
In my case, I simply forgot to run a [Docker](https://www.docker.com) service. After starting a Docker service on my machine, it resolved.

**Comment by mxye** [comment]
It's been a few days since I last posted this issue. In my case, I eventually moved away from AWS lambda to Google Cloud Functions. The documentation is easy to follow step by step. Hello-world type of apps with GCF didn't fail. Local emulator there was also easy to use. And later I got my actual app working.

**Comment by guijob** [comment]
> I also faced the same issue.
> In my case, I simply forgot to run a [Docker](https://www.docker.com) service. After starting a Docker service on my machine, it resolved.

You didn't forget, docs just don't tell us to make it.

**Comment by fcasals** [comment]
same here; just fire up docker and "problem" solved.
docs should be updated in order to advice this dependency

cheers!

**Comment by jfuss** [comment]
The Quickstarts do link out to our [installation docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html) which call out docker needs to be installed. What would make this clearer?

**Comment by fcasals** [comment]
totally true @jfuss, I missed that link. 
thanks

**Comment by TheSriram** [comment]
Closing this issue, as installations docs point to docker needing to be installed.
