### ISSUE TITLE
Can't run sam init using a template that's stored in a private repository

### ISSUE THREAD

**Issue by ja-ro-hn** [awslabs/aws-sam-cli#969]
### Description

I can't run `sam init --location git+ssh://git@github.com:ja-ro-hn/MY_REPO.git` when MY_REPO is private - the command returns the following error:
`subprocess.CalledProcessError: Command '['git', 'clone', 'ssh://git@github.com:ja-ro-hn/MY_REPO.git']' returned non-zero exit status 128.`
My public key has permission to access my GitHub account, and my repositories.  
If I run `sam init --location gh:ja-ro-hn/MY_REPO`, the SAM CLI will successfully download the template and create an instance of it (after prompting for my GitHub username and password).
If I run `sam init --location git+ssh://git@github.com/aws-samples/cookiecutter-aws-sam-python.git` to retrieve a (public) template from GitHub, the command executes successfully - this suggests that the issue only occurs when you try to use a template that's stored in a **private** repository. 

The issue here is that some of our SAM projects are on Bitbucket and GitLab - for which the SAM CLI doesn't provide a command that's similar to `sam init --location gh:ja-ro-hn/MY_REPO`. This means that we have no way to get the template from directly from a private repository via SSH - instead we have to clone out the repo, zip it, then reference the zip file using  `sam init --template <PATH_TO_TEMPLATE_ZIP>`.

**EDIT:** My SSH key is password protected. This issue occurs regardless of whether I have unlocked it with the password.

### Steps to reproduce

-  Create a private repository containing a SAM template.
-  Run the command `sam init --location git+ssh://git@github.com:<YOUR_USERNAME>/<YOUR_REPO>.git`.

### Observed result

`[+] Initializing project structure...
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.10.0', 'console_scripts', 'sam')()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/commands/init/__init__.py", line 70, in cli
    name, no_input)  # pragma: no cover
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/commands/init/__init__.py", line 81, in do_cli
    generate_project(location, runtime, output_dir, name, no_input)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/samcli/local/init/__init__.py", line 87, in generate_project
    cookiecutter(**params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/cookiecutter/main.py", line 63, in cookiecutter
    password=password
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/cookiecutter/repository.py", line 103, in determine_repo_dir
    no_input=no_input,
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/cookiecutter/vcs.py", line 99, in clone
    stderr=subprocess.STDOUT,
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', 'ssh://git@github.com:ja-ro-hn/MY_REPO.git']' returned non-zero exit status 128.`

### Expected result

To successfully pull in a private template repository using the `sam init --location git+ssh://git@github.com:ja-ro-hn/MY_REPO.git` command.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux Mint 18 (Sarah)
2. `sam --version`: 0.10.0

`Add --debug flag to command you are running`

**Comment by avanathan** [comment]
I too am facing same issue on Mac Mojave, with version `SAM CLI, version 0.11.0`

**Comment by sriram-mv** [comment]
This is is not a cookiecutter limitation which is what powers sam init.

https://cookiecutter.readthedocs.io/en/1.7.0/usage.html#works-with-private-repos

does the git executable, we shell out to have access location of ssh keys?

Feel free to reopen if you are still facing this issue, closing it.
